import type { DhikrItem } from '@/components/dhikr/DhikrCounter';

export const MORNING_ADHKAR: DhikrItem[] = [
  {
    title: 'Âyat al-Kursî',
    arabic: 'أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ\nاللّهُ لاَ إِلَـهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    phonetic: "A'ûdhu bi-llâhi mina sh-shaytâni r-rajîm. Allâhu lâ ilâha illâ huwa-l-Hayyu-l-Qayyûm, lâ ta'khudhuhu sinatun wa lâ nawm, lahu mâ fî s-samâwâti wa mâ fî-l-ard, man dhâ-lladhî yashfa'u 'indahu illâ bi-idhnih, ya'lamu mâ bayna aydîhim wa mâ khalfahum wa lâ yuhîtûna bi-shay'in min 'ilmihi illâ bi-mâ shâ', wasi'a kursiyyuhu s-samâwâti wa-l-ard, wa lâ ya'ûduhu hifzuhumâ wa huwa-l-'Aliyyu-l-'Azîm.",
    french: "Allah ! Point de divinité à part Lui, le Vivant, Celui qui subsiste par Lui-même. Ni somnolence ni sommeil ne Le saisissent. À Lui appartient tout ce qui est dans les cieux et sur la terre. Qui peut intercéder auprès de Lui sans Sa permission ? Il connaît leur passé et leur futur. Et de Sa science, ils n'embrassent que ce qu'Il veut. Son Trône déborde les cieux et la terre, dont la garde ne Lui coûte aucune peine. Et Il est le Très Haut, le Très Grand.",
    target: 1,
  },
  {
    title: 'Sourate Al-Ikhlâs',
    arabic: 'بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ هُوَ ٱللَّهُ أَحَدٌ ۝ ٱللَّهُ ٱلصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌ',
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul huwa-llâhu Ahad. Allâhu s-Samad. Lam yalid wa lam yûlad. Wa lam yakun lahu kufuwan ahad.",
    french: "Dis : «Il est Allah, Unique. Allah, Le Seul à être imploré pour ce que nous désirons. Il n'a jamais engendré, n'a pas été engendré non plus. Et nul n'est égal à Lui.»",
    target: 3,
  },
  {
    title: 'Sourate Al-Falaq',
    arabic: 'بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul a'ûdhu bi-Rabbi-l-falaq. Min sharri mâ khalaq. Wa min sharri ghâsiqin idhâ waqab. Wa min sharri n-naffâthâti fî-l-'uqad. Wa min sharri hâsidin idhâ hasad.",
    french: "Dis : «Je cherche protection auprès du Seigneur de l'aube naissante, contre le mal des êtres qu'Il a créés, contre le mal de l'obscurité quand elle s'approfondit, contre le mal de celles qui soufflent sur les nœuds, et contre le mal de l'envieux quand il envie.»",
    target: 3,
  },
  {
    title: 'Sourate An-Nâs',
    arabic: 'بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ ۝ مَلِكِ ٱلنَّاسِ ۝ إِلَٰهِ ٱلنَّاسِ ۝ مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ ۝ ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ ۝ مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ',
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul a'ûdhu bi-Rabbi n-nâs. Maliki n-nâs. Ilâhi n-nâs. Min sharri-l-waswâsi-l-khannâs. Alladhî yuwaswisu fî sudûri n-nâs. Mina-l-jinnati wa n-nâs.",
    french: "Dis : «Je cherche protection auprès du Seigneur des hommes, le Souverain des hommes, Dieu des hommes, contre le mal du mauvais conseiller, furtif, qui souffle le mal dans les poitrines des hommes, qu'il soit djinn ou être humain.»",
    target: 3,
  },
  {
    title: 'Dhikr du matin',
    arabic: 'أَصْـبَحْنا وَأَصْـبَحَ المُـلْكُ لِلَّهِ وَالحَمدُ لِلَّهِ، لا إلهَ إلاّ اللّهُ وَحدَهُ لا شَريكَ لهُ، لهُ المُـلكُ ولهُ الحَمْـد، وهُوَ على كلّ شَيءٍ قدير، رَبِّ أسْـأَلُـكَ خَـيرَ ما في هـذا اليوم وَخَـيرَ ما بَعْـدَه، وَأَعـوذُ بِكَ مِنْ شَـرِّ ما في هـذا اليوم وَشَرِّ ما بَعْـدَه، رَبِّ أَعـوذُ بِكَ مِنَ الْكَسَـلِ وَسـوءِ الْكِـبَر، رَبِّ أَعـوذُ بِكَ مِنْ عَـذابٍ في النّـارِ وَعَـذابٍ في القَـبْر',
    phonetic: "Asbahnâ wa asbaha-l-mulku li-llâh, wa-l-hamdu li-llâh, lâ ilâha illâ-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamd, wa huwa 'alâ kulli shay'in qadîr. Rabbi as'aluka khayra mâ fî hâdhâ-l-yawm wa khayra mâ ba'dah, wa a'ûdhu bika min sharri mâ fî hâdhâ-l-yawm wa sharri mâ ba'dah. Rabbi a'ûdhu bika mina-l-kasali wa sû'i-l-kibar. Rabbi a'ûdhu bika min 'adhâbin fî n-nâri wa 'adhâbin fî-l-qabr.",
    french: "Nous voilà au matin et le royaume appartient à Allah. Louange à Allah. Nulle divinité à part Allah, Seul sans associé. À Lui le royaume et à Lui la louange. Il est Omnipotent. Seigneur, je Te demande le bien de ce jour et le bien de ce qui vient après. Je me réfugie auprès de Toi contre le mal de ce jour et le mal de ce qui vient après. Je me réfugie auprès de Toi contre la paresse et les maux de la vieillesse. Je me réfugie auprès de Toi contre le châtiment du Feu et le châtiment de la tombe.",
    target: 1,
  },
  {
    title: 'Sayyid al-Istighfâr',
    arabic: 'اللّهـمَّ أَنْتَ رَبِّـي لا إلهَ إلاّ أَنْتَ، خَلَقْتَنـي وَأَنا عَبْـدُك، وَأَنا عَلـى عَهْـدِكَ وَوَعْـدِكَ ما اسْتَـطَعْـت، أَعـوذُ بِكَ مِنْ شَـرِّ ما صَنَـعْت، أَبـوءُ لَـكَ بِنِعْـمَتِـكَ عَلَـيَّ وَأَبـوءُ بِذَنْـبي فَاغْفـِرْ لي فَإِنَّـهُ لا يَغْـفِرُ الذُّنـوبَ إِلاّ أَنْتَ',
    phonetic: "Allâhumma anta Rabbî, lâ ilâha illâ ant, khalaqtanî wa ana 'abduk, wa ana 'alâ 'ahdika wa wa'dika mâ-stata't, a'ûdhu bika min sharri mâ sana't, abû'u laka bi-ni'matika 'alayya wa abû'u bi-dhanbî, fa-ghfir lî fa-innahu lâ yaghfiru dh-dhunûba illâ ant.",
    french: "Ô Allah, Tu es mon Seigneur, il n'y a de divinité que Toi. Tu m'as créé et je suis Ton serviteur. Je suis fidèle à mon engagement et à ma promesse envers Toi autant que je le peux. Je cherche refuge auprès de Toi contre le mal que j'ai fait. Je reconnais devant Toi Tes bienfaits sur moi et je reconnais mes péchés. Pardonne-moi, car nul ne pardonne les péchés à part Toi.",
    target: 1,
  },
  {
    title: 'Agrément d\'Allah',
    arabic: 'رَضيـتُ بِاللهِ رَبَّـاً وَبِالإسْلامِ ديـناً وَبِمُحَـمَّدٍ صلى الله عليه وسلم نَبِيّـاً',
    phonetic: "Radîtu bi-llâhi Rabban, wa bi-l-islâmi dînan, wa bi-Muhammadin (sallâ-llâhu 'alayhi wa sallam) nabiyyan.",
    french: "J'accepte Allah comme Seigneur, l'Islam comme religion et Muhammad ﷺ comme Prophète.",
    target: 3,
  },
  {
    title: 'Témoignage du matin',
    arabic: 'اللّهُـمَّ إِنِّـي أَصْبَـحْتُ أُشْـهِدُك، وَأُشْـهِدُ حَمَلَـةَ عَـرْشِـك، وَمَلَائِكَتَكَ، وَجَمـيعَ خَلْـقِك، أَنَّـكَ أَنْـتَ اللهُ لا إلهَ إلاّ أَنْـتَ وَحْـدَكَ لا شَريكَ لَـك، وَأَنَّ مُحَمّـداً عَبْـدُكَ وَرَسـولُـك',
    phonetic: "Allâhumma innî asbahtu ush-hiduk, wa ush-hidu hamalata 'arshik, wa malâ'ikatak, wa jamî'a khalqik, annaka anta-llâhu lâ ilâha illâ anta wahdaka lâ sharîka lak, wa anna Muhammadan 'abduka wa rasûluk.",
    french: "Ô Allah, je prends à témoin en ce matin, Toi, les porteurs de Ton Trône, Tes anges et toutes Tes créatures, que Tu es Allah, nulle divinité à part Toi, Seul sans associé, et que Muhammad est Ton serviteur et Ton messager.",
    target: 4,
  },
  {
    title: 'Reconnaissance des bienfaits',
    arabic: 'اللّهُـمَّ ما أَصْبَـحَ بي مِـنْ نِعْـمَةٍ أَو بِأَحَـدٍ مِـنْ خَلْـقِك، فَمِـنْكَ وَحْـدَكَ لا شريكَ لَـك، فَلَـكَ الْحَمْـدُ وَلَـكَ الشُّكْـر',
    phonetic: "Allâhumma mâ asbaha bî min ni'matin aw bi-ahadin min khalqik, fa-minka wahdaka lâ sharîka lak, fa-laka-l-hamdu wa laka sh-shukr.",
    french: "Ô Allah, tout bienfait dont je jouis en ce matin, ou dont jouit l'une de Tes créatures, provient de Toi Seul, sans associé. À Toi la louange et à Toi la reconnaissance.",
    target: 1,
  },
  {
    title: 'Tawakkul — La confiance',
    arabic: 'حَسْبِـيَ اللّهُ لا إلهَ إلاّ هُوَ عَلَـيهِ تَوَكَّـلتُ وَهُوَ رَبُّ العَرْشِ العَظـيم',
    phonetic: "Hasbiya-llâhu lâ ilâha illâ huwa, 'alayhi tawakkaltu wa huwa Rabbu-l-'arshi-l-'azîm.",
    french: "Allah me suffit, il n'y a de divinité que Lui. C'est en Lui que je place ma confiance et Il est le Seigneur du Trône immense.",
    target: 7,
  },
  {
    title: 'La Protection',
    arabic: 'بِسـمِ اللهِ الذي لا يَضُـرُّ مَعَ اسمِـهِ شَيءٌ في الأرْضِ وَلا في السّمـاءِ وَهـوَ السّمـيعُ العَلـيم',
    phonetic: "Bismi-llâhi-lladhî lâ yadurru ma'a-smihi shay'un fî-l-ardi wa lâ fî s-samâ'i wa huwa s-Samî'u-l-'Alîm.",
    french: "Au nom d'Allah, celui dont le nom protège de tout mal sur terre et dans les cieux. Il est l'Audient, l'Omniscient.",
    target: 3,
  },
  {
    title: 'Vivre et mourir pour Allah',
    arabic: 'اللّهُـمَّ بِكَ أَصْـبَحْنا وَبِكَ أَمْسَـينا، وَبِكَ نَحْـيا وَبِكَ نَمُـوتُ وَإِلَـيْكَ النُّـشُور',
    phonetic: "Allâhumma bika asbahnâ wa bika amsaynâ, wa bika nahyâ wa bika namûtu wa ilayka n-nushûr.",
    french: "Ô Allah, c'est par Toi que nous arrivons au matin et c'est par Toi que nous arrivons au soir. C'est par Toi que nous vivons et par Toi que nous mourons. Et c'est vers Toi la résurrection.",
    target: 1,
  },
  {
    title: 'Fitra de l\'Islam',
    arabic: 'أَصْبَـحْـنا عَلَى فِطْرَةِ الإسْلاَمِ، وَعَلَى كَلِمَةِ الإِخْلاَصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ، وَعَلَى مِلَّةِ أَبِينَا إبْرَاهِيمَ حَنِيفاً مُسْلِماً وَمَا كَانَ مِنَ المُشْرِكِينَ',
    phonetic: "Asbahnâ 'alâ fitrati-l-islâm, wa 'alâ kalimati-l-ikhlâs, wa 'alâ dîni nabiyyinâ Muhammadin (sallâ-llâhu 'alayhi wa sallam), wa 'alâ millati abînâ Ibrâhîma hanîfan musliman wa mâ kâna mina-l-mushrikîn.",
    french: "Nous sommes au matin sur la nature première de l'Islam, sur la parole de sincérité, sur la religion de notre Prophète Muhammad ﷺ, et sur la voie de notre père Abraham, monothéiste soumis, et il n'était point parmi les associateurs.",
    target: 1,
  },
  {
    title: 'Gloire à Allah',
    arabic: 'سُبْحـانَ اللهِ وَبِحَمْـدِهِ عَدَدَ خَلْـقِهِ، وَرِضـا نَفْسِـهِ، وَزِنَـةَ عَـرْشِـهِ، وَمِـدادَ كَلِمـاتِـهِ',
    phonetic: "Subhâna-llâhi wa bi-hamdihi 'adada khalqih, wa ridâ nafsih, wa zinata 'arshih, wa midâda kalimâtih.",
    french: "Gloire et louange à Allah autant que le nombre de Ses créatures, autant qu'Il agrée, autant que pèse Son Trône, et autant que l'encre de Ses paroles.",
    target: 3,
  },
  {
    title: 'Santé du corps',
    arabic: 'اللّهُـمَّ عافِـني في بَدَنـي، اللّهُـمَّ عافِـني في سَمْـعي، اللّهُـمَّ عافِـني في بَصَـري، لا إلهَ إلاّ أَنْـتَ',
    phonetic: "Allâhumma 'âfinî fî badanî, Allâhumma 'âfinî fî sam'î, Allâhumma 'âfinî fî basarî, lâ ilâha illâ ant.",
    french: "Ô Allah, accorde-moi la santé dans mon corps. Ô Allah, accorde-moi la santé dans mon ouïe. Ô Allah, accorde-moi la santé dans ma vue. Nulle divinité à part Toi.",
    target: 3,
  },
  {
    title: 'Refuge contre la mécréance',
    arabic: 'اللّهُـمَّ إِنّـي أَعـوذُ بِكَ مِنَ الْكُـفر، وَالفَـقْر، وَأَعـوذُ بِكَ مِنْ عَذابِ القَـبْر، لا إلهَ إلاّ أَنْـتَ',
    phonetic: "Allâhumma innî a'ûdhu bika mina-l-kufr, wa-l-faqr, wa a'ûdhu bika min 'adhâbi-l-qabr, lâ ilâha illâ ant.",
    french: "Ô Allah, je cherche protection auprès de Toi contre la mécréance et la pauvreté, et je cherche protection auprès de Toi contre le châtiment de la tombe. Nulle divinité à part Toi.",
    target: 3,
  },
  {
    title: 'Pardon et bien-être',
    arabic: 'اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في الدُّنْـيا وَالآخِـرَة، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في ديني وَدُنْـيايَ وَأهْـلي وَمالـي، اللّهُـمَّ اسْتُـرْ عـوْراتي وَآمِـنْ رَوْعاتـي، اللّهُـمَّ احْفَظْـني مِن بَـينِ يَدَيَّ وَمِن خَلْفـي وَعَن يَمـيني وَعَن شِمـالي، وَمِن فَوْقـي، وَأَعـوذُ بِعَظَمَـتِكَ أَن أُغْـتالَ مِن تَحْتـي',
    phonetic: "Allâhumma innî as'aluka-l-'afwa wa-l-'âfiyata fî d-dunyâ wa-l-âkhira. Allâhumma innî as'aluka-l-'afwa wa-l-'âfiyata fî dînî wa dunyâya wa ahlî wa mâlî. Allâhumma-stur 'awrâtî wa âmin raw'âtî. Allâhumma-hfaznî min bayni yadayya wa min khalfî wa 'an yamînî wa 'an shimâlî wa min fawqî, wa a'ûdhu bi-'azamatika an ughtâla min tahtî.",
    french: "Ô Allah, je Te demande le pardon et la santé dans ce monde et dans l'au-delà. Ô Allah, je Te demande le pardon et la santé dans ma religion, ma vie, ma famille et mes biens. Ô Allah, cache mes défauts et apaise mes craintes. Ô Allah, protège-moi par devant, par derrière, à ma droite, à ma gauche et au-dessus de moi. Et je cherche protection par Ta grandeur contre tout mal venant de dessous.",
    target: 1,
  },
  {
    title: 'Secours du Vivant',
    arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أسْتَغِيثُ أصْلِحْ لِي شَأنِي كُلَّهُ وَلاَ تَكِلْنِي إلَى نَفْسِي طَـرْفَةَ عَيْنٍ',
    phonetic: "Yâ Hayyu yâ Qayyûm, bi-rahmatika astaghîth, aslih lî sha'nî kullahu wa lâ takilnî ilâ nafsî tarfata 'ayn.",
    french: "Ô Vivant, ô Subsistant, par Ta miséricorde j'implore secours. Améliore ma situation tout entière et ne me laisse pas à moi-même le temps d'un clin d'œil.",
    target: 3,
  },
  {
    title: 'Bien de ce jour',
    arabic: 'أَصْبَـحْـنا وَأَصْبَـحَ المُـلكُ لِلَّهِ رَبِّ العـالَمـين، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ خَـيْرَ هـذا الـيَوْم، فَـتْحَهُ، وَنَصْـرَهُ، وَنـورَهُ وَبَـرَكَتَـهُ، وَهُـداهُ، وَأَعـوذُ بِـكَ مِـنْ شَـرِّ ما فـيهِ وَشَـرِّ ما بَعْـدَه',
    phonetic: "Asbahnâ wa asbaha-l-mulku li-llâhi Rabbi-l-'âlamîn. Allâhumma innî as'aluka khayra hâdhâ-l-yawm, fat-hahu, wa nasrahu, wa nûrahu wa barakatahu, wa hudâhu, wa a'ûdhu bika min sharri mâ fîhi wa sharri mâ ba'dah.",
    french: "Nous voilà au matin et le royaume appartient à Allah, Seigneur des mondes. Ô Allah, je Te demande le bien de ce jour : son ouverture, son secours, sa lumière, sa bénédiction et sa guidée. Et je cherche refuge auprès de Toi contre le mal qu'il contient et le mal de ce qui vient après.",
    target: 1,
  },
  {
    title: 'Connaissance de l\'invisible',
    arabic: 'اللّهُـمَّ عالِـمَ الغَـيْبِ وَالشّـهادَةِ فاطِـرَ السّماواتِ وَالأرْضِ رَبَّ كـلِّ شَـيءٍ وَمَليـكَه، أَشْهَـدُ أَنْ لا إِلـهَ إِلاّ أَنْت، أَعـوذُ بِكَ مِن شَـرِّ نَفْسـي وَمِن شَـرِّ الشَّيْـطانِ وَشِرْكِهِ، وَأَنْ أَقْتَـرِفَ عَلـى نَفْسـي سوءاً أَوْ أَجُـرَّهُ إِلـى مُسْـلِم',
    phonetic: "Allâhumma 'Âlima-l-ghaybi wa sh-shahâdah, Fâtira s-samâwâti wa-l-ard, Rabba kulli shay'in wa malîkah, ash-hadu an lâ ilâha illâ ant, a'ûdhu bika min sharri nafsî wa min sharri sh-shaytâni wa shirkihi, wa an aqtarifa 'alâ nafsî sû'an aw ajurrahu ilâ muslim.",
    french: "Ô Allah, Connaisseur de l'invisible et du visible, Créateur des cieux et de la terre, Seigneur et Maître de toute chose, j'atteste qu'il n'y a de divinité que Toi. Je cherche Ta protection contre le mal de mon âme, contre le mal du diable et de son polythéisme, et contre le fait de commettre un mal contre moi-même ou de l'attirer sur un musulman.",
    target: 1,
  },
  {
    title: 'Protection par les paroles d\'Allah',
    arabic: 'أَعـوذُ بِكَلِمـاتِ اللّهِ التّـامّـاتِ مِنْ شَـرِّ ما خَلَـق',
    phonetic: "A'ûdhu bi-kalimâti-llâhi t-tâmmâti min sharri mâ khalaq.",
    french: "Je cherche protection dans les paroles parfaites d'Allah contre le mal de ce qu'Il a créé.",
    target: 3,
  },
  {
    title: 'Prière sur le Prophète ﷺ',
    arabic: 'اللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى نَبِيِّنَا مُحَمَّد',
    phonetic: "Allâhumma salli wa sallim wa bârik 'alâ nabiyyinâ Muhammad.",
    french: "Ô Allah, prie, accorde le salut et bénis notre Prophète Muhammad ﷺ.",
    target: 10,
  },
  {
    title: 'Refuge contre le shirk',
    arabic: 'اللَّهُمَّ إِنَّا نَعُوذُ بِكَ مِنْ أَنْ نُشْرِكَ بِكَ شَيْئًا نَعْلَمُهُ، وَنَسْتَغْفِرُكَ لِمَا لَا نَعْلَمُهُ',
    phonetic: "Allâhumma innâ na'ûdhu bika min an nushrika bika shay'an na'lamuh, wa nastaghfiruka li-mâ lâ na'lamuh.",
    french: "Ô Allah, nous cherchons refuge auprès de Toi contre le fait de T'associer quelque chose sciemment, et nous Te demandons pardon pour ce que nous ignorons.",
    target: 3,
  },
  {
    title: 'Refuge contre le souci',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ، وَقَهْرِ الرِّجَالِ',
    phonetic: "Allâhumma innî a'ûdhu bika mina-l-hammi wa-l-hazan, wa a'ûdhu bika mina-l-'ajzi wa-l-kasal, wa a'ûdhu bika mina-l-jubni wa-l-bukhl, wa a'ûdhu bika min ghalabati d-dayni wa qahri r-rijâl.",
    french: "Ô Allah, je cherche refuge auprès de Toi contre le souci et la tristesse, contre l'incapacité et la paresse, contre la lâcheté et l'avarice, et contre le fardeau des dettes et la domination des hommes.",
    target: 3,
  },
  {
    title: 'Istighfâr',
    arabic: 'أسْتَغْفِرُ اللهَ العَظِيمَ الَّذِي لاَ إلَهَ إلاَّ هُوَ، الحَيُّ القَيُّومُ، وَأتُوبُ إلَيهِ',
    phonetic: "Astaghfiru-llâha-l-'Azîma-lladhî lâ ilâha illâ huwa-l-Hayya-l-Qayyûma wa atûbu ilayh.",
    french: "Je demande pardon à Allah le Très Grand, celui en dehors duquel il n'y a nulle divinité, le Vivant, le Subsistant, et je me repens à Lui.",
    target: 3,
  },
  {
    title: 'Louange à Allah',
    arabic: 'يَا رَبِّ، لَكَ الْحَمْدُ كَمَا يَنْبَغِي لِجَلَالِ وَجْهِكَ، وَلِعَظِيمِ سُلْطَانِكَ',
    phonetic: "Yâ Rabbi, laka-l-hamdu kamâ yanbaghî li-jalâli wajhik, wa li-'azîmi sultânik.",
    french: "Ô Seigneur, à Toi la louange comme il se doit à la majesté de Ton visage et à la grandeur de Ton autorité.",
    target: 3,
  },
  {
    title: 'Science bénéfique',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا',
    phonetic: "Allâhumma innî as'aluka 'ilman nâfi'an, wa rizqan tayyiban, wa 'amalan mutaqabbalan.",
    french: "Ô Allah, je Te demande une science bénéfique, une subsistance licite et une œuvre acceptée.",
    target: 1,
  },
  {
    title: 'Confiance totale en Allah',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لا إِلَهَ إِلا أَنْتَ، عَلَيْكَ تَوَكَّلْتُ، وَأَنْتَ رَبُّ الْعَرْشِ الْعَظِيمِ، مَا شَاءَ اللَّهُ كَانَ، وَمَا لَمْ يَشَأْ لَمْ يَكُنْ، وَلا حَوْلَ وَلا قُوَّةَ إِلا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ، أَعْلَمُ أَنَّ اللَّهَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، وَأَنَّ اللَّهَ قَدْ أَحَاطَ بِكُلِّ شَيْءٍ عِلْمًا، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي، وَمِنْ شَرِّ كُلِّ دَابَّةٍ أَنْتَ آخِذٌ بِنَاصِيَتِهَا، إِنَّ رَبِّي عَلَى صِرَاطٍ مُسْتَقِيمٍ',
    phonetic: "Allâhumma anta Rabbî lâ ilâha illâ ant, 'alayka tawakkaltu wa anta Rabbu-l-'arshi-l-'azîm. Mâ shâ'a-llâhu kân, wa mâ lam yasha' lam yakun, wa lâ hawla wa lâ quwwata illâ bi-llâhi-l-'Aliyyi-l-'Azîm. A'lamu anna-llâha 'alâ kulli shay'in qadîr, wa anna-llâha qad ahâta bi-kulli shay'in 'ilman. Allâhumma innî a'ûdhu bika min sharri nafsî, wa min sharri kulli dâbbatin anta âkhidhun bi-nâsiyatihâ, inna Rabbî 'alâ sirâtin mustaqîm.",
    french: "Ô Allah, Tu es mon Seigneur, il n'y a de divinité que Toi. C'est en Toi que je place ma confiance et Tu es le Seigneur du Trône immense. Ce qu'Allah a voulu fut, et ce qu'Il n'a pas voulu n'a pas été. Il n'y a de force ni de puissance qu'en Allah, le Très Haut, le Très Grand. Je sais qu'Allah est Omnipotent et qu'Allah embrasse toute chose de Sa science. Ô Allah, je cherche refuge auprès de Toi contre le mal de mon âme et contre le mal de toute créature que Tu tiens par le front. Mon Seigneur est certes sur un droit chemin.",
    target: 1,
  },
  {
    title: 'Tahlîl',
    arabic: 'لَا إلَهَ إلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِير',
    phonetic: "Lâ ilâha illâ-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamdu wa huwa 'alâ kulli shay'in qadîr.",
    french: "Nulle divinité à part Allah, Seul sans associé. À Lui le royaume, à Lui la louange, et Il est Omnipotent.",
    target: 100,
  },
  {
    title: 'Tasbîh',
    arabic: 'سُبْحـانَ اللهِ وَبِحَمْـدِهِ',
    phonetic: "Subhâna-llâhi wa bi-hamdih.",
    french: "Gloire et louange à Allah.",
    target: 100,
  },
  {
    title: 'Istighfâr abondant',
    arabic: 'أسْتَغْفِرُ اللهَ وَأتُوبُ إلَيْهِ',
    phonetic: "Astaghfiru-llâha wa atûbu ilayh.",
    french: "Je demande pardon à Allah et je me repens à Lui.",
    target: 100,
  },
];
