import type { DhikrItem } from '@/components/dhikr/DhikrCounter';

export const MORNING_ADHKAR: DhikrItem[] = [
  {
    title: 'Âyat al-Kursî',
    source: 'Coran 2:255 — Al-Bukhârî n°5010',
    fadl: 'Celui qui la récite le matin est protégé par Allah jusqu\'au soir, et celui qui la récite le soir est protégé jusqu\'au matin. (Al-Hâkim, An-Nasâ\'î)',
    arabic: 'أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ\nاللّهُ لاَ إِلَـهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    phonetic: "A'ûdhu bi-llâhi mina sh-shaytâni r-rajîm. Allâhu lâ ilâha illâ huwa-l-Hayyu-l-Qayyûm, lâ ta'khudhuhu sinatun wa lâ nawm, lahu mâ fî s-samâwâti wa mâ fî-l-ard, man dhâ-lladhî yashfa'u 'indahu illâ bi-idhnih, ya'lamu mâ bayna aydîhim wa mâ khalfahum wa lâ yuhîtûna bi-shay'in min 'ilmihi illâ bi-mâ shâ', wasi'a kursiyyuhu s-samâwâti wa-l-ard, wa lâ ya'ûduhu hifzuhumâ wa huwa-l-'Aliyyu-l-'Azîm.",
    french: "Allah ! Point de divinité à part Lui, le Vivant, Celui qui subsiste par Lui-même. Ni somnolence ni sommeil ne Le saisissent. À Lui appartient tout ce qui est dans les cieux et sur la terre. Qui peut intercéder auprès de Lui sans Sa permission ? Il connaît leur passé et leur futur. Et de Sa science, ils n'embrassent que ce qu'Il veut. Son Trône déborde les cieux et la terre, dont la garde ne Lui coûte aucune peine. Et Il est le Très Haut, le Très Grand.",
    target: 1,
  },
  {
    title: 'Sourate Al-Ikhlâs',
    source: 'Coran 112:1-4 — Al-Bukhârî n°5017',
    fadl: 'Les trois Qul (Al-Ikhlâs, Al-Falaq, An-Nâs) récitées 3 fois matin et soir te suffisent contre toute chose. (Abû Dâwûd n°5082)',
    arabic: 'بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ هُوَ ٱللَّهُ أَحَدٌ ۝ ٱللَّهُ ٱلصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌ',
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul huwa-llâhu Ahad. Allâhu s-Samad. Lam yalid wa lam yûlad. Wa lam yakun lahu kufuwan ahad.",
    french: "Dis : «Il est Allah, Unique. Allah, Le Seul à être imploré pour ce que nous désirons. Il n'a jamais engendré, n'a pas été engendré non plus. Et nul n'est égal à Lui.»",
    target: 3,
  },
  {
    title: 'Sourate Al-Falaq',
    source: 'Coran 113:1-5 — Al-Bukhârî n°5017',
    arabic: 'بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul a'ûdhu bi-Rabbi-l-falaq. Min sharri mâ khalaq. Wa min sharri ghâsiqin idhâ waqab. Wa min sharri n-naffâthâti fî-l-'uqad. Wa min sharri hâsidin idhâ hasad.",
    french: "Dis : «Je cherche protection auprès du Seigneur de l'aube naissante, contre le mal des êtres qu'Il a créés, contre le mal de l'obscurité quand elle s'approfondit, contre le mal de celles qui soufflent sur les nœuds, et contre le mal de l'envieux quand il envie.»",
    target: 3,
  },
  {
    title: 'Sourate An-Nâs',
    source: 'Coran 114:1-6 — Al-Bukhârî n°5017',
    arabic: 'بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ ۝ مَلِكِ ٱلنَّاسِ ۝ إِلَٰهِ ٱلنَّاسِ ۝ مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ ۝ ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ ۝ مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ',
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul a'ûdhu bi-Rabbi n-nâs. Maliki n-nâs. Ilâhi n-nâs. Min sharri-l-waswâsi-l-khannâs. Alladhî yuwaswisu fî sudûri n-nâs. Mina-l-jinnati wa n-nâs.",
    french: "Dis : «Je cherche protection auprès du Seigneur des hommes, le Souverain des hommes, Dieu des hommes, contre le mal du mauvais conseiller, furtif, qui souffle le mal dans les poitrines des hommes, qu'il soit djinn ou être humain.»",
    target: 3,
  },
  {
    title: 'Dhikr du matin',
    source: 'Muslim n°2723',
    arabic: 'أَصْـبَحْنا وَأَصْـبَحَ المُـلْكُ لِلَّهِ وَالحَمدُ لِلَّهِ، لا إلهَ إلاّ اللّهُ وَحدَهُ لا شَريكَ لهُ، لهُ المُـلكُ ولهُ الحَمْـد، وهُوَ على كلّ شَيءٍ قدير، رَبِّ أسْـأَلُـكَ خَـيرَ ما في هـذا اليوم وَخَـيرَ ما بَعْـدَه، وَأَعـوذُ بِكَ مِنْ شَـرِّ ما في هـذا اليوم وَشَرِّ ما بَعْـدَه، رَبِّ أَعـوذُ بِكَ مِنَ الْكَسَـلِ وَسـوءِ الْكِـبَر، رَبِّ أَعـوذُ بِكَ مِنْ عَـذابٍ في النّـارِ وَعَـذابٍ في القَـبْر',
    phonetic: "Asbahnâ wa asbaha-l-mulku li-llâh, wa-l-hamdu li-llâh, lâ ilâha illâ-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamd, wa huwa 'alâ kulli shay'in qadîr. Rabbi as'aluka khayra mâ fî hâdhâ-l-yawm wa khayra mâ ba'dah, wa a'ûdhu bika min sharri mâ fî hâdhâ-l-yawm wa sharri mâ ba'dah. Rabbi a'ûdhu bika mina-l-kasali wa sû'i-l-kibar. Rabbi a'ûdhu bika min 'adhâbin fî n-nâri wa 'adhâbin fî-l-qabr.",
    french: "Nous voilà au matin et le royaume appartient à Allah. Louange à Allah. Nulle divinité à part Allah, Seul sans associé. À Lui le royaume et à Lui la louange. Il est Omnipotent. Seigneur, je Te demande le bien de ce jour et le bien de ce qui vient après. Je me réfugie auprès de Toi contre le mal de ce jour et le mal de ce qui vient après. Je me réfugie auprès de Toi contre la paresse et les maux de la vieillesse. Je me réfugie auprès de Toi contre le châtiment du Feu et le châtiment de la tombe.",
    target: 1,
  },
  {
    title: 'Sayyid al-Istighfâr',
    source: 'Al-Bukhârî n°6306',
    fadl: 'Celui qui le récite avec certitude le matin et meurt dans la journée sera parmi les gens du Paradis. De même s\'il le dit le soir. (Al-Bukhârî)',
    arabic: 'اللّهـمَّ أَنْتَ رَبِّـي لا إلهَ إلاّ أَنْتَ، خَلَقْتَنـي وَأَنا عَبْـدُك، وَأَنا عَلـى عَهْـدِكَ وَوَعْـدِكَ ما اسْتَـطَعْـت، أَعـوذُ بِكَ مِنْ شَـرِّ ما صَنَـعْت، أَبـوءُ لَـكَ بِنِعْـمَتِـكَ عَلَـيَّ وَأَبـوءُ بِذَنْـبي فَاغْفـِرْ لي فَإِنَّـهُ لا يَغْـفِرُ الذُّنـوبَ إِلاّ أَنْتَ',
    phonetic: "Allâhumma anta Rabbî, lâ ilâha illâ ant, khalaqtanî wa ana 'abduk, wa ana 'alâ 'ahdika wa wa'dika mâ-stata't, a'ûdhu bika min sharri mâ sana't, abû'u laka bi-ni'matika 'alayya wa abû'u bi-dhanbî, fa-ghfir lî fa-innahu lâ yaghfiru dh-dhunûba illâ ant.",
    french: "Ô Allah, Tu es mon Seigneur, il n'y a de divinité que Toi. Tu m'as créé et je suis Ton serviteur. Je suis fidèle à mon engagement et à ma promesse envers Toi autant que je le peux. Je cherche refuge auprès de Toi contre le mal que j'ai fait. Je reconnais devant Toi Tes bienfaits sur moi et je reconnais mes péchés. Pardonne-moi, car nul ne pardonne les péchés à part Toi.",
    target: 1,
  },
  {
    title: 'Agrément d\'Allah',
    source: 'Abû Dâwûd n°5072, At-Tirmidhî n°3389',
    fadl: 'Quiconque dit cela 3 fois le matin, Allah s\'engage à le satisfaire le Jour du Jugement. (At-Tirmidhî)',
    arabic: 'رَضيـتُ بِاللهِ رَبَّـاً وَبِالإسْلامِ ديـناً وَبِمُحَـمَّدٍ صلى الله عليه وسلم نَبِيّـاً',
    phonetic: "Radîtu bi-llâhi Rabban, wa bi-l-islâmi dînan, wa bi-Muhammadin (sallâ-llâhu 'alayhi wa sallam) nabiyyan.",
    french: "J'accepte Allah comme Seigneur, l'Islam comme religion et Muhammad ﷺ comme Prophète.",
    target: 3,
  },
  {
    title: 'Témoignage du matin',
    source: 'Abû Dâwûd n°5069',
    fadl: 'Quiconque le dit 4 fois le matin et le soir, Allah l\'affranchira du Feu. (Abû Dâwûd)',
    arabic: 'اللّهُـمَّ إِنِّـي أَصْبَـحْتُ أُشْـهِدُك، وَأُشْـهِدُ حَمَلَـةَ عَـرْشِـك، وَمَلَائِكَتَكَ، وَجَمـيعَ خَلْـقِك، أَنَّـكَ أَنْـتَ اللهُ لا إلهَ إلاّ أَنْـتَ وَحْـدَكَ لا شَريكَ لَـك، وَأَنَّ مُحَمّـداً عَبْـدُكَ وَرَسـولُـك',
    phonetic: "Allâhumma innî asbahtu ush-hiduk, wa ush-hidu hamalata 'arshik, wa malâ'ikatak, wa jamî'a khalqik, annaka anta-llâhu lâ ilâha illâ anta wahdaka lâ sharîka lak, wa anna Muhammadan 'abduka wa rasûluk.",
    french: "Ô Allah, je prends à témoin en ce matin, Toi, les porteurs de Ton Trône, Tes anges et toutes Tes créatures, que Tu es Allah, nulle divinité à part Toi, Seul sans associé, et que Muhammad est Ton serviteur et Ton messager.",
    target: 4,
  },
  {
    title: 'Reconnaissance des bienfaits',
    source: 'Abû Dâwûd n°5073',
    fadl: 'Quiconque dit cela le matin a accompli le remerciement de sa journée, et quiconque le dit le soir a accompli le remerciement de sa nuit. (Abû Dâwûd)',
    arabic: 'اللّهُـمَّ ما أَصْبَـحَ بي مِـنْ نِعْـمَةٍ أَو بِأَحَـدٍ مِـنْ خَلْـقِك، فَمِـنْكَ وَحْـدَكَ لا شريكَ لَـك، فَلَـكَ الْحَمْـدُ وَلَـكَ الشُّكْـر',
    phonetic: "Allâhumma mâ asbaha bî min ni'matin aw bi-ahadin min khalqik, fa-minka wahdaka lâ sharîka lak, fa-laka-l-hamdu wa laka sh-shukr.",
    french: "Ô Allah, tout bienfait dont je jouis en ce matin, ou dont jouit l'une de Tes créatures, provient de Toi Seul, sans associé. À Toi la louange et à Toi la reconnaissance.",
    target: 1,
  },
  {
    title: 'Tawakkul — La confiance',
    source: 'Coran 9:129 — Abû Dâwûd n°5081',
    fadl: 'Quiconque le dit 7 fois matin et soir, Allah lui suffit pour tout ce qui le préoccupe. (Abû Dâwûd, Ibn as-Sunnî)',
    arabic: 'حَسْبِـيَ اللّهُ لا إلهَ إلاّ هُوَ عَلَـيهِ تَوَكَّـلتُ وَهُوَ رَبُّ العَرْشِ العَظـيم',
    phonetic: "Hasbiya-llâhu lâ ilâha illâ huwa, 'alayhi tawakkaltu wa huwa Rabbu-l-'arshi-l-'azîm.",
    french: "Allah me suffit, il n'y a de divinité que Lui. C'est en Lui que je place ma confiance et Il est le Seigneur du Trône immense.",
    target: 7,
  },
  {
    title: 'La Protection',
    source: 'Abû Dâwûd n°5088, At-Tirmidhî n°3388',
    fadl: 'Quiconque le dit 3 fois le matin et le soir, rien ne lui nuira. (At-Tirmidhî)',
    arabic: 'بِسـمِ اللهِ الذي لا يَضُـرُّ مَعَ اسمِـهِ شَيءٌ في الأرْضِ وَلا في السّمـاءِ وَهـوَ السّمـيعُ العَلـيم',
    phonetic: "Bismi-llâhi-lladhî lâ yadurru ma'a-smihi shay'un fî-l-ardi wa lâ fî s-samâ'i wa huwa s-Samî'u-l-'Alîm.",
    french: "Au nom d'Allah, celui dont le nom protège de tout mal sur terre et dans les cieux. Il est l'Audient, l'Omniscient.",
    target: 3,
  },
  {
    title: 'Vivre et mourir pour Allah',
    source: 'At-Tirmidhî n°3391',
    arabic: 'اللّهُـمَّ بِكَ أَصْـبَحْنا وَبِكَ أَمْسَـينا، وَبِكَ نَحْـيا وَبِكَ نَمُـوتُ وَإِلَـيْكَ النُّـشُور',
    phonetic: "Allâhumma bika asbahnâ wa bika amsaynâ, wa bika nahyâ wa bika namûtu wa ilayka n-nushûr.",
    french: "Ô Allah, c'est par Toi que nous arrivons au matin et c'est par Toi que nous arrivons au soir. C'est par Toi que nous vivons et par Toi que nous mourons. Et c'est vers Toi la résurrection.",
    target: 1,
  },
  {
    title: 'Fitra de l\'Islam',
    source: 'Ahmad n°15360',
    arabic: 'أَصْبَـحْـنا عَلَى فِطْرَةِ الإسْلاَمِ، وَعَلَى كَلِمَةِ الإِخْلاَصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ، وَعَلَى مِلَّةِ أَبِينَا إبْرَاهِيمَ حَنِيفاً مُسْلِماً وَمَا كَانَ مِنَ المُشْرِكِينَ',
    phonetic: "Asbahnâ 'alâ fitrati-l-islâm, wa 'alâ kalimati-l-ikhlâs, wa 'alâ dîni nabiyyinâ Muhammadin (sallâ-llâhu 'alayhi wa sallam), wa 'alâ millati abînâ Ibrâhîma hanîfan musliman wa mâ kâna mina-l-mushrikîn.",
    french: "Nous sommes au matin sur la nature première de l'Islam, sur la parole de sincérité, sur la religion de notre Prophète Muhammad ﷺ, et sur la voie de notre père Abraham, monothéiste soumis, et il n'était point parmi les associateurs.",
    target: 1,
  },
  {
    title: 'Gloire à Allah',
    source: 'Muslim n°2726',
    fadl: 'Juwayriya bint al-Hârith rapporte que le Prophète ﷺ a dit que ces paroles pèsent plus que tout ce qu\'on pourrait dire depuis le matin. (Muslim)',
    arabic: 'سُبْحـانَ اللهِ وَبِحَمْـدِهِ عَدَدَ خَلْـقِهِ، وَرِضـا نَفْسِـهِ، وَزِنَـةَ عَـرْشِـهِ، وَمِـدادَ كَلِمـاتِـهِ',
    phonetic: "Subhâna-llâhi wa bi-hamdihi 'adada khalqih, wa ridâ nafsih, wa zinata 'arshih, wa midâda kalimâtih.",
    french: "Gloire et louange à Allah autant que le nombre de Ses créatures, autant qu'Il agrée, autant que pèse Son Trône, et autant que l'encre de Ses paroles.",
    target: 3,
  },
  {
    title: 'Santé du corps',
    source: 'Abû Dâwûd n°5090',
    arabic: 'اللّهُـمَّ عافِـني في بَدَنـي، اللّهُـمَّ عافِـني في سَمْـعي، اللّهُـمَّ عافِـني في بَصَـري، لا إلهَ إلاّ أَنْـتَ',
    phonetic: "Allâhumma 'âfinî fî badanî, Allâhumma 'âfinî fî sam'î, Allâhumma 'âfinî fî basarî, lâ ilâha illâ ant.",
    french: "Ô Allah, accorde-moi la santé dans mon corps. Ô Allah, accorde-moi la santé dans mon ouïe. Ô Allah, accorde-moi la santé dans ma vue. Nulle divinité à part Toi.",
    target: 3,
  },
  {
    title: 'Refuge contre la mécréance',
    source: 'Abû Dâwûd n°5090',
    arabic: 'اللّهُـمَّ إِنّـي أَعـوذُ بِكَ مِنَ الْكُـفر، وَالفَـقْر، وَأَعـوذُ بِكَ مِنْ عَذابِ القَـبْر، لا إلهَ إلاّ أَنْـتَ',
    phonetic: "Allâhumma innî a'ûdhu bika mina-l-kufr, wa-l-faqr, wa a'ûdhu bika min 'adhâbi-l-qabr, lâ ilâha illâ ant.",
    french: "Ô Allah, je cherche protection auprès de Toi contre la mécréance et la pauvreté, et je cherche protection auprès de Toi contre le châtiment de la tombe. Nulle divinité à part Toi.",
    target: 3,
  },
  {
    title: 'Pardon et bien-être',
    source: 'Abû Dâwûd n°5074, Ibn Mâjah n°3871',
    arabic: 'اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في الدُّنْـيا وَالآخِـرَة، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في ديني وَدُنْـيايَ وَأهْـلي وَمالـي، اللّهُـمَّ اسْتُـرْ عـوْراتي وَآمِـنْ رَوْعاتـي، اللّهُـمَّ احْفَظْـني مِن بَـينِ يَدَيَّ وَمِن خَلْفـي وَعَن يَمـيني وَعَن شِمـالي، وَمِن فَوْقـي، وَأَعـوذُ بِعَظَمَـتِكَ أَن أُغْـتالَ مِن تَحْتـي',
    phonetic: "Allâhumma innî as'aluka-l-'afwa wa-l-'âfiyata fî d-dunyâ wa-l-âkhira. Allâhumma innî as'aluka-l-'afwa wa-l-'âfiyata fî dînî wa dunyâya wa ahlî wa mâlî. Allâhumma-stur 'awrâtî wa âmin raw'âtî. Allâhumma-hfaznî min bayni yadayya wa min khalfî wa 'an yamînî wa 'an shimâlî wa min fawqî, wa a'ûdhu bi-'azamatika an ughtâla min tahtî.",
    french: "Ô Allah, je Te demande le pardon et la santé dans ce monde et dans l'au-delà. Ô Allah, je Te demande le pardon et la santé dans ma religion, ma vie, ma famille et mes biens. Ô Allah, cache mes défauts et apaise mes craintes. Ô Allah, protège-moi par devant, par derrière, à ma droite, à ma gauche et au-dessus de moi. Et je cherche protection par Ta grandeur contre tout mal venant de dessous.",
    target: 1,
  },
  {
    title: 'Secours du Vivant',
    source: 'Al-Hâkim, Sahîh al-Jâmi\' n°5820',
    arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أسْتَغِيثُ أصْلِحْ لِي شَأنِي كُلَّهُ وَلاَ تَكِلْنِي إلَى نَفْسِي طَـرْفَةَ عَيْنٍ',
    phonetic: "Yâ Hayyu yâ Qayyûm, bi-rahmatika astaghîth, aslih lî sha'nî kullahu wa lâ takilnî ilâ nafsî tarfata 'ayn.",
    french: "Ô Vivant, ô Subsistant, par Ta miséricorde j'implore secours. Améliore ma situation tout entière et ne me laisse pas à moi-même le temps d'un clin d'œil.",
    target: 3,
  },
  {
    title: 'Bien de ce jour',
    source: 'Abû Dâwûd n°5084',
    arabic: 'أَصْبَـحْـنا وَأَصْبَـحَ المُـلكُ لِلَّهِ رَبِّ العـالَمـين، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ خَـيْرَ هـذا الـيَوْم، فَـتْحَهُ، وَنَصْـرَهُ، وَنـورَهُ وَبَـرَكَتَـهُ، وَهُـداهُ، وَأَعـوذُ بِـكَ مِـنْ شَـرِّ ما فـيهِ وَشَـرِّ ما بَعْـدَه',
    phonetic: "Asbahnâ wa asbaha-l-mulku li-llâhi Rabbi-l-'âlamîn. Allâhumma innî as'aluka khayra hâdhâ-l-yawm, fat-hahu, wa nasrahu, wa nûrahu wa barakatahu, wa hudâhu, wa a'ûdhu bika min sharri mâ fîhi wa sharri mâ ba'dah.",
    french: "Nous voilà au matin et le royaume appartient à Allah, Seigneur des mondes. Ô Allah, je Te demande le bien de ce jour : son ouverture, son secours, sa lumière, sa bénédiction et sa guidée. Et je cherche refuge auprès de Toi contre le mal qu'il contient et le mal de ce qui vient après.",
    target: 1,
  },
  {
    title: 'Connaissance de l\'invisible',
    source: 'Abû Dâwûd n°5067, At-Tirmidhî n°3392',
    arabic: 'اللّهُـمَّ عالِـمَ الغَـيْبِ وَالشّـهادَةِ فاطِـرَ السّماواتِ وَالأرْضِ رَبَّ كـلِّ شَـيءٍ وَمَليـكَه، أَشْهَـدُ أَنْ لا إِلـهَ إِلاّ أَنْت، أَعـوذُ بِكَ مِن شَـرِّ نَفْسـي وَمِن شَـرِّ الشَّيْـطانِ وَشِرْكِهِ، وَأَنْ أَقْتَـرِفَ عَلـى نَفْسـي سوءاً أَوْ أَجُـرَّهُ إِلـى مُسْـلِم',
    phonetic: "Allâhumma 'Âlima-l-ghaybi wa sh-shahâdah, Fâtira s-samâwâti wa-l-ard, Rabba kulli shay'in wa malîkah, ash-hadu an lâ ilâha illâ ant, a'ûdhu bika min sharri nafsî wa min sharri sh-shaytâni wa shirkihi, wa an aqtarifa 'alâ nafsî sû'an aw ajurrahu ilâ muslim.",
    french: "Ô Allah, Connaisseur de l'invisible et du visible, Créateur des cieux et de la terre, Seigneur et Maître de toute chose, j'atteste qu'il n'y a de divinité que Toi. Je cherche Ta protection contre le mal de mon âme, contre le mal du diable et de son polythéisme, et contre le fait de commettre un mal contre moi-même ou de l'attirer sur un musulman.",
    target: 1,
  },
  {
    title: 'Protection par les paroles d\'Allah',
    source: 'Muslim n°2708',
    fadl: 'Quiconque dit cela 3 fois le soir ne sera pas piqué par un scorpion ni touché par un mal cette nuit-là. (Muslim)',
    arabic: 'أَعـوذُ بِكَلِمـاتِ اللّهِ التّـامّـاتِ مِنْ شَـرِّ ما خَلَـق',
    phonetic: "A'ûdhu bi-kalimâti-llâhi t-tâmmâti min sharri mâ khalaq.",
    french: "Je cherche protection dans les paroles parfaites d'Allah contre le mal de ce qu'Il a créé.",
    target: 3,
  },
  {
    title: 'Prière Ibrâhîmiya ﷺ',
    source: 'Al-Bukhârî n°3370, Muslim n°406',
    arabic: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ',
    phonetic: "Allâhumma salli 'alâ Muhammadin wa 'alâ âli Muhammad, kamâ sallayta 'alâ Ibrâhîma wa 'alâ âli Ibrâhîm, innaka Hamîdun Majîd. Allâhumma bârik 'alâ Muhammadin wa 'alâ âli Muhammad, kamâ bârakta 'alâ Ibrâhîma wa 'alâ âli Ibrâhîm, innaka Hamîdun Majîd.",
    french: "Ô Allah, prie sur Muhammad et sur la famille de Muhammad, comme Tu as prié sur Ibrâhîm et sur la famille d'Ibrâhîm, Tu es certes Digne de louange et de gloire. Ô Allah, bénis Muhammad et la famille de Muhammad, comme Tu as béni Ibrâhîm et la famille d'Ibrâhîm, Tu es certes Digne de louange et de gloire.",
    target: 10,
  },
  {
    title: 'Refuge contre le shirk',
    source: 'Ahmad n°19606',
    arabic: 'اللَّهُمَّ إِنَّا نَعُوذُ بِكَ مِنْ أَنْ نُشْرِكَ بِكَ شَيْئًا نَعْلَمُهُ، وَنَسْتَغْفِرُكَ لِمَا لَا نَعْلَمُهُ',
    phonetic: "Allâhumma innâ na'ûdhu bika min an nushrika bika shay'an na'lamuh, wa nastaghfiruka li-mâ lâ na'lamuh.",
    french: "Ô Allah, nous cherchons refuge auprès de Toi contre le fait de T'associer quelque chose sciemment, et nous Te demandons pardon pour ce que nous ignorons.",
    target: 3,
  },
  {
    title: 'Refuge contre le souci',
    source: 'Al-Bukhârî n°6369',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ، وَقَهْرِ الرِّجَالِ',
    phonetic: "Allâhumma innî a'ûdhu bika mina-l-hammi wa-l-hazan, wa a'ûdhu bika mina-l-'ajzi wa-l-kasal, wa a'ûdhu bika mina-l-jubni wa-l-bukhl, wa a'ûdhu bika min ghalabati d-dayni wa qahri r-rijâl.",
    french: "Ô Allah, je cherche refuge auprès de Toi contre le souci et la tristesse, contre l'incapacité et la paresse, contre la lâcheté et l'avarice, et contre le fardeau des dettes et la domination des hommes.",
    target: 3,
  },
  {
    title: 'Istighfâr',
    source: 'Abû Dâwûd n°1517, At-Tirmidhî n°3577',
    arabic: 'أسْتَغْفِرُ اللهَ العَظِيمَ الَّذِي لاَ إلَهَ إلاَّ هُوَ، الحَيُّ القَيُّومُ، وَأتُوبُ إلَيهِ',
    phonetic: "Astaghfiru-llâha-l-'Azîma-lladhî lâ ilâha illâ huwa-l-Hayya-l-Qayyûma wa atûbu ilayh.",
    french: "Je demande pardon à Allah le Très Grand, celui en dehors duquel il n'y a nulle divinité, le Vivant, le Subsistant, et je me repens à Lui.",
    target: 3,
  },
  {
    title: 'Louange à Allah',
    source: 'Ibn Mâjah n°3801',
    arabic: 'يَا رَبِّ، لَكَ الْحَمْدُ كَمَا يَنْبَغِي لِجَلَالِ وَجْهِكَ، وَلِعَظِيمِ سُلْطَانِكَ',
    phonetic: "Yâ Rabbi, laka-l-hamdu kamâ yanbaghî li-jalâli wajhik, wa li-'azîmi sultânik.",
    french: "Ô Seigneur, à Toi la louange comme il se doit à la majesté de Ton visage et à la grandeur de Ton autorité.",
    target: 3,
  },
  {
    title: 'Science bénéfique',
    source: 'Ibn Mâjah n°925',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا',
    phonetic: "Allâhumma innî as'aluka 'ilman nâfi'an, wa rizqan tayyiban, wa 'amalan mutaqabbalan.",
    french: "Ô Allah, je Te demande une science bénéfique, une subsistance licite et une œuvre acceptée.",
    target: 1,
  },
  {
    title: 'Confiance totale en Allah',
    source: 'Abû Dâwûd n°5067',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لا إِلَهَ إِلا أَنْتَ، عَلَيْكَ تَوَكَّلْتُ، وَأَنْتَ رَبُّ الْعَرْشِ الْعَظِيمِ، مَا شَاءَ اللَّهُ كَانَ، وَمَا لَمْ يَشَأْ لَمْ يَكُنْ، وَلا حَوْلَ وَلا قُوَّةَ إِلا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ، أَعْلَمُ أَنَّ اللَّهَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، وَأَنَّ اللَّهَ قَدْ أَحَاطَ بِكُلِّ شَيْءٍ عِلْمًا، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي، وَمِنْ شَرِّ كُلِّ دَابَّةٍ أَنْتَ آخِذٌ بِنَاصِيَتِهَا، إِنَّ رَبِّي عَلَى صِرَاطٍ مُسْتَقِيمٍ',
    phonetic: "Allâhumma anta Rabbî lâ ilâha illâ ant, 'alayka tawakkaltu wa anta Rabbu-l-'arshi-l-'azîm. Mâ shâ'a-llâhu kân, wa mâ lam yasha' lam yakun, wa lâ hawla wa lâ quwwata illâ bi-llâhi-l-'Aliyyi-l-'Azîm. A'lamu anna-llâha 'alâ kulli shay'in qadîr, wa anna-llâha qad ahâta bi-kulli shay'in 'ilman. Allâhumma innî a'ûdhu bika min sharri nafsî, wa min sharri kulli dâbbatin anta âkhidhun bi-nâsiyatihâ, inna Rabbî 'alâ sirâtin mustaqîm.",
    french: "Ô Allah, Tu es mon Seigneur, il n'y a de divinité que Toi. C'est en Toi que je place ma confiance et Tu es le Seigneur du Trône immense. Ce qu'Allah a voulu fut, et ce qu'Il n'a pas voulu n'a pas été. Il n'y a de force ni de puissance qu'en Allah, le Très Haut, le Très Grand. Je sais qu'Allah est Omnipotent et qu'Allah embrasse toute chose de Sa science. Ô Allah, je cherche refuge auprès de Toi contre le mal de mon âme et contre le mal de toute créature que Tu tiens par le front. Mon Seigneur est certes sur un droit chemin.",
    target: 1,
  },
  {
    title: 'Tahlîl',
    source: 'Al-Bukhârî n°6403, Muslim n°2693',
    arabic: 'لَا إلَهَ إلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِير',
    phonetic: "Lâ ilâha illâ-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamdu wa huwa 'alâ kulli shay'in qadîr.",
    french: "Nulle divinité à part Allah, Seul sans associé. À Lui le royaume, à Lui la louange, et Il est Omnipotent.",
    target: 100,
  },
  {
    title: 'Tasbîh',
    source: 'Al-Bukhârî n°6405, Muslim n°2692',
    arabic: 'سُبْحـانَ اللهِ وَبِحَمْـدِهِ',
    phonetic: "Subhâna-llâhi wa bi-hamdih.",
    french: "Gloire et louange à Allah.",
    target: 100,
  },
  {
    title: 'Istighfâr abondant',
    source: 'Al-Bukhârî n°6307, Muslim n°2702',
    arabic: 'أسْتَغْفِرُ اللهَ وَأتُوبُ إلَيْهِ',
    phonetic: "Astaghfiru-llâha wa atûbu ilayh.",
    french: "Je demande pardon à Allah et je me repens à Lui.",
    target: 100,
  },
];

export const EVENING_ADHKAR: DhikrItem[] = [
  {
    title: 'Âyat al-Kursî',
    source: 'Coran 2:255 — Al-Bukhârî n°5010',
    arabic: 'أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ\nاللّهُ لاَ إِلَـهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    phonetic: "A'ûdhu bi-llâhi mina sh-shaytâni r-rajîm. Allâhu lâ ilâha illâ huwa-l-Hayyu-l-Qayyûm, lâ ta'khudhuhu sinatun wa lâ nawm, lahu mâ fî s-samâwâti wa mâ fî-l-ard, man dhâ-lladhî yashfa'u 'indahu illâ bi-idhnih, ya'lamu mâ bayna aydîhim wa mâ khalfahum wa lâ yuhîtûna bi-shay'in min 'ilmihi illâ bi-mâ shâ', wasi'a kursiyyuhu s-samâwâti wa-l-ard, wa lâ ya'ûduhu hifzuhumâ wa huwa-l-'Aliyyu-l-'Azîm.",
    french: "Allah ! Point de divinité à part Lui, le Vivant, Celui qui subsiste par Lui-même. Ni somnolence ni sommeil ne Le saisissent. À Lui appartient tout ce qui est dans les cieux et sur la terre. Qui peut intercéder auprès de Lui sans Sa permission ? Il connaît leur passé et leur futur. Et de Sa science, ils n'embrassent que ce qu'Il veut. Son Trône déborde les cieux et la terre, dont la garde ne Lui coûte aucune peine. Et Il est le Très Haut, le Très Grand.",
    target: 1,
  },
  {
    title: 'Sourate Al-Ikhlâs',
    source: 'Coran 112:1-4 — Al-Bukhârî n°5017',
    arabic: 'بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ هُوَ ٱللَّهُ أَحَدٌ ۝ ٱللَّهُ ٱلصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌ',
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul huwa-llâhu Ahad. Allâhu s-Samad. Lam yalid wa lam yûlad. Wa lam yakun lahu kufuwan ahad.",
    french: "Dis : «Il est Allah, Unique. Allah, Le Seul à être imploré pour ce que nous désirons. Il n'a jamais engendré, n'a pas été engendré non plus. Et nul n'est égal à Lui.»",
    target: 3,
  },
  {
    title: 'Sourate Al-Falaq',
    source: 'Coran 113:1-5 — Al-Bukhârî n°5017',
    arabic: 'بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul a'ûdhu bi-Rabbi-l-falaq. Min sharri mâ khalaq. Wa min sharri ghâsiqin idhâ waqab. Wa min sharri n-naffâthâti fî-l-'uqad. Wa min sharri hâsidin idhâ hasad.",
    french: "Dis : «Je cherche protection auprès du Seigneur de l'aube naissante, contre le mal des êtres qu'Il a créés, contre le mal de l'obscurité quand elle s'approfondit, contre le mal de celles qui soufflent sur les nœuds, et contre le mal de l'envieux quand il envie.»",
    target: 3,
  },
  {
    title: 'Sourate An-Nâs',
    source: 'Coran 114:1-6 — Al-Bukhârî n°5017',
    arabic: 'بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ ۝ مَلِكِ ٱلنَّاسِ ۝ إِلَٰهِ ٱلنَّاسِ ۝ مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ ۝ ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ ۝ مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ',
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul a'ûdhu bi-Rabbi n-nâs. Maliki n-nâs. Ilâhi n-nâs. Min sharri-l-waswâsi-l-khannâs. Alladhî yuwaswisu fî sudûri n-nâs. Mina-l-jinnati wa n-nâs.",
    french: "Dis : «Je cherche protection auprès du Seigneur des hommes, le Souverain des hommes, Dieu des hommes, contre le mal du mauvais conseiller, furtif, qui souffle le mal dans les poitrines des hommes, qu'il soit djinn ou être humain.»",
    target: 3,
  },
  {
    title: 'Dhikr du soir',
    source: 'Muslim n°2723',
    arabic: 'أَمْسَيْنَا وَأَمْسَى المُلْكُ لِلَّهِ وَالحَمْدُ لِلَّهِ، لا إلهَ إلاّ اللّهُ وَحْدَهُ لا شَريكَ لهُ، لهُ المُلْكُ ولهُ الحَمْدُ، وهُوَ عَلى كلّ شَيءٍ قدير، رَبِّ أسْأَلُكَ خَيْرَ ما في هذِهِ اللَّيلَةِ وَخَيْرَ ما بَعْدَها، وَأَعوذُ بِكَ مِنْ شَرِّ ما في هذِهِ اللَّيلَةِ وَشَرِّ ما بَعْدَها، رَبِّ أَعوذُ بِكَ مِنَ الكَسَلِ وَسوءِ الكِبَرِ، رَبِّ أَعوذُ بِكَ مِنْ عَذابٍ في النّارِ وَعَذابٍ في القَبْرِ',
    phonetic: "Amsaynâ wa amsâ-l-mulku li-llâh, wa-l-hamdu li-llâh, lâ ilâha illâ-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamd, wa huwa 'alâ kulli shay'in qadîr. Rabbi as'aluka khayra mâ fî hâdhihi-l-laylah wa khayra mâ ba'dahâ, wa a'ûdhu bika min sharri mâ fî hâdhihi-l-laylah wa sharri mâ ba'dahâ. Rabbi a'ûdhu bika mina-l-kasali wa sû'i-l-kibar. Rabbi a'ûdhu bika min 'adhâbin fî n-nâri wa 'adhâbin fî-l-qabr.",
    french: "Nous voilà au soir et le royaume appartient à Allah. Louange à Allah. Nulle divinité à part Allah, Seul sans associé. À Lui le royaume et à Lui la louange. Il est Omnipotent. Seigneur, je Te demande le bien de cette nuit et le bien de ce qui vient après. Je me réfugie auprès de Toi contre le mal de cette nuit et le mal de ce qui vient après. Je me réfugie auprès de Toi contre la paresse et les maux de la vieillesse. Je me réfugie auprès de Toi contre le châtiment du Feu et le châtiment de la tombe.",
    target: 1,
  },
  {
    title: 'Sayyid al-Istighfâr',
    source: 'Al-Bukhârî n°6306',
    arabic: 'اللّهـمَّ أَنْتَ رَبِّـي لا إلهَ إلاّ أَنْتَ، خَلَقْتَنـي وَأَنا عَبْـدُك، وَأَنا عَلـى عَهْـدِكَ وَوَعْـدِكَ ما اسْتَـطَعْـت، أَعـوذُ بِكَ مِنْ شَـرِّ ما صَنَـعْت، أَبـوءُ لَـكَ بِنِعْـمَتِـكَ عَلَـيَّ وَأَبـوءُ بِذَنْـبي فَاغْفـِرْ لي فَإِنَّـهُ لا يَغْـفِرُ الذُّنـوبَ إِلاّ أَنْتَ',
    phonetic: "Allâhumma anta Rabbî, lâ ilâha illâ ant, khalaqtanî wa ana 'abduk, wa ana 'alâ 'ahdika wa wa'dika mâ-stata't, a'ûdhu bika min sharri mâ sana't, abû'u laka bi-ni'matika 'alayya wa abû'u bi-dhanbî, fa-ghfir lî fa-innahu lâ yaghfiru dh-dhunûba illâ ant.",
    french: "Ô Allah, Tu es mon Seigneur, il n'y a de divinité que Toi. Tu m'as créé et je suis Ton serviteur. Je suis fidèle à mon engagement et à ma promesse envers Toi autant que je le peux. Je cherche refuge auprès de Toi contre le mal que j'ai fait. Je reconnais devant Toi Tes bienfaits sur moi et je reconnais mes péchés. Pardonne-moi, car nul ne pardonne les péchés à part Toi.",
    target: 1,
  },
  {
    title: 'Agrément d\'Allah',
    source: 'Abû Dâwûd n°5072, At-Tirmidhî n°3389',
    arabic: 'رَضيـتُ بِاللهِ رَبَّـاً وَبِالإسْلامِ ديـناً وَبِمُحَـمَّدٍ صلى الله عليه وسلم نَبِيّـاً',
    phonetic: "Radîtu bi-llâhi Rabban, wa bi-l-islâmi dînan, wa bi-Muhammadin (sallâ-llâhu 'alayhi wa sallam) nabiyyan.",
    french: "J'accepte Allah comme Seigneur, l'Islam comme religion et Muhammad ﷺ comme Prophète.",
    target: 3,
  },
  {
    title: 'Témoignage du soir',
    source: 'Abû Dâwûd n°5069',
    arabic: 'اللّهُـمَّ إِنِّـي أَمْسَيْتُ أُشْـهِدُك، وَأُشْـهِدُ حَمَلَـةَ عَـرْشِـك، وَمَلَائِكَتَكَ، وَجَمـيعَ خَلْـقِك، أَنَّـكَ أَنْـتَ اللهُ لا إلهَ إلاّ أَنْـتَ وَحْـدَكَ لا شَريكَ لَـك، وَأَنَّ مُحَمّـداً عَبْـدُكَ وَرَسـولُـك',
    phonetic: "Allâhumma innî amsaytu ush-hiduk, wa ush-hidu hamalata 'arshik, wa malâ'ikatak, wa jamî'a khalqik, annaka anta-llâhu lâ ilâha illâ anta wahdaka lâ sharîka lak, wa anna Muhammadan 'abduka wa rasûluk.",
    french: "Ô Allah, je prends à témoin en ce soir, Toi, les porteurs de Ton Trône, Tes anges et toutes Tes créatures, que Tu es Allah, nulle divinité à part Toi, Seul sans associé, et que Muhammad est Ton serviteur et Ton messager.",
    target: 4,
  },
  {
    title: 'Reconnaissance des bienfaits',
    source: 'Abû Dâwûd n°5073',
    arabic: 'اللّهُـمَّ ما أَمْسَى بي مِـنْ نِعْـمَةٍ أَو بِأَحَـدٍ مِـنْ خَلْـقِك، فَمِـنْكَ وَحْـدَكَ لا شريكَ لَـك، فَلَـكَ الْحَمْـدُ وَلَـكَ الشُّكْـر',
    phonetic: "Allâhumma mâ amsâ bî min ni'matin aw bi-ahadin min khalqik, fa-minka wahdaka lâ sharîka lak, fa-laka-l-hamdu wa laka sh-shukr.",
    french: "Ô Allah, tout bienfait dont je jouis en ce soir, ou dont jouit l'une de Tes créatures, provient de Toi Seul, sans associé. À Toi la louange et à Toi la reconnaissance.",
    target: 1,
  },
  {
    title: 'Tawakkul — La confiance',
    source: 'Coran 9:129 — Abû Dâwûd n°5081',
    arabic: 'حَسْبِـيَ اللّهُ لا إلهَ إلاّ هُوَ عَلَـيهِ تَوَكَّـلتُ وَهُوَ رَبُّ العَرْشِ العَظـيم',
    phonetic: "Hasbiya-llâhu lâ ilâha illâ huwa, 'alayhi tawakkaltu wa huwa Rabbu-l-'arshi-l-'azîm.",
    french: "Allah me suffit, il n'y a de divinité que Lui. C'est en Lui que je place ma confiance et Il est le Seigneur du Trône immense.",
    target: 7,
  },
  {
    title: 'La Protection',
    source: 'Abû Dâwûd n°5088, At-Tirmidhî n°3388',
    arabic: 'بِسـمِ اللهِ الذي لا يَضُـرُّ مَعَ اسمِـهِ شَيءٌ في الأرْضِ وَلا في السّمـاءِ وَهـوَ السّمـيعُ العَلـيم',
    phonetic: "Bismi-llâhi-lladhî lâ yadurru ma'a-smihi shay'un fî-l-ardi wa lâ fî s-samâ'i wa huwa s-Samî'u-l-'Alîm.",
    french: "Au nom d'Allah, celui dont le nom protège de tout mal sur terre et dans les cieux. Il est l'Audient, l'Omniscient.",
    target: 3,
  },
  {
    title: 'Vivre et mourir pour Allah',
    source: 'At-Tirmidhî n°3391',
    arabic: 'اللّهُـمَّ بِكَ أَمْسَـيْنا وَبِكَ أَصْـبَحْنا، وَبِكَ نَحْـيا وَبِكَ نَمُـوتُ وَإِلَـيْكَ المَصِير',
    phonetic: "Allâhumma bika amsaynâ wa bika asbahnâ, wa bika nahyâ wa bika namûtu wa ilayka-l-masîr.",
    french: "Ô Allah, c'est par Toi que nous arrivons au soir et c'est par Toi que nous arrivons au matin. C'est par Toi que nous vivons et par Toi que nous mourons. Et c'est vers Toi le retour.",
    target: 1,
  },
  {
    title: 'Fitra de l\'Islam',
    source: 'Ahmad n°15360',
    arabic: 'أَمْسَـيْنا عَلَى فِطْرَةِ الإسْلاَمِ، وَعَلَى كَلِمَةِ الإِخْلاَصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ، وَعَلَى مِلَّةِ أَبِينَا إبْرَاهِيمَ حَنِيفاً مُسْلِماً وَمَا كَانَ مِنَ المُشْرِكِينَ',
    phonetic: "Amsaynâ 'alâ fitrati-l-islâm, wa 'alâ kalimati-l-ikhlâs, wa 'alâ dîni nabiyyinâ Muhammadin (sallâ-llâhu 'alayhi wa sallam), wa 'alâ millati abînâ Ibrâhîma hanîfan musliman wa mâ kâna mina-l-mushrikîn.",
    french: "Nous sommes au soir sur la nature première de l'Islam, sur la parole de sincérité, sur la religion de notre Prophète Muhammad ﷺ, et sur la voie de notre père Abraham, monothéiste soumis, et il n'était point parmi les associateurs.",
    target: 1,
  },
  {
    title: 'Gloire à Allah',
    source: 'Muslim n°2726',
    arabic: 'سُبْحـانَ اللهِ وَبِحَمْـدِهِ عَدَدَ خَلْـقِهِ، وَرِضـا نَفْسِـهِ، وَزِنَـةَ عَـرْشِـهِ، وَمِـدادَ كَلِمـاتِـهِ',
    phonetic: "Subhâna-llâhi wa bi-hamdihi 'adada khalqih, wa ridâ nafsih, wa zinata 'arshih, wa midâda kalimâtih.",
    french: "Gloire et louange à Allah autant que le nombre de Ses créatures, autant qu'Il agrée, autant que pèse Son Trône, et autant que l'encre de Ses paroles.",
    target: 3,
  },
  {
    title: 'Santé du corps',
    source: 'Abû Dâwûd n°5090',
    arabic: 'اللّهُـمَّ عافِـني في بَدَنـي، اللّهُـمَّ عافِـني في سَمْـعي، اللّهُـمَّ عافِـني في بَصَـري، لا إلهَ إلاّ أَنْـتَ',
    phonetic: "Allâhumma 'âfinî fî badanî, Allâhumma 'âfinî fî sam'î, Allâhumma 'âfinî fî basarî, lâ ilâha illâ ant.",
    french: "Ô Allah, accorde-moi la santé dans mon corps. Ô Allah, accorde-moi la santé dans mon ouïe. Ô Allah, accorde-moi la santé dans ma vue. Nulle divinité à part Toi.",
    target: 3,
  },
  {
    title: 'Refuge contre la mécréance',
    source: 'Abû Dâwûd n°5090',
    arabic: 'اللّهُـمَّ إِنّـي أَعـوذُ بِكَ مِنَ الْكُـفر، وَالفَـقْر، وَأَعـوذُ بِكَ مِنْ عَذابِ القَـبْر، لا إلهَ إلاّ أَنْـتَ',
    phonetic: "Allâhumma innî a'ûdhu bika mina-l-kufr, wa-l-faqr, wa a'ûdhu bika min 'adhâbi-l-qabr, lâ ilâha illâ ant.",
    french: "Ô Allah, je cherche protection auprès de Toi contre la mécréance et la pauvreté, et je cherche protection auprès de Toi contre le châtiment de la tombe. Nulle divinité à part Toi.",
    target: 3,
  },
  {
    title: 'Pardon et bien-être',
    source: 'Abû Dâwûd n°5074, Ibn Mâjah n°3871',
    arabic: 'اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في الدُّنْـيا وَالآخِـرَة، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في ديني وَدُنْـيايَ وَأهْـلي وَمالـي، اللّهُـمَّ اسْتُـرْ عـوْراتي وَآمِـنْ رَوْعاتـي، اللّهُـمَّ احْفَظْـني مِن بَـينِ يَدَيَّ وَمِن خَلْفـي وَعَن يَمـيني وَعَن شِمـالي، وَمِن فَوْقـي، وَأَعـوذُ بِعَظَمَـتِكَ أَن أُغْـتالَ مِن تَحْتـي',
    phonetic: "Allâhumma innî as'aluka-l-'afwa wa-l-'âfiyata fî d-dunyâ wa-l-âkhira. Allâhumma innî as'aluka-l-'afwa wa-l-'âfiyata fî dînî wa dunyâya wa ahlî wa mâlî. Allâhumma-stur 'awrâtî wa âmin raw'âtî. Allâhumma-hfaznî min bayni yadayya wa min khalfî wa 'an yamînî wa 'an shimâlî wa min fawqî, wa a'ûdhu bi-'azamatika an ughtâla min tahtî.",
    french: "Ô Allah, je Te demande le pardon et la santé dans ce monde et dans l'au-delà. Ô Allah, je Te demande le pardon et la santé dans ma religion, ma vie, ma famille et mes biens. Ô Allah, cache mes défauts et apaise mes craintes. Ô Allah, protège-moi par devant, par derrière, à ma droite, à ma gauche et au-dessus de moi. Et je cherche protection par Ta grandeur contre tout mal venant de dessous.",
    target: 1,
  },
  {
    title: 'Secours du Vivant',
    source: 'Al-Hâkim, Sahîh al-Jâmi\' n°5820',
    arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أسْتَغِيثُ أصْلِحْ لِي شَأنِي كُلَّهُ وَلاَ تَكِلْنِي إلَى نَفْسِي طَـرْفَةَ عَيْنٍ',
    phonetic: "Yâ Hayyu yâ Qayyûm, bi-rahmatika astaghîth, aslih lî sha'nî kullahu wa lâ takilnî ilâ nafsî tarfata 'ayn.",
    french: "Ô Vivant, ô Subsistant, par Ta miséricorde j'implore secours. Améliore ma situation tout entière et ne me laisse pas à moi-même le temps d'un clin d'œil.",
    target: 3,
  },
  {
    title: 'Bien de cette nuit',
    source: 'Abû Dâwûd n°5084',
    arabic: 'أَمْسَيْنا وَأَمْسَى المُلْكُ لِلَّهِ رَبِّ العالَمينَ، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ خَـيْرَ هـذِهِ اللَّيلَة، فَتْحَها، وَنَصْرَها، وَنورَها وَبَرَكَتَها، وَهُداها، وَأَعوذُ بِكَ مِنْ شَرِّ ما فيها وَشَرِّ ما بَعْدَها',
    phonetic: "Amsaynâ wa amsâ-l-mulku li-llâhi Rabbi-l-'âlamîn. Allâhumma innî as'aluka khayra hâdhihi-l-laylah, fat-hahâ, wa nasrahâ, wa nûrahâ wa barakatahâ, wa hudâhâ, wa a'ûdhu bika min sharri mâ fîhâ wa sharri mâ ba'dahâ.",
    french: "Nous voilà au soir et le royaume appartient à Allah, Seigneur des mondes. Ô Allah, je Te demande le bien de cette nuit : son ouverture, son secours, sa lumière, sa bénédiction et sa guidée. Et je cherche refuge auprès de Toi contre le mal qu'elle contient et le mal de ce qui vient après.",
    target: 1,
  },
  {
    title: 'Connaissance de l\'invisible',
    source: 'Abû Dâwûd n°5067, At-Tirmidhî n°3392',
    arabic: 'اللّهُـمَّ عالِـمَ الغَـيْبِ وَالشّـهادَةِ فاطِـرَ السّماواتِ وَالأرْضِ رَبَّ كـلِّ شَـيءٍ وَمَليـكَه، أَشْهَـدُ أَنْ لا إِلـهَ إِلاّ أَنْت، أَعـوذُ بِكَ مِن شَـرِّ نَفْسـي وَمِن شَـرِّ الشَّيْـطانِ وَشِرْكِهِ، وَأَنْ أَقْتَـرِفَ عَلـى نَفْسـي سوءاً أَوْ أَجُـرَّهُ إِلـى مُسْـلِم',
    phonetic: "Allâhumma 'Âlima-l-ghaybi wa sh-shahâdah, Fâtira s-samâwâti wa-l-ard, Rabba kulli shay'in wa malîkah, ash-hadu an lâ ilâha illâ ant, a'ûdhu bika min sharri nafsî wa min sharri sh-shaytâni wa shirkihi, wa an aqtarifa 'alâ nafsî sû'an aw ajurrahu ilâ muslim.",
    french: "Ô Allah, Connaisseur de l'invisible et du visible, Créateur des cieux et de la terre, Seigneur et Maître de toute chose, j'atteste qu'il n'y a de divinité que Toi. Je cherche Ta protection contre le mal de mon âme, contre le mal du diable et de son polythéisme, et contre le fait de commettre un mal contre moi-même ou de l'attirer sur un musulman.",
    target: 1,
  },
  {
    title: 'Protection par les paroles d\'Allah',
    source: 'Muslim n°2708',
    arabic: 'أَعـوذُ بِكَلِمـاتِ اللّهِ التّـامّـاتِ مِنْ شَـرِّ ما خَلَـق',
    phonetic: "A'ûdhu bi-kalimâti-llâhi t-tâmmâti min sharri mâ khalaq.",
    french: "Je cherche protection dans les paroles parfaites d'Allah contre le mal de ce qu'Il a créé.",
    target: 3,
  },
  {
    title: 'Prière Ibrâhîmiya ﷺ',
    source: 'Al-Bukhârî n°3370, Muslim n°406',
    arabic: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ',
    phonetic: "Allâhumma salli 'alâ Muhammadin wa 'alâ âli Muhammad, kamâ sallayta 'alâ Ibrâhîma wa 'alâ âli Ibrâhîm, innaka Hamîdun Majîd. Allâhumma bârik 'alâ Muhammadin wa 'alâ âli Muhammad, kamâ bârakta 'alâ Ibrâhîma wa 'alâ âli Ibrâhîm, innaka Hamîdun Majîd.",
    french: "Ô Allah, prie sur Muhammad et sur la famille de Muhammad, comme Tu as prié sur Ibrâhîm et sur la famille d'Ibrâhîm, Tu es certes Digne de louange et de gloire. Ô Allah, bénis Muhammad et la famille de Muhammad, comme Tu as béni Ibrâhîm et la famille d'Ibrâhîm, Tu es certes Digne de louange et de gloire.",
    target: 10,
  },
  {
    title: 'Refuge contre le shirk',
    source: 'Ahmad n°19606',
    arabic: 'اللَّهُمَّ إِنَّا نَعُوذُ بِكَ مِنْ أَنْ نُشْرِكَ بِكَ شَيْئًا نَعْلَمُهُ، وَنَسْتَغْفِرُكَ لِمَا لَا نَعْلَمُهُ',
    phonetic: "Allâhumma innâ na'ûdhu bika min an nushrika bika shay'an na'lamuh, wa nastaghfiruka li-mâ lâ na'lamuh.",
    french: "Ô Allah, nous cherchons refuge auprès de Toi contre le fait de T'associer quelque chose sciemment, et nous Te demandons pardon pour ce que nous ignorons.",
    target: 3,
  },
  {
    title: 'Refuge contre le souci',
    source: 'Al-Bukhârî n°6369',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ، وَقَهْرِ الرِّجَالِ',
    phonetic: "Allâhumma innî a'ûdhu bika mina-l-hammi wa-l-hazan, wa a'ûdhu bika mina-l-'ajzi wa-l-kasal, wa a'ûdhu bika mina-l-jubni wa-l-bukhl, wa a'ûdhu bika min ghalabati d-dayni wa qahri r-rijâl.",
    french: "Ô Allah, je cherche refuge auprès de Toi contre le souci et la tristesse, contre l'incapacité et la paresse, contre la lâcheté et l'avarice, et contre le fardeau des dettes et la domination des hommes.",
    target: 3,
  },
  {
    title: 'Istighfâr',
    source: 'Abû Dâwûd n°1517, At-Tirmidhî n°3577',
    arabic: 'أسْتَغْفِرُ اللهَ العَظِيمَ الَّذِي لاَ إلَهَ إلاَّ هُوَ، الحَيُّ القَيُّومُ، وَأتُوبُ إلَيهِ',
    phonetic: "Astaghfiru-llâha-l-'Azîma-lladhî lâ ilâha illâ huwa-l-Hayya-l-Qayyûma wa atûbu ilayh.",
    french: "Je demande pardon à Allah le Très Grand, celui en dehors duquel il n'y a nulle divinité, le Vivant, le Subsistant, et je me repens à Lui.",
    target: 3,
  },
  {
    title: 'Louange à Allah',
    source: 'Ibn Mâjah n°3801',
    arabic: 'يَا رَبِّ، لَكَ الْحَمْدُ كَمَا يَنْبَغِي لِجَلَالِ وَجْهِكَ، وَلِعَظِيمِ سُلْطَانِكَ',
    phonetic: "Yâ Rabbi, laka-l-hamdu kamâ yanbaghî li-jalâli wajhik, wa li-'azîmi sultânik.",
    french: "Ô Seigneur, à Toi la louange comme il se doit à la majesté de Ton visage et à la grandeur de Ton autorité.",
    target: 3,
  },
  {
    title: 'Confiance totale en Allah',
    source: 'Abû Dâwûd n°5067',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لا إِلَهَ إِلا أَنْتَ، عَلَيْكَ تَوَكَّلْتُ، وَأَنْتَ رَبُّ الْعَرْشِ الْعَظِيمِ، مَا شَاءَ اللَّهُ كَانَ، وَمَا لَمْ يَشَأْ لَمْ يَكُنْ، وَلا حَوْلَ وَلا قُوَّةَ إِلا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ، أَعْلَمُ أَنَّ اللَّهَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، وَأَنَّ اللَّهَ قَدْ أَحَاطَ بِكُلِّ شَيْءٍ عِلْمًا، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي، وَمِنْ شَرِّ كُلِّ دَابَّةٍ أَنْتَ آخِذٌ بِنَاصِيَتِهَا، إِنَّ رَبِّي عَلَى صِرَاطٍ مُسْتَقِيمٍ',
    phonetic: "Allâhumma anta Rabbî lâ ilâha illâ ant, 'alayka tawakkaltu wa anta Rabbu-l-'arshi-l-'azîm. Mâ shâ'a-llâhu kân, wa mâ lam yasha' lam yakun, wa lâ hawla wa lâ quwwata illâ bi-llâhi-l-'Aliyyi-l-'Azîm. A'lamu anna-llâha 'alâ kulli shay'in qadîr, wa anna-llâha qad ahâta bi-kulli shay'in 'ilman. Allâhumma innî a'ûdhu bika min sharri nafsî, wa min sharri kulli dâbbatin anta âkhidhun bi-nâsiyatihâ, inna Rabbî 'alâ sirâtin mustaqîm.",
    french: "Ô Allah, Tu es mon Seigneur, il n'y a de divinité que Toi. C'est en Toi que je place ma confiance et Tu es le Seigneur du Trône immense. Ce qu'Allah a voulu fut, et ce qu'Il n'a pas voulu n'a pas été. Il n'y a de force ni de puissance qu'en Allah, le Très Haut, le Très Grand. Je sais qu'Allah est Omnipotent et qu'Allah embrasse toute chose de Sa science. Ô Allah, je cherche refuge auprès de Toi contre le mal de mon âme et contre le mal de toute créature que Tu tiens par le front. Mon Seigneur est certes sur un droit chemin.",
    target: 1,
  },
  {
    title: 'Tahlîl',
    source: 'Al-Bukhârî n°6403, Muslim n°2693',
    arabic: 'لَا إلَهَ إلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِير',
    phonetic: "Lâ ilâha illâ-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamdu wa huwa 'alâ kulli shay'in qadîr.",
    french: "Nulle divinité à part Allah, Seul sans associé. À Lui le royaume, à Lui la louange, et Il est Omnipotent.",
    target: 100,
  },
  {
    title: 'Tasbîh',
    source: 'Al-Bukhârî n°6405, Muslim n°2692',
    arabic: 'سُبْحـانَ اللهِ وَبِحَمْـدِهِ',
    phonetic: "Subhâna-llâhi wa bi-hamdih.",
    french: "Gloire et louange à Allah.",
    target: 100,
  },
  {
    title: 'Istighfâr abondant',
    source: 'Al-Bukhârî n°6307, Muslim n°2702',
    arabic: 'أسْتَغْفِرُ اللهَ وَأتُوبُ إلَيْهِ',
    phonetic: "Astaghfiru-llâha wa atûbu ilayh.",
    french: "Je demande pardon à Allah et je me repens à Lui.",
    target: 100,
  },
];

// ═══════════════════════════════════════════════════════════
//  أذكار بعد الصلاة — Adhkâr après la prière
// ═══════════════════════════════════════════════════════════
export const POST_PRAYER_ADHKAR: DhikrItem[] = [
  {
    title: 'Istighfâr (3×)',
    arabic: 'أَسْتَغْفِرُ اللهَ',
    phonetic: "Astaghfiru-llâh.",
    french: "Je demande pardon à Allah.",
    target: 3,
  },
  {
    title: 'Allâhumma anta s-Salâm',
    arabic: 'اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ',
    phonetic: "Allâhumma anta s-Salâm, wa minka s-salâm, tabârakta yâ dhâ-l-Jalâli wa-l-Ikrâm.",
    french: "Ô Allah, Tu es la Paix et de Toi vient la paix. Béni sois-Tu, ô Toi qui es pourvu de Majesté et de Munificence.",
    target: 1,
  },
  {
    title: 'Lâ ilâha illa-llâh wahdahu',
    arabic: 'لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، اللَّهُمَّ لَا مَانِعَ لِمَا أَعْطَيْتَ وَلَا مُعْطِيَ لِمَا مَنَعْتَ وَلَا يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ',
    phonetic: "Lâ ilâha illa-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamd, wa huwa 'alâ kulli shay'in qadîr. Allâhumma lâ mâni'a limâ a'tayt, wa lâ mu'tiya limâ mana't, wa lâ yanfa'u dhâ-l-jaddi minka-l-jadd.",
    french: "Il n'y a de divinité qu'Allah, Seul sans associé. À Lui la royauté, à Lui la louange et Il est Omnipotent. Ô Allah, nul ne peut empêcher ce que Tu donnes, et nul ne peut donner ce que Tu empêches, et la fortune d'aucun fortuné ne lui sera utile contre Toi.",
    target: 1,
  },
  {
    title: 'Lâ ilâha illa-llâh (après la prière)',
    arabic: 'لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ، لَا إِلَهَ إِلَّا اللهُ وَلَا نَعْبُدُ إِلَّا إِيَّاهُ، لَهُ النِّعْمَةُ وَلَهُ الْفَضْلُ وَلَهُ الثَّنَاءُ الْحَسَنُ، لَا إِلَهَ إِلَّا اللهُ مُخْلِصِينَ لَهُ الدِّينَ وَلَوْ كَرِهَ الْكَافِرُونَ',
    phonetic: "Lâ ilâha illa-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamd, wa huwa 'alâ kulli shay'in qadîr. Lâ hawla wa lâ quwwata illâ bi-llâh. Lâ ilâha illa-llâh, wa lâ na'budu illâ iyyâh, lahu n-ni'matu wa lahu-l-fadl, wa lahu th-thanâ'u-l-hasan. Lâ ilâha illa-llâhu mukhlisîna lahu d-dîn wa law kariha-l-kâfirûn.",
    french: "Il n'y a de divinité qu'Allah, Seul sans associé. À Lui la royauté, la louange et Il est Omnipotent. Il n'y a de force ni de puissance qu'en Allah. Il n'y a de divinité qu'Allah et nous n'adorons que Lui seul. À Lui le bienfait, la grâce et la belle louange. Il n'y a de divinité qu'Allah, en Lui vouant un culte exclusif, en dépit de l'aversion des mécréants.",
    target: 1,
  },
  {
    title: 'Âyat al-Kursî',
    arabic: 'اللّهُ لاَ إِلَـهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    phonetic: "Allâhu lâ ilâha illâ huwa-l-Hayyu-l-Qayyûm, lâ ta'khudhuhu sinatun wa lâ nawm, lahu mâ fî s-samâwâti wa mâ fî-l-ard, man dhâ-lladhî yashfa'u 'indahu illâ bi-idhnih, ya'lamu mâ bayna aydîhim wa mâ khalfahum wa lâ yuhîtûna bi-shay'in min 'ilmihi illâ bi-mâ shâ', wasi'a kursiyyuhu s-samâwâti wa-l-ard, wa lâ ya'ûduhu hifzuhumâ wa huwa-l-'Aliyyu-l-'Azîm.",
    french: "Allah ! Point de divinité à part Lui, le Vivant, Celui qui subsiste par Lui-même. Ni somnolence ni sommeil ne Le saisissent. À Lui appartient tout ce qui est dans les cieux et sur la terre. Qui peut intercéder auprès de Lui sans Sa permission ? Il connaît leur passé et leur futur. Et de Sa science, ils n'embrassent que ce qu'Il veut. Son Trône déborde les cieux et la terre, dont la garde ne Lui coûte aucune peine. Et Il est le Très Haut, le Très Grand.",
    target: 1,
  },
  {
    title: 'Sourate Al-Ikhlâs',
    arabic: 'بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ هُوَ ٱللَّهُ أَحَدٌ ۝ ٱللَّهُ ٱلصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌ',
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul huwa-llâhu Ahad. Allâhu s-Samad. Lam yalid wa lam yûlad. Wa lam yakun lahu kufuwan ahad.",
    french: "Dis : «Il est Allah, Unique. Allah, Le Seul à être imploré pour ce que nous désirons. Il n'a jamais engendré, n'a pas été engendré non plus. Et nul n'est égal à Lui.»",
    target: 1,
  },
  {
    title: 'Sourate Al-Falaq',
    arabic: 'بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ',
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul a'ûdhu bi-Rabbi-l-falaq. Min sharri mâ khalaq. Wa min sharri ghâsiqin idhâ waqab. Wa min sharri n-naffâthâti fî-l-'uqad. Wa min sharri hâsidin idhâ hasad.",
    french: "Dis : «Je cherche protection auprès du Seigneur de l'aube naissante, contre le mal des êtres qu'Il a créés, contre le mal de l'obscurité quand elle s'approfondit, contre le mal de celles qui soufflent sur les nœuds, et contre le mal de l'envieux quand il envie.»",
    target: 1,
  },
  {
    title: 'Sourate An-Nâs',
    arabic: 'بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم\nقُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ ۝ مَلِكِ ٱلنَّاسِ ۝ إِلَٰهِ ٱلنَّاسِ ۝ مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ ۝ ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ ۝ مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ',
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul a'ûdhu bi-Rabbi n-nâs. Maliki n-nâs. Ilâhi n-nâs. Min sharri-l-waswâsi-l-khannâs. Alladhî yuwaswisu fî sudûri n-nâs. Mina-l-jinnati wa n-nâs.",
    french: "Dis : «Je cherche protection auprès du Seigneur des hommes, le Souverain des hommes, Dieu des hommes, contre le mal du mauvais conseiller, furtif, qui souffle le mal dans les poitrines des hommes, qu'il soit djinn ou être humain.»",
    target: 1,
  },
  {
    title: 'Subhâna-llâh (33×)',
    arabic: 'سُبْحَانَ اللهِ',
    phonetic: "Subhâna-llâh.",
    french: "Gloire à Allah.",
    target: 33,
  },
  {
    title: 'Al-hamdu li-llâh (33×)',
    arabic: 'الْحَمْدُ لِلَّهِ',
    phonetic: "Al-hamdu li-llâh.",
    french: "Louange à Allah.",
    target: 33,
  },
  {
    title: 'Allâhu Akbar (33×)',
    arabic: 'اللهُ أَكْبَرُ',
    phonetic: "Allâhu Akbar.",
    french: "Allah est le Plus Grand.",
    target: 33,
  },
  {
    title: 'Compléter le centième (1×)',
    arabic: 'لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    phonetic: "Lâ ilâha illa-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamd, wa huwa 'alâ kulli shay'in qadîr.",
    french: "Il n'y a de divinité qu'Allah, Seul sans associé. À Lui la royauté, à Lui la louange et Il est Omnipotent. (Pour compléter le centième après 33+33+33)",
    target: 1,
  },
  {
    title: 'Invocation pour la protection',
    arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ',
    phonetic: "Allâhumma a'innî 'alâ dhikrika wa shukrika wa husni 'ibâdatik.",
    french: "Ô Allah, aide-moi à T'évoquer, à Te remercier et à T'adorer de la meilleure manière.",
    target: 1,
  },
  {
    title: 'Protection contre le châtiment',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْجُبْنِ، وَأَعُوذُ بِكَ أَنْ أُرَدَّ إِلَى أَرْذَلِ الْعُمُرِ، وَأَعُوذُ بِكَ مِنْ فِتْنَةِ الدُّنْيَا، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ',
    phonetic: "Allâhumma innî a'ûdhu bika mina-l-jubn, wa a'ûdhu bika an uradda ilâ ardhali-l-'umur, wa a'ûdhu bika min fitnati d-dunyâ, wa a'ûdhu bika min 'adhâbi-l-qabr.",
    french: "Ô Allah, je cherche refuge auprès de Toi contre la lâcheté, contre le fait d'être ramené au plus vil âge, contre les tentations de ce bas monde et contre le châtiment de la tombe.",
    target: 1,
  },
];

export const ANYTIME_ADHKAR: DhikrItem[] = [
  {
    title: 'Tasbîh',
    arabic: 'سُبْحَانَ اللهِ',
    phonetic: "Subhâna-llâh",
    french: "Gloire à Allah.",
    target: 33,
  },
  {
    title: 'Tahmîd',
    arabic: 'الْحَمْدُ لِلَّهِ',
    phonetic: "Al-hamdu li-llâh",
    french: "Louange à Allah.",
    target: 33,
  },
  {
    title: 'Takbîr',
    arabic: 'اللهُ أَكْبَرُ',
    phonetic: "Allâhu Akbar",
    french: "Allah est le Plus Grand.",
    target: 33,
  },
  {
    title: 'Tahlîl',
    arabic: 'لَا إِلَهَ إِلَّا اللهُ',
    phonetic: "Lâ ilâha illa-llâh",
    french: "Il n'y a de divinité qu'Allah.",
    target: 100,
  },
  {
    title: "Salât 'alâ n-Nabî ﷺ",
    arabic: 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ',
    phonetic: "Allâhumma salli wa sallim 'alâ nabiyyinâ Muhammad",
    french: "Ô Allah, prie et accorde le salut sur notre prophète Muhammad ﷺ.",
    target: 10,
  },
  {
    title: 'Istighfâr',
    arabic: 'أَسْتَغْفِرُ اللهَ',
    phonetic: "Astaghfiru-llâh",
    french: "Je demande pardon à Allah.",
    target: 100,
  },
  {
    title: 'Hawqala',
    arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ',
    phonetic: "Lâ hawla wa lâ quwwata illâ bi-llâh",
    french: "Il n'y a de force ni de puissance qu'en Allah.",
    target: 10,
  },
  {
    title: 'Tasbîh complet',
    arabic: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ، سُبْحَانَ اللهِ الْعَظِيمِ',
    phonetic: "Subhâna-llâhi wa bi-hamdih, subhâna-llâhi-l-'Azîm",
    french: "Gloire à Allah et louange à Lui. Gloire à Allah le Très Grand.",
    target: 100,
  },
  {
    title: 'Dhikr léger sur la balance',
    arabic: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
    phonetic: "Subhâna-llâhi wa bi-hamdih",
    french: "Gloire et louange à Allah. Deux paroles légères sur la langue, lourdes sur la balance, aimées du Tout Miséricordieux.",
    target: 100,
  },
  {
    title: "Meilleur du'â",
    arabic: 'لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    phonetic: "Lâ ilâha illa-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamd, wa huwa 'alâ kulli shay'in qadîr",
    french: "Il n'y a de divinité qu'Allah, Seul sans associé. À Lui la royauté et la louange, et Il est Omnipotent.",
    target: 10,
  },
  {
    title: 'Sayyid al-Istighfâr',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    phonetic: "Allâhumma Anta Rabbî, lâ ilâha illâ Ant, khalaqtanî wa anâ 'abduk, wa anâ 'alâ 'ahdika wa wa'dika ma-stata't, a'ûdhu bika min sharri mâ sana't, abû'u laka bi-ni'matika 'alayya wa abû'u bi-dhanbî, fa-ghfir lî fa-innahu lâ yaghfiru dh-dhunûba illâ Ant.",
    french: "Ô Allah, Tu es mon Seigneur, il n'y a de divinité que Toi. Tu m'as créé et je suis Ton serviteur. Je suis fidèle à Ton pacte et à Ta promesse autant que je le peux. Je cherche refuge auprès de Toi contre le mal que j'ai commis. Je reconnais Tes bienfaits sur moi et je reconnais mon péché. Pardonne-moi, car nul ne pardonne les péchés si ce n'est Toi.",
    target: 1,
  },
  {
    title: 'Demande de protection',
    arabic: 'بِسْمِ اللهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    phonetic: "Bismi-llâhi-lladhî lâ yadurru ma'a-smihi shay'un fî-l-ardi wa lâ fî-s-samâ', wa huwa-s-Samî'u-l-'Alîm.",
    french: "Au nom d'Allah, Celui dont le nom protège de tout mal sur terre et dans le ciel, et Il est l'Audient, l'Omniscient.",
    target: 3,
  },
];

export const SUJUD_TILAWAH_ADHKAR: DhikrItem[] = [
  {
    title: "Du'â principal du Sujûd at-Tilâwah",
    arabic: 'سَجَدَ وَجْهِيَ لِلَّذِي خَلَقَهُ، وَشَقَّ سَمْعَهُ وَبَصَرَهُ، بِحَوْلِهِ وَقُوَّتِهِ، فَتَبَارَكَ اللهُ أَحْسَنُ الْخَالِقِينَ',
    phonetic: "Sajada wajhî li-lladhî khalaqahu, wa shaqqa sam'ahu wa basarahu, bi-hawlihi wa quwwatih, fa-tabâraka-llâhu ahsanu-l-khâliqîn.",
    french: "Mon visage s'est prosterné devant Celui qui l'a créé, qui a formé son ouïe et sa vue par Sa force et Sa puissance. Béni soit Allah, le Meilleur des créateurs.",
    target: 1,
  },
  {
    title: "Du'â du Sujûd — demande de récompense",
    arabic: 'اللَّهُمَّ اكْتُبْ لِي بِهَا عِنْدَكَ أَجْرًا، وَضَعْ عَنِّي بِهَا وِزْرًا، وَاجْعَلْهَا لِي عِنْدَكَ ذُخْرًا، وَتَقَبَّلْهَا مِنِّي كَمَا تَقَبَّلْتَهَا مِنْ عَبْدِكَ دَاوُدَ',
    phonetic: "Allâhumma-ktub lî bihâ 'indaka ajran, wa da' 'annî bihâ wizran, wa-j'alhâ lî 'indaka dhukhran, wa taqabbalhâ minnî kamâ taqabbaltahâ min 'abdika Dâwûd.",
    french: "Ô Allah, inscris-moi par cette prosternation une récompense auprès de Toi, efface-moi par elle un péché, fais-en pour moi une provision auprès de Toi, et accepte-la de moi comme Tu l'as acceptée de Ton serviteur Dâwûd.",
    target: 1,
  },
  {
    title: 'Tasbîh du Sujûd',
    arabic: 'سُبْحَانَ رَبِّيَ الْأَعْلَى',
    phonetic: "Subhâna Rabbiya-l-A'lâ",
    french: "Gloire à mon Seigneur le Très Haut.",
    target: 3,
  },
  {
    title: "Du'â dans le Sujûd",
    arabic: 'اللَّهُمَّ لَكَ سَجَدْتُ، وَبِكَ آمَنْتُ، وَلَكَ أَسْلَمْتُ، سَجَدَ وَجْهِيَ لِلَّذِي خَلَقَهُ وَصَوَّرَهُ وَشَقَّ سَمْعَهُ وَبَصَرَهُ، تَبَارَكَ اللهُ أَحْسَنُ الْخَالِقِينَ',
    phonetic: "Allâhumma laka sajadtu, wa bika âmantu, wa laka aslamtu, sajada wajhî li-lladhî khalaqahu wa sawwarahu wa shaqqa sam'ahu wa basarahu, tabâraka-llâhu ahsanu-l-khâliqîn.",
    french: "Ô Allah, c'est devant Toi que je me prosterne, c'est en Toi que je crois, c'est à Toi que je me soumets. Mon visage s'est prosterné devant Celui qui l'a créé, lui a donné sa forme, a ouvert son ouïe et sa vue. Béni soit Allah, le Meilleur des créateurs.",
    target: 1,
  },
  {
    title: "Du'â de glorification dans le Sujûd",
    arabic: 'سُبْحَانَكَ اللَّهُمَّ رَبَّنَا وَبِحَمْدِكَ، اللَّهُمَّ اغْفِرْ لِي',
    phonetic: "Subhânaka-llâhumma Rabbanâ wa bi-hamdik, Allâhumma-ghfir lî.",
    french: "Gloire à Toi, ô Allah notre Seigneur, et louange à Toi. Ô Allah, pardonne-moi.",
    target: 3,
  },
];

export const OMRA_DUAS: DhikrItem[] = [
  {
    title: "Talbiyah",
    readOnly: true,
    arabic: "لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ",
    phonetic: "Labbayka-llâhumma labbayk, labbayka lâ sharîka laka labbayk, inna-l-hamda wa n-ni'mata laka wa-l-mulk, lâ sharîka lak.",
    french: "Me voici, ô Allah, me voici ! Me voici, Tu n'as point d'associé, me voici ! La louange, la grâce et la royauté T'appartiennent. Tu n'as point d'associé.",
    target: 10,
  },
  {
    title: "Du'â du Tawâf (Pierre Noire)",
    readOnly: true,
    arabic: "بِسْمِ اللَّهِ وَاللَّهُ أَكْبَرُ، اللَّهُمَّ إِيمَانًا بِكَ وَتَصْدِيقًا بِكِتَابِكَ وَوَفَاءً بِعَهْدِكَ وَاتِّبَاعًا لِسُنَّةِ نَبِيِّكَ مُحَمَّدٍ ﷺ",
    phonetic: "Bismi-llâhi wa-llâhu Akbar. Allâhumma îmânan bika wa tasdîqan bi-kitâbika wa wafâ'an bi-'ahdika wa-ttibâ'an li-sunnati nabiyyika Muhammadin ﷺ.",
    french: "Au nom d'Allah, Allah est le plus Grand. Ô Allah, par foi en Toi, en confirmation de Ton Livre, en respect de Ton pacte, et en suivant la tradition de Ton Prophète Muhammad ﷺ.",
    target: 7,
  },
  {
    title: "Entre le coin yéménite et la Pierre Noire",
    readOnly: true,
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    phonetic: "Rabbanâ âtinâ fî d-dunyâ hasanatan wa fî-l-âkhirati hasanatan wa qinâ 'adhâba n-nâr.",
    french: "Seigneur ! Accorde-nous une belle part dans ce monde, et une belle part dans l'au-delà, et protège-nous du châtiment du Feu. (Al-Baqarah, 201)",
    target: 7,
  },
  {
    title: "Du'â du Sa'î (Safâ & Marwa)",
    readOnly: true,
    arabic: "إِنَّ الصَّفَا وَالْمَرْوَةَ مِن شَعَائِرِ اللَّهِ ۖ أَبْدَأُ بِمَا بَدَأَ اللَّهُ بِهِ",
    phonetic: "Inna s-Safâ wa-l-Marwata min sha'â'iri-llâh. Abda'u bi-mâ bada'a-llâhu bih.",
    french: "Safâ et Marwa sont parmi les rites d'Allah. Je commence par ce par quoi Allah a commencé. (Rapporté par Muslim)",
    target: 3,
  },
  {
    title: "Sur le mont Safâ / Marwa",
    readOnly: true,
    arabic: "اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    phonetic: "Allâhu Akbar (3 fois). Lâ ilâha illâ-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamdu wa huwa 'alâ kulli shay'in qadîr.",
    french: "Allah est le plus Grand (3 fois). Il n'y a de divinité qu'Allah, Seul sans associé. À Lui la royauté, à Lui la louange. Il est Omnipotent.",
    target: 3,
  },
  {
    title: "Du'â après la Omra",
    readOnly: true,
    arabic: "اللَّهُمَّ تَقَبَّلْ مِنِّي إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ، وَتُبْ عَلَيَّ إِنَّكَ أَنتَ التَّوَّابُ الرَّحِيمُ",
    phonetic: "Allâhumma taqabbal minnî innaka anta s-Samî'u-l-'Alîm. Wa tub 'alayya innaka anta t-Tawwâbu r-Rahîm.",
    french: "Ô Allah, accepte de moi, Tu es certes l'Audient, l'Omniscient. Et accepte mon repentir, Tu es certes le Repentant, le Miséricordieux.",
    target: 3,
  },
  {
    title: "Du'â en buvant Zamzam",
    readOnly: true,
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا وَاسِعًا، وَشِفَاءً مِنْ كُلِّ دَاءٍ",
    phonetic: "Allâhumma innî as'aluka 'ilman nâfi'an, wa rizqan wâsi'an, wa shifâ'an min kulli dâ'.",
    french: "Ô Allah, je Te demande une science bénéfique, une subsistance abondante et une guérison de toute maladie.",
    target: 1,
  },
  {
    title: "Du'â général pendant la Omra",
    readOnly: true,
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ",
    phonetic: "Allâhumma innî as'aluka-l-jannata wa a'ûdhu bika mina-n-nâr.",
    french: "Ô Allah, je Te demande le Paradis et je cherche refuge auprès de Toi contre le Feu.",
    target: 3,
  },
];

export const ISTIKHARAH_DUAS: DhikrItem[] = [
  {
    title: "Du'â al-Istikhârah",
    arabic: 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ، وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ، وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ، فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ، وَتَعْلَمُ وَلَا أَعْلَمُ، وَأَنْتَ عَلَّامُ الْغُيُوبِ، اللَّهُمَّ إِنْ كُنْتَ تَعْلَمُ أَنَّ هَذَا الْأَمْرَ خَيْرٌ لِي فِي دِينِي وَمَعَاشِي وَعَاقِبَةِ أَمْرِي فَاقْدُرْهُ لِي وَيَسِّرْهُ لِي ثُمَّ بَارِكْ لِي فِيهِ، وَإِنْ كُنْتَ تَعْلَمُ أَنَّ هَذَا الْأَمْرَ شَرٌّ لِي فِي دِينِي وَمَعَاشِي وَعَاقِبَةِ أَمْرِي فَاصْرِفْهُ عَنِّي وَاصْرِفْنِي عَنْهُ وَاقْدُرْ لِيَ الْخَيْرَ حَيْثُ كَانَ ثُمَّ أَرْضِنِي بِهِ',
    phonetic: "Allâhumma innî astakhîruka bi-'ilmik, wa astaqdiruka bi-qudratik, wa as'aluka min fadlika-l-'azîm. Fa-innaka taqdiru wa lâ aqdir, wa ta'lamu wa lâ a'lam, wa Anta 'allâmu-l-ghuyûb. Allâhumma in kunta ta'lamu anna hâdhâ-l-amra khayrun lî fî dînî wa ma'âshî wa 'âqibati amrî fa-qdurhu lî wa yassirhu lî thumma bârik lî fîh. Wa in kunta ta'lamu anna hâdhâ-l-amra sharrun lî fî dînî wa ma'âshî wa 'âqibati amrî fa-srifhu 'annî wa-srifnî 'anhu wa-qdur liya-l-khayra haythu kâna thumma ardinî bih.",
    french: "Ô Allah, je Te consulte par Ta science, je Te demande de m'accorder la capacité par Ta puissance, et je Te demande de Ta grâce immense. Car Tu es capable et je ne le suis pas, Tu sais et je ne sais pas, et Tu es le Grand Connaisseur de l'invisible. Ô Allah, si Tu sais que cette affaire est un bien pour moi dans ma religion, ma vie et mon devenir, alors décrète-la pour moi, facilite-la moi puis bénis-la moi. Et si Tu sais que cette affaire est un mal pour moi dans ma religion, ma vie et mon devenir, alors écarte-la de moi et écarte-moi d'elle, et décrète pour moi le bien où qu'il se trouve, puis rends-moi satisfait de ce choix.",
    target: 1,
  },
  {
    title: "Du'â de guidance",
    arabic: 'اللَّهُمَّ اهْدِنِي وَسَدِّدْنِي',
    phonetic: "Allâhumma-hdinî wa saddidnî.",
    french: "Ô Allah, guide-moi et dirige-moi sur le droit chemin.",
    target: 7,
  },
  {
    title: "Demande de facilité",
    arabic: 'اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا، وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا',
    phonetic: "Allâhumma lâ sahla illâ mâ ja'altahu sahlan, wa Anta taj'alu-l-hazna idhâ shi'ta sahla.",
    french: "Ô Allah, il n'y a de facilité que ce que Tu rends facile, et Tu rends l'affliction facile quand Tu le veux.",
    target: 3,
  },
  {
    title: "Remise à Allah",
    arabic: 'تَوَكَّلْتُ عَلَى اللهِ، لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ',
    phonetic: "Tawakkaltu 'alâ-llâh, lâ hawla wa lâ quwwata illâ bi-llâh.",
    french: "Je place ma confiance en Allah. Il n'y a de force ni de puissance qu'en Allah.",
    target: 7,
  },
  {
    title: "Salât 'alâ n-Nabî ﷺ (avant et après)",
    arabic: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ',
    phonetic: "Allâhumma salli 'alâ Muhammadin wa 'alâ âli Muhammadin kamâ sallayta 'alâ Ibrâhîma wa 'alâ âli Ibrâhîm, innaka Hamîdun Majîd. Allâhumma bârik 'alâ Muhammadin wa 'alâ âli Muhammadin kamâ bârakta 'alâ Ibrâhîma wa 'alâ âli Ibrâhîm, innaka Hamîdun Majîd.",
    french: "Ô Allah, prie sur Muhammad et sur la famille de Muhammad comme Tu as prié sur Ibrâhîm et la famille d'Ibrâhîm, Tu es certes Digne de louange et de gloire. Ô Allah, bénis Muhammad et la famille de Muhammad comme Tu as béni Ibrâhîm et la famille d'Ibrâhîm, Tu es certes Digne de louange et de gloire. (À réciter avant et après le du'â al-Istikharah)",
    target: 1,
  },
];

export const LOUANGES_ISTIGHFAR: DhikrItem[] = [
  {
    title: 'Subhân Allâh',
    arabic: 'سُبْحَانَ اللهِ',
    phonetic: "Subhân Allâh.",
    french: "Gloire à Allah. Le Prophète ﷺ a dit : « Deux paroles légères sur la langue, lourdes dans la balance, aimées du Tout Miséricordieux : Subhân Allâhi wa bi-Hamdih, Subhân Allâhi-l-'Azîm. »",
    target: 33,
  },
  {
    title: 'Al-Hamdulillâh',
    arabic: 'الْحَمْدُ لِلَّهِ',
    phonetic: "Al-Hamdulillâh.",
    french: "Louange à Allah. Le Prophète ﷺ a dit : « Al-Hamdulillâh remplit la balance. »",
    target: 33,
  },
  {
    title: 'Allâhu Akbar',
    arabic: 'اللهُ أَكْبَرُ',
    phonetic: "Allâhu Akbar.",
    french: "Allah est le Plus Grand.",
    target: 33,
  },
  {
    title: 'Lâ ilâha illa-llâh',
    arabic: 'لَا إِلَٰهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    phonetic: "Lâ ilâha illa-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamdu wa huwa 'alâ kulli shay'in Qadîr.",
    french: "Il n'y a de divinité digne d'adoration qu'Allah, Seul sans associé. À Lui la royauté, à Lui la louange et Il est Omnipotent. Quiconque dit cela 100 fois par jour a la récompense de l'affranchissement de 10 esclaves.",
    target: 10,
  },
  {
    title: 'Subhân Allâhi wa bi-Hamdih',
    arabic: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
    phonetic: "Subhân Allâhi wa bi-Hamdih.",
    french: "Gloire et louange à Allah. Le Prophète ﷺ a dit : « Quiconque dit cela 100 fois par jour, ses péchés seront effacés, fussent-ils comme l'écume de la mer. »",
    target: 33,
  },
  {
    title: "Subhân Allâhi-l-'Azîm wa bi-Hamdih",
    arabic: 'سُبْحَانَ اللهِ الْعَظِيمِ وَبِحَمْدِهِ',
    phonetic: "Subhân Allâhi-l-'Azîm wa bi-Hamdih.",
    french: "Gloire à Allah le Très Grand et louange à Lui. Deux paroles légères sur la langue, lourdes dans la balance, aimées du Tout Miséricordieux.",
    target: 33,
  },
  {
    title: 'Astaghfiru-llâh',
    arabic: 'أَسْتَغْفِرُ اللهَ',
    phonetic: "Astaghfiru-llâh.",
    french: "Je demande pardon à Allah. Le Prophète ﷺ demandait pardon à Allah plus de 70 fois par jour.",
    target: 33,
  },
  {
    title: 'Sayyid al-Istighfâr',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    phonetic: "Allâhumma Anta Rabbî, lâ ilâha illâ Ant, khalaqtanî wa ana 'abduk, wa ana 'alâ 'ahdika wa wa'dika mâ-stata't, a'ûdhu bika min sharri mâ sana't, abû'u laka bi-ni'matika 'alayya wa abû'u bi-dhanbî, fa-ghfir lî fa-innahu lâ yaghfiru dh-dhunûba illâ Ant.",
    french: "Ô Allah, Tu es mon Seigneur, il n'y a de divinité que Toi. Tu m'as créé et je suis Ton serviteur. Je suis fidèle à Ton pacte et à Ta promesse autant que je le peux. Je cherche refuge auprès de Toi contre le mal que j'ai commis. Je reconnais Tes bienfaits envers moi et je reconnais mes péchés. Pardonne-moi car nul ne pardonne les péchés hormis Toi. (Maître de l'Istighfâr — quiconque le dit avec conviction le matin et meurt dans la journée entre au Paradis.)",
    target: 3,
  },
  {
    title: 'Astaghfiru-llâh wa atûbu ilayh',
    arabic: 'أَسْتَغْفِرُ اللهَ وَأَتُوبُ إِلَيْهِ',
    phonetic: "Astaghfiru-llâha wa atûbu ilayh.",
    french: "Je demande pardon à Allah et je me repens à Lui. Le Prophète ﷺ a dit : « Par Allah, je demande pardon à Allah et je me repens à Lui plus de 70 fois par jour. »",
    target: 33,
  },
  {
    title: 'Lâ hawla wa lâ quwwata illâ bi-llâh',
    arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ',
    phonetic: "Lâ hawla wa lâ quwwata illâ bi-llâh.",
    french: "Il n'y a de force ni de puissance qu'en Allah. Le Prophète ﷺ a dit : « C'est un trésor parmi les trésors du Paradis. »",
    target: 10,
  },
];

/* ═══════════════════════════════════════════════════════════
   CHIFÂ & SÉRÉNITÉ — Ruqyah et invocations de guérison
   ═══════════════════════════════════════════════════════════ */

export const CHIFA_SERENITE: DhikrItem[] = [
  // ── Protection générale ──
  {
    title: "🛡️ Sourate Al-Fâtiha",
    source: "Coran 1:1-7 — Al-Bukhârî n°5007",
    arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمَٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Al-hamdu li-llâhi Rabbi-l-'âlamîn. Ar-Rahmâni r-Rahîm. Mâliki yawmi d-dîn. Iyyâka na'budu wa iyyâka nasta'în. Ihdinâ s-sirâta-l-mustaqîm. Sirâta-lladhîna an'amta 'alayhim, ghayri-l-maghdûbi 'alayhim wa lâ d-dâllîn.",
    french: "Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux. Louange à Allah, Seigneur de l'univers. Le Tout Miséricordieux, le Très Miséricordieux. Maître du Jour de la rétribution. C'est Toi seul que nous adorons, et c'est Toi seul dont nous implorons secours. Guide-nous dans le droit chemin. Le chemin de ceux que Tu as comblés de faveurs, non pas de ceux qui ont encouru Ta colère, ni des égarés.",
    target: 7,
  },
  {
    title: "🛡️ Âyat al-Kursî",
    source: "Coran 2:255 — Al-Bukhârî n°5010",
    arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ",
    phonetic: "Allâhu lâ ilâha illâ huwa-l-Hayyu-l-Qayyûm. Lâ ta'khudhuhu sinatun wa lâ nawm. Lahu mâ fî s-samâwâti wa mâ fî-l-ard. Man dhâ-lladhî yashfa'u 'indahu illâ bi-idhnih. Ya'lamu mâ bayna aydîhim wa mâ khalfahum. Wa lâ yuhîtûna bi-shay'in min 'ilmihi illâ bi-mâ shâ'. Wasi'a kursiyyuhu s-samâwâti wa-l-ard. Wa lâ ya'ûduhu hifzuhumâ. Wa huwa-l-'Aliyyu-l-'Azîm.",
    french: "Allah ! Point de divinité à part Lui, le Vivant, Celui qui subsiste par Lui-même. Ni somnolence ni sommeil ne Le saisissent. À Lui appartient tout ce qui est dans les cieux et sur la terre. Qui peut intercéder auprès de Lui sans Sa permission ? Il connaît leur passé et leur futur. Et de Sa science, ils n'embrassent que ce qu'Il veut. Son Trône déborde les cieux et la terre, dont la garde ne Lui coûte aucune peine. Et Il est le Très Haut, le Très Grand.",
    target: 3,
  },
  {
    title: "🛡️ Al-Baqarah v.285",
    source: "Coran 2:285 — Muslim n°810",
    arabic: "آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّن رُّسُلِهِ ۚ وَقَالُوا سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ",
    phonetic: "Âmana r-rasûlu bi-mâ unzila ilayhi min Rabbihî wa-l-mu'minûn. Kullun âmana bi-llâhi wa malâ'ikatihî wa kutubihî wa rusulih. Lâ nufarriqu bayna ahadin min rusulih. Wa qâlû sami'nâ wa ata'nâ, ghufrânaka Rabbanâ wa ilayka-l-masîr.",
    french: "Le Messager a cru en ce qu'on a fait descendre vers lui venant de son Seigneur, et aussi les croyants : tous ont cru en Allah, en Ses anges, en Ses livres et en Ses messagers ; « Nous ne faisons aucune distinction entre Ses messagers. » Et ils ont dit : « Nous avons entendu et obéi. Ton pardon, notre Seigneur. C'est vers Toi que sera le retour. »",
    target: 1,
  },
  {
    title: "🛡️ Al-Baqarah v.286",
    source: "Coran 2:286 — Muslim n°810",
    arabic: "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ۗ رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا ۚ رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ۖ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ۚ أَنتَ مَوْلَانَا فَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ",
    phonetic: "Lâ yukallifu-llâhu nafsan illâ wus'ahâ. Lahâ mâ kasabat wa 'alayhâ mâ-ktasabat. Rabbanâ lâ tu'âkhidhnâ in nasînâ aw akhta'nâ. Rabbanâ wa lâ tahmil 'alaynâ isran kamâ hamaltahu 'alâ-lladhîna min qablinâ. Rabbanâ wa lâ tuhammilnâ mâ lâ tâqata lanâ bih. Wa-'fu 'annâ wa-ghfir lanâ wa-rhamnâ. Anta mawlânâ fa-nsurnâ 'alâ-l-qawmi-l-kâfirîn.",
    french: "Allah n'impose à aucune âme une charge supérieure à sa capacité. Elle sera récompensée du bien qu'elle aura fait, et punie du mal qu'elle aura fait. « Seigneur, ne nous châtie pas s'il nous arrive d'oublier ou de commettre une erreur. Seigneur ! Ne nous charge pas d'un fardeau lourd comme Tu as chargé ceux qui vécurent avant nous. Seigneur ! Ne nous impose pas ce que nous ne pouvons supporter. Efface nos fautes, pardonne-nous et fais-nous miséricorde. Tu es notre Maître, accorde-nous la victoire sur les peuples mécréants. »",
    target: 1,
  },
  {
    title: "🛡️ Sourate Al-Ikhlâs",
    source: "Coran 112:1-4 — Al-Bukhârî n°5017",
    arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul huwa-llâhu Ahad. Allâhu s-Samad. Lam yalid wa lam yûlad. Wa lam yakun lahu kufuwan ahad.",
    french: "Au nom d'Allah. Dis : « Il est Allah, Unique. Allah, Le Seul à être imploré. Il n'a jamais engendré, n'a pas été engendré non plus. Et nul n'est égal à Lui. »",
    target: 3,
  },
  {
    title: "🛡️ Sourate Al-Falaq",
    source: "Coran 113:1-5 — Al-Bukhârî n°5017",
    arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul a'ûdhu bi-Rabbi-l-falaq. Min sharri mâ khalaq. Wa min sharri ghâsiqin idhâ waqab. Wa min sharri n-naffâthâti fî-l-'uqad. Wa min sharri hâsidin idhâ hasad.",
    french: "Au nom d'Allah. Dis : « Je cherche protection auprès du Seigneur de l'aube naissante, contre le mal des êtres qu'Il a créés, contre le mal de l'obscurité quand elle s'approfondit, contre le mal de celles qui soufflent sur les nœuds, et contre le mal de l'envieux quand il envie. »",
    target: 3,
  },
  {
    title: "🛡️ Sourate An-Nâs",
    source: "Coran 114:1-6 — Al-Bukhârî n°5017",
    arabic: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\nقُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ",
    phonetic: "Bismi-llâhi r-Rahmâni r-Rahîm. Qul a'ûdhu bi-Rabbi n-nâs. Maliki n-nâs. Ilâhi n-nâs. Min sharri-l-waswâsi-l-khannâs. Alladhî yuwaswisu fî sudûri n-nâs. Mina-l-jinnati wa n-nâs.",
    french: "Au nom d'Allah. Dis : « Je cherche protection auprès du Seigneur des hommes, le Souverain des hommes, Dieu des hommes, contre le mal du mauvais conseiller, furtif, qui souffle le mal dans les poitrines des hommes, qu'il soit djinn ou être humain. »",
    target: 3,
  },

  // ── Apaisement du cœur ──
  {
    title: "💚 Du'â d'Ayyûb (عليه السلام)",
    source: "Coran 21:83 — At-Tirmidhî n°3505",
    arabic: "رَبِّ إِنِّي مَسَّنِيَ الضُّرُّ وَأَنتَ أَرْحَمُ الرَّاحِمِينَ",
    phonetic: "Rabbi innî massaniya d-durru wa anta Arhamu r-Râhimîn.",
    french: "Seigneur ! Le mal m'a touché. Et Toi, Tu es le plus Miséricordieux des miséricordieux. (Al-Anbiyâ, 83) — Allah exauça Ayyûb (عليه السلام) et le guérit.",
    target: 7,
  },
  {
    title: "💚 Sérénité du cœur (Ar-Ra'd 28)",
    source: "Coran 13:28",
    arabic: "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ",
    phonetic: "Alâ bi-dhikri-llâhi tatma'innu-l-qulûb.",
    french: "N'est-ce point par le rappel d'Allah que se tranquillisent les cœurs ? (Ar-Ra'd, 28)",
    target: 7,
  },
  {
    title: "💚 Du'â de Yûnus (عليه السلام)",
    source: "Coran 21:87 — At-Tirmidhî n°3505",
    arabic: "لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
    phonetic: "Lâ ilâha illâ anta, subhânaka innî kuntu mina z-zâlimîn.",
    french: "Pas de divinité à part Toi ! Pureté à Toi ! J'ai été du nombre des injustes. (Al-Anbiyâ, 87) — Le Prophète ﷺ a dit : « Aucun musulman n'invoque par cette du'â sans qu'Allah ne l'exauce. »",
    target: 7,
  },
  {
    title: "💚 Contre l'angoisse et la tristesse",
    source: "Al-Bukhârî n°6369",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
    phonetic: "Allâhumma innî a'ûdhu bika mina-l-hammi wa-l-hazan, wa-l-'ajzi wa-l-kasal, wa-l-bukhli wa-l-jubn, wa dala'i d-dayni wa ghalabati r-rijâl.",
    french: "Ô Allah, je cherche refuge auprès de Toi contre les soucis et la tristesse, contre l'incapacité et la paresse, contre l'avarice et la lâcheté, contre le fardeau des dettes et la domination des hommes. (Rapporté par Al-Bukhârî)",
    target: 3,
  },
  {
    title: "💚 En cas de détresse",
    source: "Abû Dâwûd n°5090 — Sahîh",
    arabic: "اللَّهُمَّ رَحْمَتَكَ أَرْجُو فَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ وَأَصْلِحْ لِي شَأْنِي كُلَّهُ لَا إِلَهَ إِلَّا أَنتَ",
    phonetic: "Allâhumma rahmataka arjû fa-lâ takilnî ilâ nafsî tarfata 'ayn, wa aslih lî sha'nî kullah, lâ ilâha illâ ant.",
    french: "Ô Allah, c'est Ta miséricorde que j'espère. Ne me laisse pas à moi-même le temps d'un clin d'œil. Améliore ma situation tout entière. Il n'y a de divinité que Toi. (Rapporté par Abû Dâwûd)",
    target: 3,
  },
  {
    title: "💚 Confiance en Allah",
    source: "Coran 3:173 — Al-Bukhârî n°4563",
    arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
    phonetic: "Hasbunâ-llâhu wa ni'ma-l-wakîl.",
    french: "Allah nous suffit ; Il est notre meilleur Garant. (Âl 'Imrân, 173)",
    target: 7,
  },

  // ── Douleurs physiques ──
  {
    title: "🤲 Ruqyah du malade",
    source: "Al-Bukhârî n°5675, Muslim n°2191",
    arabic: "أَذْهِبِ الْبَأْسَ رَبَّ النَّاسِ، اشْفِ وَأَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا",
    phonetic: "Adh-hibi-l-ba's, Rabba n-nâs, ishfi wa anta sh-Shâfî, lâ shifâ'a illâ shifâ'uk, shifâ'an lâ yughâdiru saqaman.",
    french: "Ôte le mal, Seigneur des hommes ! Guéris, car Tu es le Guérisseur. Il n'y a de guérison que Ta guérison, une guérison qui ne laisse aucune maladie. (Rapporté par Al-Bukhârî et Muslim) — Invocation du Prophète ﷺ pour les malades.",
    target: 7,
  },
  {
    title: "🤲 En posant la main sur la douleur",
    source: "Muslim n°2202",
    arabic: "بِسْمِ اللَّهِ (ثلاثًا)\nأَعُوذُ بِاللَّهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ",
    phonetic: "Bismi-llâh (3 fois). A'ûdhu bi-llâhi wa qudratihî min sharri mâ ajidu wa uhâdhir.",
    french: "Au nom d'Allah (3 fois). Je cherche refuge auprès d'Allah et de Sa puissance contre le mal que je ressens et que je crains. (Rapporté par Muslim) — Poser la main sur l'endroit douloureux.",
    target: 7,
  },
  {
    title: "🤲 Demande de guérison (7x)",
    source: "Abû Dâwûd n°3106, At-Tirmidhî n°2083",
    arabic: "أَسْأَلُ اللَّهَ الْعَظِيمَ رَبَّ الْعَرْشِ الْعَظِيمِ أَنْ يَشْفِيَكَ",
    phonetic: "As'alu-llâha-l-'Azîm, Rabba-l-'Arshi-l-'Azîm, an yashfiyak.",
    french: "Je demande à Allah le Très Grand, le Seigneur du Trône immense, de te guérir. (À réciter 7 fois) — Le Prophète ﷺ a dit : « Quiconque dit cela 7 fois, Allah le guérit. » (Rapporté par Abû Dâwûd et At-Tirmidhî)",
    target: 7,
  },
  {
    title: "🤲 Protection par le souffle (Mu'awwidhat)",
    source: "Al-Bukhârî n°5016",
    arabic: "كَانَ النَّبِيُّ ﷺ إِذَا اشْتَكَى يَقْرَأُ عَلَى نَفْسِهِ بِالمُعَوِّذَاتِ وَيَنْفُثُ",
    phonetic: "Kâna n-Nabiyyu ﷺ idhâ-shtakâ yaqra'u 'alâ nafsihî bi-l-mu'awwidhât wa yanfuth.",
    french: "Le Prophète ﷺ, lorsqu'il souffrait, récitait les sourates protectrices (Al-Ikhlâs, Al-Falaq, An-Nâs) et soufflait dans ses mains puis les passait sur son corps. (Rapporté par Al-Bukhârî) — Fais de même 3 fois.",
    target: 3,
  },
  {
    title: "🤲 Contre le mauvais œil",
    source: "Al-Bukhârî n°3371",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ",
    phonetic: "A'ûdhu bi-kalimâti-llâhi t-tâmmati min kulli shaytânin wa hâmmatin wa min kulli 'aynin lâmmah.",
    french: "Je cherche protection par les paroles parfaites d'Allah contre tout démon, tout animal venimeux et contre tout mauvais œil. (Rapporté par Al-Bukhârî) — Le Prophète ﷺ récitait cela pour protéger Al-Hasan et Al-Husayn.",
    target: 3,
  },
  {
    title: "🤲 Guérison par le Coran (Al-Isrâ' 82)",
    source: "Coran 17:82",
    arabic: "وَنُنَزِّلُ مِنَ الْقُرْآنِ مَا هُوَ شِفَاءٌ وَرَحْمَةٌ لِّلْمُؤْمِنِينَ",
    phonetic: "Wa nunazzilu mina-l-Qur'âni mâ huwa shifâ'un wa rahmatun li-l-mu'minîn.",
    french: "Nous faisons descendre du Coran ce qui est une guérison et une miséricorde pour les croyants. (Al-Isrâ', 82) — Le Coran est une guérison par la permission d'Allah.",
    target: 3,
  },
  {
    title: "🤲 Invocation pour le malade qu'on visite",
    source: "Al-Bukhârî n°3616",
    arabic: "لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهُ",
    phonetic: "Lâ ba's, tahûrun in shâ'a-llâh.",
    french: "Pas de mal, c'est une purification si Allah le veut. (Rapporté par Al-Bukhârî) — Parole du Prophète ﷺ lorsqu'il visitait un malade.",
    target: 3,
  },
  {
    title: "🤲 Sourate Ash-Shu'arâ' v.80",
    source: "Coran 26:80",
    arabic: "وَإِذَا مَرِضْتُ فَهُوَ يَشْفِينِ",
    phonetic: "Wa idhâ maridtu fa-huwa yashfîn.",
    french: "Et quand je suis malade, c'est Lui qui me guérit. (Ash-Shu'arâ', 80) — Parole d'Ibrâhîm (عليه السلام) rapportée dans le Coran.",
    target: 7,
  },
];

/* ═══════════════════════════════════════════════════════════
   DUAS HAJJ — Invocations du pèlerinage
   ═══════════════════════════════════════════════════════════ */

export const HAJJ_DUAS: DhikrItem[] = [
  {
    title: "Talbiya",
    readOnly: true,
    arabic: "لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ",
    phonetic: "Labbayka-llâhumma labbayk, labbayka lâ sharîka laka labbayk, inna-l-hamda wa n-ni'mata laka wa-l-mulk, lâ sharîka lak.",
    french: "Me voici, ô Allah, me voici ! Me voici, Tu n'as point d'associé, me voici ! La louange, la grâce et la royauté T'appartiennent. Tu n'as point d'associé.",
    target: 10,
  },
  {
    title: "Du'â du Tawâf (Pierre Noire)",
    readOnly: true,
    arabic: "بِسْمِ اللَّهِ وَاللَّهُ أَكْبَرُ، اللَّهُمَّ إِيمَانًا بِكَ وَتَصْدِيقًا بِكِتَابِكَ وَوَفَاءً بِعَهْدِكَ وَاتِّبَاعًا لِسُنَّةِ نَبِيِّكَ مُحَمَّدٍ ﷺ",
    phonetic: "Bismi-llâhi wa-llâhu Akbar. Allâhumma îmânan bika wa tasdîqan bi-kitâbika wa wafâ'an bi-'ahdika wa-ttibâ'an li-sunnati nabiyyika Muhammadin ﷺ.",
    french: "Au nom d'Allah, Allah est le plus Grand. Ô Allah, par foi en Toi, en confirmation de Ton Livre, en respect de Ton pacte, et en suivant la tradition de Ton Prophète Muhammad ﷺ.",
    target: 7,
  },
  {
    title: "Entre les deux coins (Tawâf)",
    readOnly: true,
    arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    phonetic: "Rabbanâ âtinâ fî d-dunyâ hasanatan wa fî-l-âkhirati hasanatan wa qinâ 'adhâba n-nâr.",
    french: "Seigneur ! Accorde-nous une belle part dans ce monde, et une belle part dans l'au-delà, et protège-nous du châtiment du Feu. (Al-Baqarah, 201)",
    target: 7,
  },
  {
    title: "Du'â du Sa'î (Safâ & Marwa)",
    readOnly: true,
    arabic: "إِنَّ الصَّفَا وَالْمَرْوَةَ مِن شَعَائِرِ اللَّهِ ۖ أَبْدَأُ بِمَا بَدَأَ اللَّهُ بِهِ",
    phonetic: "Inna s-Safâ wa-l-Marwata min sha'â'iri-llâh. Abda'u bi-mâ bada'a-llâhu bih.",
    french: "Safâ et Marwa sont parmi les rites d'Allah. Je commence par ce par quoi Allah a commencé. (Rapporté par Muslim)",
    target: 3,
  },
  {
    title: "Du'â sur le mont Safâ",
    readOnly: true,
    arabic: "اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    phonetic: "Allâhu Akbar, Allâhu Akbar, Allâhu Akbar. Lâ ilâha illâ-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamdu wa huwa 'alâ kulli shay'in qadîr.",
    french: "Allah est le plus Grand (3 fois). Il n'y a de divinité qu'Allah, Seul sans associé. À Lui la royauté, à Lui la louange. Il est Omnipotent.",
    target: 3,
  },
  {
    title: "Du'â du jour de 'Arafât",
    readOnly: true,
    arabic: "خَيْرُ الدُّعَاءِ دُعَاءُ يَوْمِ عَرَفَةَ، وَخَيْرُ مَا قُلْتُ أَنَا وَالنَّبِيُّونَ مِنْ قَبْلِي: لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    phonetic: "Khayru d-du'â'i du'â'u yawmi 'Arafah, wa khayru mâ qultu anâ wa n-nabiyyûna min qablî: Lâ ilâha illâ-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamdu wa huwa 'alâ kulli shay'in qadîr.",
    french: "La meilleure invocation est celle du jour de 'Arafât, et la meilleure parole que j'ai dite, moi et les Prophètes (عليهم السلام) avant moi : Il n'y a de divinité qu'Allah, Seul sans associé. À Lui la royauté, à Lui la louange. Il est Omnipotent. (Rapporté par At-Tirmidhî)",
    target: 10,
  },
  {
    title: "Du'â de Muzdalifah",
    readOnly: true,
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ بِأَنَّكَ أَنتَ اللَّهُ لَا إِلَٰهَ إِلَّا أَنتَ الْأَحَدُ الصَّمَدُ الَّذِي لَمْ يَلِدْ وَلَمْ يُولَدْ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
    phonetic: "Allâhumma innî as'aluka bi-annaka anta-llâhu lâ ilâha illâ anta-l-Ahadu s-Samadu-lladhî lam yalid wa lam yûlad wa lam yakun lahu kufuwan ahad.",
    french: "Ô Allah, je T'implore car Tu es Allah, il n'y a de divinité que Toi, l'Unique, le Seul imploré, qui n'a jamais engendré et n'a pas été engendré, et nul n'est égal à Lui.",
    target: 3,
  },
  {
    title: "Lapidation (Jamarat)",
    readOnly: true,
    arabic: "اللَّهُ أَكْبَرُ",
    phonetic: "Allâhu Akbar.",
    french: "Allah est le plus Grand. (À chaque lancer de caillou lors de la lapidation des stèles à Minâ.)",
    target: 7,
  },
  {
    title: "Du'â après le sacrifice",
    readOnly: true,
    arabic: "بِسْمِ اللَّهِ وَاللَّهُ أَكْبَرُ، اللَّهُمَّ مِنْكَ وَلَكَ، اللَّهُمَّ تَقَبَّلْ مِنِّي",
    phonetic: "Bismi-llâhi wa-llâhu Akbar. Allâhumma minka wa lak. Allâhumma taqabbal minnî.",
    french: "Au nom d'Allah, Allah est le plus Grand. Ô Allah, cela vient de Toi et c'est pour Toi. Ô Allah, accepte de moi.",
    target: 1,
  },
  {
    title: "Du'â en buvant Zamzam",
    readOnly: true,
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا وَاسِعًا وَشِفَاءً مِنْ كُلِّ دَاءٍ",
    phonetic: "Allâhumma innî as'aluka 'ilman nâfi'an wa rizqan wâsi'an wa shifâ'an min kulli dâ'.",
    french: "Ô Allah, je Te demande une science bénéfique, une subsistance abondante et la guérison de toute maladie. (À réciter en buvant l'eau de Zamzam.)",
    target: 3,
  },
  {
    title: "Takbîr des jours de Tachrîq",
    readOnly: true,
    arabic: "اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ، لَا إِلَهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ وَلِلَّهِ الْحَمْدُ",
    phonetic: "Allâhu Akbar, Allâhu Akbar, lâ ilâha illâ-llâh, wa-llâhu Akbar, Allâhu Akbar, wa li-llâhi-l-hamd.",
    french: "Allah est le plus Grand, Allah est le plus Grand. Nulle divinité à part Allah. Allah est le plus Grand, Allah est le plus Grand. Et à Allah la louange. (Du 9 au 13 Dhû-l-Hijja)",
    target: 10,
  },
  {
    title: "Du'â du retour de voyage",
    readOnly: true,
    arabic: "اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ",
    phonetic: "Allâhu Akbar (3 fois). Lâ ilâha illâ-llâhu wahdahu lâ sharîka lah, lahu-l-mulku wa lahu-l-hamdu wa huwa 'alâ kulli shay'in qadîr. Âyibûna tâ'ibûna 'âbidûna li-Rabbinâ hâmidûn.",
    french: "Allah est le plus Grand (3 fois). Nulle divinité à part Allah, Seul sans associé. À Lui la royauté, à Lui la louange. Il est Omnipotent. Nous voilà de retour, repentants, adorateurs de notre Seigneur et Le louant. (Rapporté par Muslim)",
    target: 3,
  },
];
