import { type DhikrItem } from '@/components/dhikr/DhikrCounter';

export interface DouaSubtheme {
  id: string;
  title: string;
  icon: string;
  items: DhikrItem[];
}

export interface DouaCategory {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
  bg: string;
  textColor: string;
  subthemes: DouaSubtheme[];
}

export const DOUAS_CATEGORIES: DouaCategory[] = [
  {
    id: 'aube',
    title: 'Aube & Crépuscule',
    subtitle: 'Sommeil · Réveil · Nuit',
    icon: 'Moon',
    bg: '#1a1a2e',
    textColor: '#D4AF37',
    subthemes: [
      {
        id: 'reveil',
        title: 'Au réveil',
        icon: '🌅',
        items: [
          {
            title: 'Doua du réveil',
            arabic: 'الحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
            phonetic: 'Al-hamdou lillâhi-lladhî ahyânâ ba\'da mâ amâtanâ wa ilayhi-nnushûr',
            french: 'Louange à Allah (عز وجل) qui nous a redonné la vie après nous avoir fait mourir, et c\'est vers Lui la résurrection.',
            target: 1,
            source: 'Al-Boukhârî',
          },
          {
            title: 'Attestation de foi au réveil',
            arabic: 'لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَلاَ إِلَهَ إِلاَّ اللَّهُ وَاللَّهُ أَكْبَرُ',
            phonetic: 'Lâ ilâha illa-llâhou wahdahou lâ sharîka lah, lahou-l-moulkou wa lahou-l-hamd, wa houwa \'alâ koulli shay\'in qadîr. Soubhâna-llâh, wa-l-hamdou lillâh, wa lâ ilâha illa-llâh, wa-llâhou akbar',
            french: 'Il n\'y a de divinité qu\'Allah (عز وجل), Seul sans associé. À Lui la royauté, à Lui la louange et Il est capable de toute chose. Gloire à Allah (عز وجل), louange à Allah (عز وجل), il n\'y a de divinité qu\'Allah (عز وجل), Allah (عز وجل) est Le Plus Grand.',
            target: 1,
            source: 'Al-Boukhârî',
          },
          {
            title: 'Doua en se levant du lit',
            arabic: 'الحَمْدُ لِلَّهِ الَّذِي عَافَانِي فِي جَسَدِي وَرَدَّ عَلَيَّ رُوحِي وَأَذِنَ لِي بِذِكْرِهِ',
            phonetic: 'Al-hamdou lillâhi-lladhî \'âfânî fî jasadî wa radda \'alayya rûhî wa adhina lî bi-dhikrih',
            french: 'Louange à Allah (عز وجل) qui m\'a accordé la santé dans mon corps, m\'a rendu mon âme et m\'a permis de L\'évoquer.',
            target: 1,
            source: 'At-Tirmidhî',
          },
        ],
      },
      {
        id: 'dormir',
        title: 'Avant de dormir',
        icon: '🌙',
        items: [
          {
            title: 'Doua avant de dormir',
            arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
            phonetic: 'Bismika-llâhoumma amûtou wa ahyâ',
            french: 'C\'est en Ton nom, ô Allah (عز وجل), que je meurs et que je vis.',
            target: 1,
            source: 'Al-Boukhârî',
          },
          {
            title: 'Sourate Al-Ikhlâs, Al-Falaq et An-Nâs',
            arabic: 'يَجْمَعُ كَفَّيْهِ ثُمَّ يَنْفُثُ فِيهِمَا فَيَقْرَأُ فِيهِمَا: قُلْ هُوَ اللَّهُ أَحَدٌ… وَ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ… وَ قُلْ أَعُوذُ بِرَبِّ النَّاسِ…',
            phonetic: 'On réunit ses paumes, on souffle dedans puis on récite les 3 sourates protectrices',
            french: 'Le Prophète (ﷺ) rassemblait ses mains chaque nuit, y soufflait et récitait les trois sourates protectrices, puis passait ses mains sur tout son corps.',
            target: 3,
            source: 'Al-Boukhârî et Mouslim',
          },
          {
            title: 'Doua de remise à Allah',
            arabic: 'اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ، وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ، رَغْبَةً وَرَهْبَةً إِلَيْكَ',
            phonetic: 'Allâhoumma aslamtou nafsî ilayka, wa fawwadtou amrî ilayka, wa wajjahtou wajhî ilayka, wa alja\'tou dhahrî ilayka, raghbatan wa rahbatan ilayka',
            french: 'Ô Allah (عز وجل), je me suis soumis à Toi, je T\'ai confié mon sort, j\'ai dirigé mon visage vers Toi et je me suis adossé à Toi, par désir et par crainte envers Toi.',
            target: 1,
            source: 'Al-Boukhârî et Mouslim',
          },
          {
            title: 'Âyat al-Kursî avant de dormir',
            arabic: 'اللَّهُ لاَ إِلَهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ…',
            phonetic: 'Allâhou lâ ilâha illâ houwa-l-hayyou-l-qayyoûm, lâ ta\'khoudhouhou sinatoun wa lâ nawm...',
            french: 'Quiconque récite Âyat al-Kursî avant de dormir, Allah (عز وجل) lui envoie un gardien et aucun démon ne s\'approchera de lui jusqu\'au matin.',
            target: 1,
            source: 'Al-Boukhârî',
          },
        ],
      },
      {
        id: 'insomnie',
        title: 'En cas d\'insomnie',
        icon: '😴',
        items: [
          {
            title: 'Doua de l\'insomnie',
            arabic: 'اللَّهُمَّ غَارَتِ النُّجُومُ وَهَدَأَتِ الْعُيُونُ وَأَنْتَ حَيٌّ قَيُّومٌ، يَا حَيُّ يَا قَيُّومُ أَنِمْ عَيْنِي وَأَهْدِئْ لَيْلِي',
            phonetic: 'Allâhoumma ghârati-nnujoûm, wa hada\'ati-l-\'uyoûn, wa anta hayyoun qayyoûm, yâ hayyou yâ qayyoûm, anim \'aynî wa ahdi\' laylî',
            french: 'Ô Allah (عز وجل), les étoiles se sont couchées, les yeux se sont assoupis et Tu es Le Vivant, Le Subsistant. Ô Vivant, ô Subsistant, endors mes yeux et apaise ma nuit.',
            target: 1,
            source: 'Ibn As-Sounni',
          },
          {
            title: 'Se tourner dans le lit',
            arabic: 'لاَ إِلَهَ إِلاَّ اللَّهُ الْوَاحِدُ الْقَهَّارُ، رَبُّ السَّمَاوَاتِ وَالأَرْضِ وَمَا بَيْنَهُمَا الْعَزِيزُ الْغَفَّارُ',
            phonetic: 'Lâ ilâha illa-llâhou-l-wâhidou-l-qahhâr, rabbou-ssamâwâti wa-l-ardi wa mâ baynahoumâ-l-\'azîzou-l-ghaffâr',
            french: 'Il n\'y a de divinité qu\'Allah (عز وجل), L\'Unique, Le Dominateur Suprême, Seigneur des cieux et de la terre et de ce qui est entre eux, Le Tout-Puissant, Le Grand Pardonneur.',
            target: 1,
            source: 'Al-Hâkim',
          },
        ],
      },
      {
        id: 'cauchemar',
        title: 'Après un cauchemar',
        icon: '😰',
        items: [
          {
            title: 'Protection après un cauchemar',
            arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ غَضَبِهِ وَعِقَابِهِ وَشَرِّ عِبَادِهِ وَمِنْ هَمَزَاتِ الشَّيَاطِينِ وَأَنْ يَحْضُرُونِ',
            phonetic: 'A\'oûdhou bi-kalimâti-llâhi-ttâmmâti min ghadabihi wa \'iqâbihi wa sharri \'ibâdihi wa min hamazâti-shshayâtîn wa an yahduroûn',
            french: 'Je cherche protection auprès des paroles parfaites d\'Allah (عز وجل) contre Sa colère, Son châtiment, le mal de Ses serviteurs et les suggestions des démons.',
            target: 1,
            source: 'Abou Dâwoud',
          },
          {
            title: 'Cracher à gauche et changer de côté',
            arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
            phonetic: 'A\'oûdhou billâhi mina-shshaytâni-rrajîm',
            french: 'Le Prophète (ﷺ) a dit : « Si l\'un de vous voit un mauvais rêve, qu\'il crache (légèrement) trois fois à sa gauche, qu\'il cherche refuge auprès d\'Allah (عز وجل) contre le diable maudit et qu\'il se retourne de l\'autre côté. »',
            target: 3,
            source: 'Mouslim',
          },
        ],
      },
      {
        id: 'priere-nuit',
        title: 'Prière de nuit (Qiyâm)',
        icon: '🤲',
        items: [
          {
            title: 'Doua d\'ouverture du Qiyâm',
            arabic: 'اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ نُورُ السَّمَاوَاتِ وَالأَرْضِ وَمَنْ فِيهِنَّ، وَلَكَ الْحَمْدُ أَنْتَ قَيِّمُ السَّمَاوَاتِ وَالأَرْضِ وَمَنْ فِيهِنَّ',
            phonetic: 'Allâhoumma laka-l-hamd, anta noûrou-ssamâwâti wa-l-ard wa man fîhinn, wa laka-l-hamd anta qayyimou-ssamâwâti wa-l-ard wa man fîhinn',
            french: 'Ô Allah (عز وجل), à Toi la louange ! Tu es la lumière des cieux et de la terre et de ceux qui s\'y trouvent. À Toi la louange, Tu es le Soutien des cieux et de la terre.',
            target: 1,
            source: 'Al-Boukhârî et Mouslim',
          },
          {
            title: 'Doua du Witr',
            arabic: 'اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ، وَعَافِنِي فِيمَنْ عَافَيْتَ، وَتَوَلَّنِي فِيمَنْ تَوَلَّيْتَ، وَبَارِكْ لِي فِيمَا أَعْطَيْتَ، وَقِنِي شَرَّ مَا قَضَيْتَ',
            phonetic: 'Allâhoumma-hdinî fîman hadayt, wa \'âfinî fîman \'âfayt, wa tawallanî fîman tawallayt, wa bârik lî fîmâ a\'tayt, wa qinî sharra mâ qadayt',
            french: 'Ô Allah (عز وجل), guide-moi parmi ceux que Tu as guidés, accorde-moi le salut parmi ceux à qui Tu as accordé le salut, prends-moi en charge parmi ceux que Tu as pris en charge, bénis-moi dans ce que Tu m\'as donné et protège-moi du mal que Tu as décrété.',
            target: 1,
            source: 'Abou Dâwoud et At-Tirmidhî',
          },
          {
            title: 'Invocation du Soujoûd (prosternation)',
            arabic: 'سُبْحَانَ رَبِّيَ الأَعْلَى',
            phonetic: 'Soubhâna rabbiya-l-a\'lâ',
            french: 'Gloire à mon Seigneur Le Très-Haut.',
            target: 3,
            source: 'Mouslim',
          },
        ],
      },
    ],
  },
  {
    id: 'passages',
    title: 'Mes Passages',
    subtitle: 'Mosquée · Voyage · Marché',
    icon: 'MapPin',
    bg: '#faf8f5',
    textColor: '#2d6a4f',
    subthemes: [
      {
        id: 'adhan',
        title: 'Après l\'Adhân',
        icon: '🕌',
        items: [
          {
            title: 'Doua après l\'Adhân',
            arabic: 'اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ',
            phonetic: 'Allâhoumma rabba hâdhihi-dda\'wati-ttâmmah, wa-ssalâti-l-qâ\'imah, âti Muhammadan (ﷺ) al-wasîlata wa-l-fadîlah, wab\'ath-hou maqâman mahmûdani-lladhî wa\'adtah',
            french: 'Ô Allah (عز وجل), Seigneur de cet appel parfait et de cette prière imminente, accorde à Mouhamed (ﷺ) la place privilégiée et la vertu, et ressuscite-le au rang digne de louange que Tu lui as promis.',
            target: 1,
            source: 'Al-Boukhârî',
          },
          {
            title: 'Répéter après le Muezzin',
            arabic: 'يقول مثل ما يقول المؤذن إلا في «حي على الصلاة» و«حي على الفلاح» فيقول: لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ',
            phonetic: 'On répète ce que dit le Muezzin, sauf pour « Hayya \'ala-ssalâh » et « Hayya \'ala-l-falâh » où l\'on dit : Lâ hawla wa lâ qouwwata illâ billâh',
            french: 'Le Prophète (ﷺ) a dit : « Lorsque vous entendez le Muezzin, répétez ce qu\'il dit, puis invoquez la bénédiction sur moi. » Il n\'y a de force ni de puissance qu\'en Allah (عز وجل).',
            target: 1,
            source: 'Mouslim',
          },
        ],
      },
      {
        id: 'mosquee-entree',
        title: 'Entrée à la mosquée',
        icon: '🚪',
        items: [
          {
            title: 'En entrant à la mosquée',
            arabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
            phonetic: 'Allâhoumma-ftah lî abwâba rahmatik',
            french: 'Ô Allah (عز وجل), ouvre-moi les portes de Ta miséricorde.',
            target: 1,
            source: 'Mouslim',
          },
          {
            title: 'Salutations sur le Prophète (ﷺ)',
            arabic: 'بِسْمِ اللَّهِ وَالصَّلاَةُ وَالسَّلاَمُ عَلَى رَسُولِ اللَّهِ',
            phonetic: 'Bismi-llâh, wa-ssalâtou wa-ssalâmou \'alâ rasûli-llâh',
            french: 'Au nom d\'Allah (عز وجل), et la prière et le salut soient sur le Messager d\'Allah (ﷺ).',
            target: 1,
            source: 'Abou Dâwoud',
          },
        ],
      },
      {
        id: 'mosquee-sortie',
        title: 'Sortie de la mosquée',
        icon: '🚶',
        items: [
          {
            title: 'En sortant de la mosquée',
            arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
            phonetic: 'Allâhoumma innî as\'alouka min fadlik',
            french: 'Ô Allah (عز وجل), je Te demande de Ta grâce.',
            target: 1,
            source: 'Mouslim',
          },
          {
            title: 'Salutations en sortant',
            arabic: 'بِسْمِ اللَّهِ وَالصَّلاَةُ وَالسَّلاَمُ عَلَى رَسُولِ اللَّهِ، اللَّهُمَّ اعْصِمْنِي مِنَ الشَّيْطَانِ الرَّجِيمِ',
            phonetic: 'Bismi-llâh, wa-ssalâtou wa-ssalâmou \'alâ rasûli-llâh, Allâhoumma-\'simnî mina-shshaytâni-rrajîm',
            french: 'Au nom d\'Allah (عز وجل), prière et salut sur le Messager d\'Allah (ﷺ). Ô Allah (عز وجل), protège-moi du diable maudit.',
            target: 1,
            source: 'Ibn Mâjah',
          },
        ],
      },
      {
        id: 'voyage-depart',
        title: 'Doua du voyage (départ)',
        icon: '✈️',
        items: [
          {
            title: 'Doua du voyage',
            arabic: 'اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
            phonetic: 'Allâhou akbar, Allâhou akbar, Allâhou akbar, soubhâna-lladhî sakhkhara lanâ hâdhâ wa mâ kounnâ lahou mouqrinîn, wa innâ ilâ rabbinâ lamounqaliboûn',
            french: 'Allah (عز وجل) est Le Plus Grand ! Gloire à Celui qui a mis ceci à notre service alors que nous n\'étions pas capables de le dominer, et c\'est vers notre Seigneur que nous retournerons.',
            target: 1,
            source: 'Mouslim',
          },
          {
            title: 'Doua de confiance au voyage',
            arabic: 'اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى وَمِنَ الْعَمَلِ مَا تَرْضَى',
            phonetic: 'Allâhoumma innâ nas\'alouka fî safarinâ hâdha-l-birra wa-ttaqwâ wa mina-l-\'amali mâ tardâ',
            french: 'Ô Allah (عز وجل), nous Te demandons dans ce voyage la piété, la crainte révérencielle et les œuvres dont Tu es satisfait.',
            target: 1,
            source: 'Mouslim',
          },
          {
            title: 'Doua du retour de voyage',
            arabic: 'آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ',
            phonetic: 'Âyiboûn, tâ\'iboûn, \'âbidoûn, li-rabbinâ hâmidoûn',
            french: 'Nous voici de retour, repentants, adorateurs de notre Seigneur et Le louant.',
            target: 1,
            source: 'Al-Boukhârî et Mouslim',
          },
        ],
      },
      {
        id: 'marche',
        title: 'Entrée au marché',
        icon: '🛒',
        items: [
          {
            title: 'Doua du marché',
            arabic: 'لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ يُحْيِي وَيُمِيتُ وَهُوَ حَيٌّ لاَ يَمُوتُ بِيَدِهِ الْخَيْرُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
            phonetic: 'Lâ ilâha illa-llâhou wahdahou lâ sharîka lah, lahou-l-moulkou wa lahou-l-hamd, youhyî wa youmîtou wa houwa hayyoun lâ yamoûtou biyadihi-l-khayr wa houwa \'alâ koulli shay\'in qadîr',
            french: 'Il n\'y a de divinité qu\'Allah (عز وجل), Seul sans associé. À Lui la royauté, à Lui la louange. Il donne la vie et la mort, Il est Le Vivant qui ne meurt pas. Le bien est dans Sa main et Il est capable de toute chose.',
            target: 1,
            source: 'At-Tirmidhî',
          },
        ],
      },
      {
        id: 'vehicule',
        title: 'Monter en véhicule',
        icon: '🚗',
        items: [
          {
            title: 'En montant en véhicule',
            arabic: 'بِسْمِ اللَّهِ، الْحَمْدُ لِلَّهِ، سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
            phonetic: 'Bismi-llâh, al-hamdou lillâh, soubhâna-lladhî sakhkhara lanâ hâdhâ wa mâ kounnâ lahou mouqrinîn, wa innâ ilâ rabbinâ lamounqaliboûn',
            french: 'Au nom d\'Allah (عز وجل), louange à Allah (عز وجل). Gloire à Celui qui a mis ceci à notre service alors que nous n\'étions pas capables de le dominer.',
            target: 1,
            source: 'Mouslim',
          },
          {
            title: 'Doua en sortant de la maison',
            arabic: 'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ',
            phonetic: 'Bismi-llâh, tawakkaltou \'ala-llâh, wa lâ hawla wa lâ qouwwata illâ billâh',
            french: 'Au nom d\'Allah (عز وجل), je place ma confiance en Allah (عز وجل) et il n\'y a de force ni de puissance qu\'en Allah (عز وجل).',
            target: 1,
            source: 'Abou Dâwoud et At-Tirmidhî',
          },
        ],
      },
      {
        id: 'maison',
        title: 'Entrée à la maison',
        icon: '🏠',
        items: [
          {
            title: 'En entrant chez soi',
            arabic: 'بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا',
            phonetic: 'Bismi-llâhi walajnâ, wa bismi-llâhi kharajnâ, wa \'ala-llâhi rabbinâ tawakkalnâ',
            french: 'C\'est au nom d\'Allah (عز وجل) que nous entrons, au nom d\'Allah (عز وجل) que nous sortons, et c\'est en Allah (عز وجل) notre Seigneur que nous plaçons notre confiance.',
            target: 1,
            source: 'Abou Dâwoud',
          },
          {
            title: 'Saluer les gens de la maison',
            arabic: 'السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ',
            phonetic: 'As-salâmou \'alaykoum wa rahmatou-llâhi wa barakâtouh',
            french: 'Que la paix soit sur vous ainsi que la miséricorde d\'Allah (عز وجل) et Ses bénédictions.',
            target: 1,
            source: 'An-Nûr, 61',
          },
        ],
      },
    ],
  },
  {
    id: 'quotidien',
    title: 'Actes du Quotidien',
    subtitle: 'Repas · Pluie · Mariage',
    icon: 'Heart',
    bg: '#c8d5c0',
    textColor: '#1b4332',
    subthemes: [
      {
        id: 'avant-repas',
        title: 'Avant le repas',
        icon: '🍽️',
        items: [
          {
            title: 'Avant de manger',
            arabic: 'بِسْمِ اللَّهِ',
            phonetic: 'Bismi-llâh',
            french: 'Au nom d\'Allah (عز وجل).',
            target: 1,
            source: 'Mouslim',
          },
          {
            title: 'Si on oublie au début',
            arabic: 'بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ',
            phonetic: 'Bismi-llâhi awwalahou wa âkhirah',
            french: 'Au nom d\'Allah (عز وجل) au début et à la fin.',
            target: 1,
            source: 'Abou Dâwoud et At-Tirmidhî',
          },
        ],
      },
      {
        id: 'apres-repas',
        title: 'Après le repas',
        icon: '🤲',
        items: [
          {
            title: 'Après avoir mangé',
            arabic: 'الحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلاَ قُوَّةٍ',
            phonetic: 'Al-hamdou lillâhi-lladhî at\'amanî hâdhâ wa razaqanîhi min ghayri hawlin minnî wa lâ qouwwah',
            french: 'Louange à Allah (عز وجل) qui m\'a nourri de ceci et me l\'a accordé sans force ni puissance de ma part.',
            target: 1,
            source: 'Abou Dâwoud et At-Tirmidhî',
          },
          {
            title: 'Doua pour l\'hôte',
            arabic: 'اللَّهُمَّ بَارِكْ لَهُمْ فِيمَا رَزَقْتَهُمْ وَاغْفِرْ لَهُمْ وَارْحَمْهُمْ',
            phonetic: 'Allâhoumma bârik lahoum fîmâ razaqtahoum wa-ghfir lahoum wa-rhamhoum',
            french: 'Ô Allah (عز وجل), bénis-les dans ce que Tu leur as donné comme subsistance, pardonne-leur et fais-leur miséricorde.',
            target: 1,
            source: 'Mouslim',
          },
        ],
      },
      {
        id: 'pluie',
        title: 'Lorsqu\'il pleut',
        icon: '🌧️',
        items: [
          {
            title: 'Doua sous la pluie',
            arabic: 'اللَّهُمَّ صَيِّبًا نَافِعًا',
            phonetic: 'Allâhoumma sayyiban nâfi\'an',
            french: 'Ô Allah (عز وجل), accorde-nous une pluie bénéfique.',
            target: 1,
            source: 'Al-Boukhârî',
          },
          {
            title: 'Après la pluie',
            arabic: 'مُطِرْنَا بِفَضْلِ اللَّهِ وَرَحْمَتِهِ',
            phonetic: 'Moutirnâ bi-fadli-llâhi wa rahmatih',
            french: 'Il a plu par la grâce d\'Allah (عز وجل) et Sa miséricorde.',
            target: 1,
            source: 'Al-Boukhârî et Mouslim',
          },
        ],
      },
      {
        id: 'tonnerre',
        title: 'En entendant le tonnerre',
        icon: '⛈️',
        items: [
          {
            title: 'Doua du tonnerre',
            arabic: 'سُبْحَانَ الَّذِي يُسَبِّحُ الرَّعْدُ بِحَمْدِهِ وَالْمَلائِكَةُ مِنْ خِيفَتِهِ',
            phonetic: 'Soubhâna-lladhî yousabbih-hou ar-ra\'dou bihamdihi wa-l-malâ\'ikatou min khîfatih',
            french: 'Gloire à Celui dont le tonnerre Le glorifie par Sa louange, ainsi que les anges, par crainte de Lui.',
            target: 1,
            source: 'Al-Mouwattâ\' de l\'Imam Mâlik',
          },
          {
            title: 'Demande de protection contre le vent',
            arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا وَخَيْرَ مَا فِيهَا وَخَيْرَ مَا أُرْسِلَتْ بِهِ، وَأَعُوذُ بِكَ مِنْ شَرِّهَا وَشَرِّ مَا فِيهَا وَشَرِّ مَا أُرْسِلَتْ بِهِ',
            phonetic: 'Allâhoumma innî as\'alouka khayrahâ wa khayra mâ fîhâ wa khayra mâ oursilat bih, wa a\'oûdhou bika min sharrihâ wa sharri mâ fîhâ wa sharri mâ oursilat bih',
            french: 'Ô Allah (عز وجل), je Te demande son bien, le bien qu\'elle contient et le bien avec lequel elle a été envoyée, et je me réfugie auprès de Toi contre son mal, le mal qu\'elle contient et le mal avec lequel elle a été envoyée.',
            target: 1,
            source: 'Mouslim',
          },
        ],
      },
      {
        id: 'mariage',
        title: 'Félicitations de mariage',
        icon: '💍',
        items: [
          {
            title: 'Doua pour les mariés',
            arabic: 'بَارَكَ اللَّهُ لَكَ وَبَارَكَ عَلَيْكَ وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ',
            phonetic: 'Bâraka-llâhou laka, wa bâraka \'alayka, wa jama\'a baynakoumâ fî khayr',
            french: 'Qu\'Allah (عز وجل) te bénisse, répande Ses bénédictions sur toi et vous réunisse dans le bien.',
            target: 1,
            source: 'Abou Dâwoud et At-Tirmidhî',
          },
          {
            title: 'Doua de la nuit de noces',
            arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا وَخَيْرَ مَا جَبَلْتَهَا عَلَيْهِ، وَأَعُوذُ بِكَ مِنْ شَرِّهَا وَشَرِّ مَا جَبَلْتَهَا عَلَيْهِ',
            phonetic: 'Allâhoumma innî as\'alouka khayrahâ wa khayra mâ jabaltahâ \'alayh, wa a\'oûdhou bika min sharrihâ wa sharri mâ jabaltahâ \'alayh',
            french: 'Ô Allah (عز وجل), je Te demande son bien et le bien sur lequel Tu l\'as disposée, et je me réfugie auprès de Toi contre son mal et le mal sur lequel Tu l\'as disposée.',
            target: 1,
            source: 'Abou Dâwoud et Ibn Mâjah',
          },
        ],
      },
      {
        id: 'nouveau-ne',
        title: 'Nouveau-né',
        icon: '👶',
        items: [
          {
            title: 'Doua pour le nouveau-né',
            arabic: 'بَارَكَ اللَّهُ لَكَ فِي الْمَوْهُوبِ لَكَ وَشَكَرْتَ الْوَاهِبَ وَبَلَغَ أَشُدَّهُ وَرُزِقْتَ بِرَّهُ',
            phonetic: 'Bâraka-llâhou laka fî-l-mawhûbi lak, wa shakarta-l-wâhib, wa balagha ashoud-dahou, wa rouziqta birrah',
            french: 'Qu\'Allah (عز وجل) te bénisse dans ce qui t\'a été offert, que tu remercies Le Donateur, qu\'il atteigne sa pleine maturité et que tu sois gratifié de sa piété filiale.',
            target: 1,
            source: 'An-Nawawî',
          },
          {
            title: 'Réponse à la félicitation',
            arabic: 'بَارَكَ اللَّهُ لَكَ وَبَارَكَ عَلَيْكَ وَجَزَاكَ اللَّهُ خَيْرًا وَرَزَقَكَ اللَّهُ مِثْلَهُ وَأَجْزَلَ ثَوَابَكَ',
            phonetic: 'Bâraka-llâhou laka wa bâraka \'alayka, wa jazâka-llâhou khayran, wa razaqaka-llâhou mithlah, wa ajzala thawâbak',
            french: 'Qu\'Allah (عز وجل) te bénisse, répande sur toi Ses bénédictions, te récompense en bien, te gratifie d\'un semblable et multiplie ta récompense.',
            target: 1,
            source: 'An-Nawawî',
          },
        ],
      },
      {
        id: 'vetement-neuf',
        title: 'Vêtement neuf',
        icon: '👗',
        items: [
          {
            title: 'En portant un vêtement neuf',
            arabic: 'اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ كَسَوْتَنِيهِ، أَسْأَلُكَ مِنْ خَيْرِهِ وَخَيْرِ مَا صُنِعَ لَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّهِ وَشَرِّ مَا صُنِعَ لَهُ',
            phonetic: 'Allâhoumma laka-l-hamdou anta kasawtanîh, as\'alouka min khayrihi wa khayri mâ souni\'a lah, wa a\'oûdhou bika min sharrihi wa sharri mâ souni\'a lah',
            french: 'Ô Allah (عز وجل), à Toi la louange, c\'est Toi qui m\'en as revêtu. Je Te demande son bien et le bien pour lequel il a été fait, et je me réfugie auprès de Toi contre son mal et le mal pour lequel il a été fait.',
            target: 1,
            source: 'Abou Dâwoud et At-Tirmidhî',
          },
          {
            title: 'Doua pour celui qui porte un vêtement neuf',
            arabic: 'تُبْلِي وَيُخْلِفُ اللَّهُ تَعَالَى',
            phonetic: 'Toublî wa youkhlifou-llâhou ta\'âlâ',
            french: 'Puisses-tu le porter jusqu\'à ce qu\'il s\'use, et qu\'Allah (عز وجل) Le Très-Haut te le remplace.',
            target: 1,
            source: 'Abou Dâwoud',
          },
        ],
      },
      {
        id: 'miroir',
        title: 'En se regardant dans le miroir',
        icon: '🪞',
        items: [
          {
            title: 'Doua du miroir',
            arabic: 'اللَّهُمَّ أَنْتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي',
            phonetic: 'Allâhoumma anta hassanta khalqî fa-hassin khoulouqî',
            french: 'Ô Allah (عز وجل), Tu as embelli ma création, embellis donc mon caractère.',
            target: 1,
            source: 'Ahmad',
          },
          {
            title: 'Louange en se regardant',
            arabic: 'الحَمْدُ لِلَّهِ، اللَّهُمَّ كَمَا حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي',
            phonetic: 'Al-hamdou lillâh, Allâhoumma kamâ hassanta khalqî fa-hassin khoulouqî',
            french: 'Louange à Allah (عز وجل). Ô Allah (عز وجل), de même que Tu as embelli ma forme, embellis mon caractère.',
            target: 1,
            source: 'Ibn As-Sounni',
          },
        ],
      },
      {
        id: 'toilettes',
        title: 'Entrée/sortie des toilettes',
        icon: '🚻',
        items: [
          {
            title: 'En entrant aux toilettes',
            arabic: 'بِسْمِ اللَّهِ، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبْثِ وَالْخَبَائِثِ',
            phonetic: 'Bismi-llâh, Allâhoumma innî a\'oûdhou bika mina-l-khoubthi wa-l-khabâ\'ith',
            french: 'Au nom d\'Allah (عز وجل). Ô Allah (عز وجل), je cherche refuge auprès de Toi contre les démons mâles et femelles.',
            target: 1,
            source: 'Al-Boukhârî et Mouslim',
          },
          {
            title: 'En sortant des toilettes',
            arabic: 'غُفْرَانَكَ',
            phonetic: 'Ghoufrânak',
            french: 'Je Te demande pardon (ô Allah عز وجل).',
            target: 1,
            source: 'Abou Dâwoud et At-Tirmidhî',
          },
        ],
      },
    ],
  },
  {
    id: 'reconfort',
    title: 'Réconfort & Lumière',
    subtitle: 'Épreuves · Dettes · Deuil',
    icon: 'Sparkles',
    bg: '#065F46',
    textColor: '#D4AF37',
    subthemes: [
      {
        id: 'dettes',
        title: 'Soulagement des dettes',
        icon: '💰',
        items: [
          {
            title: 'Doua contre les dettes',
            arabic: 'اللَّهُمَّ اكْفِنِي بِحَلالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
            phonetic: 'Allâhoumma-kfinî bi-halâlika \'an harâmik, wa aghninî bi-fadlika \'amman siwâk',
            french: 'Ô Allah (عز وجل), accorde-moi suffisance par Ton licite plutôt que Ton illicite, et enrichis-moi par Ta grâce de sorte que je n\'aie besoin de personne d\'autre que Toi.',
            target: 3,
            source: 'At-Tirmidhî',
          },
          {
            title: 'Doua contre le souci et la dette',
            arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْمَأْثَمِ وَالْمَغْرَمِ',
            phonetic: 'Allâhoumma innî a\'oûdhou bika mina-l-ma\'thami wa-l-maghram',
            french: 'Ô Allah (عز وجل), je cherche refuge auprès de Toi contre le péché et la dette.',
            target: 3,
            source: 'Al-Boukhârî et Mouslim',
          },
        ],
      },
      {
        id: 'affliction',
        title: 'Affliction et tristesse',
        icon: '😢',
        items: [
          {
            title: 'Doua de la détresse',
            arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحُزْنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ',
            phonetic: 'Allâhoumma innî a\'oûdhou bika mina-l-hammi wa-l-houzn, wa-l-\'ajzi wa-l-kasal, wa-l-boukhli wa-l-joubn, wa dala\'i-ddayni wa ghalabati-rrijâl',
            french: 'Ô Allah (عز وجل), je cherche refuge auprès de Toi contre le souci et la tristesse, l\'incapacité et la paresse, l\'avarice et la lâcheté, le fardeau des dettes et la domination des hommes.',
            target: 3,
            source: 'Al-Boukhârî',
          },
          {
            title: 'Doua de Younous (عليه السلام)',
            arabic: 'لاَ إِلَهَ إِلاَّ أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ',
            phonetic: 'Lâ ilâha illâ anta soubhânaka innî kountou mina-ddhâlimîn',
            french: 'Il n\'y a de divinité que Toi, Gloire à Toi ! J\'ai été certes du nombre des injustes. Invocation de Younous (عليه السلام) dans le ventre de la baleine.',
            target: 7,
            source: 'At-Tirmidhî — Doua de Younous (عليه السلام)',
          },
          {
            title: 'Doua de la grande détresse',
            arabic: 'لاَ إِلَهَ إِلاَّ اللَّهُ الْعَظِيمُ الْحَلِيمُ، لاَ إِلَهَ إِلاَّ اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ، لاَ إِلَهَ إِلاَّ اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الأَرْضِ وَرَبُّ الْعَرْشِ الْكَرِيمِ',
            phonetic: 'Lâ ilâha illa-llâhou-l-\'adhîmou-l-halîm, lâ ilâha illa-llâhou rabbou-l-\'arshi-l-\'adhîm, lâ ilâha illa-llâhou rabbou-ssamâwâti wa rabbou-l-ardi wa rabbou-l-\'arshi-l-karîm',
            french: 'Il n\'y a de divinité qu\'Allah (عز وجل), Le Très Grand, Le Très Clément. Il n\'y a de divinité qu\'Allah (عز وجل), Seigneur du Trône immense. Il n\'y a de divinité qu\'Allah (عز وجل), Seigneur des cieux, Seigneur de la terre et Seigneur du Trône généreux.',
            target: 3,
            source: 'Al-Boukhârî et Mouslim',
          },
        ],
      },
      {
        id: 'deces',
        title: 'Décès et condoléances',
        icon: '🕊️',
        items: [
          {
            title: 'En apprenant un décès',
            arabic: 'إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ، اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا',
            phonetic: 'Innâ lillâhi wa innâ ilayhi râji\'oûn, Allâhoumma-journi fî mousîbatî wa akhlif lî khayran minhâ',
            french: 'Certes nous appartenons à Allah (عز وجل) et c\'est vers Lui que nous retournerons. Ô Allah (عز وجل), accorde-moi une récompense dans mon épreuve et remplace-la par quelque chose de meilleur.',
            target: 1,
            source: 'Mouslim',
          },
          {
            title: 'Doua pour le défunt',
            arabic: 'اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ وَعَافِهِ وَاعْفُ عَنْهُ وَأَكْرِمْ نُزُلَهُ وَوَسِّعْ مُدْخَلَهُ وَاغْسِلْهُ بِالْمَاءِ وَالثَّلْجِ وَالْبَرَدِ',
            phonetic: 'Allâhoumma-ghfir lahou wa-rhamhou wa \'âfihi wa-\'fou \'anhou wa akrim nouzoulahou wa wassi\' moudkhalahou wa-ghsilhou bi-l-mâ\'i wa-ththalji wa-l-barad',
            french: 'Ô Allah (عز وجل), pardonne-lui, fais-lui miséricorde, accorde-lui le salut, excuse-le, honore sa demeure, élargis son entrée et lave-le avec l\'eau, la neige et la grêle.',
            target: 1,
            source: 'Mouslim',
          },
          {
            title: 'Condoléances',
            arabic: 'إِنَّ لِلَّهِ مَا أَخَذَ وَلَهُ مَا أَعْطَى وَكُلُّ شَيْءٍ عِنْدَهُ بِأَجَلٍ مُسَمًّى، فَلْتَصْبِرْ وَلْتَحْتَسِبْ',
            phonetic: 'Inna lillâhi mâ akhadha wa lahou mâ a\'tâ, wa koullou shay\'in \'indahou bi-ajalin mousamman, faltasbir wa-ltahtasib',
            french: 'Certes à Allah (عز وجل) appartient ce qu\'Il a repris et à Lui ce qu\'Il a donné, et toute chose a auprès de Lui un terme fixé. Patiente donc et espère la récompense.',
            target: 1,
            source: 'Al-Boukhârî et Mouslim',
          },
        ],
      },
      {
        id: 'visite-malade',
        title: 'Visite du malade',
        icon: '🏥',
        items: [
          {
            title: 'Doua pour le malade',
            arabic: 'أَسْأَلُ اللَّهَ الْعَظِيمَ رَبَّ الْعَرْشِ الْعَظِيمِ أَنْ يَشْفِيَكَ',
            phonetic: 'As\'alou-llâha-l-\'adhîma rabba-l-\'arshi-l-\'adhîmi an yashfiyak',
            french: 'Je demande à Allah (عز وجل), Le Très Grand, Seigneur du Trône immense, de te guérir.',
            target: 7,
            source: 'Abou Dâwoud et At-Tirmidhî',
          },
          {
            title: 'Doua en posant la main sur la douleur',
            arabic: 'بِسْمِ اللَّهِ (ثلاثاً)، أَعُوذُ بِعِزَّةِ اللَّهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ',
            phonetic: 'Bismi-llâh (3 fois), a\'oûdhou bi-\'izzati-llâhi wa qoudratihi min sharri mâ ajidou wa ouhâdhir',
            french: 'Au nom d\'Allah (عز وجل) (3 fois). Je me réfugie auprès de la puissance d\'Allah (عز وجل) et de Son pouvoir contre le mal de ce que je ressens et que je crains.',
            target: 7,
            source: 'Mouslim',
          },
          {
            title: 'Doua de la Rouqiya',
            arabic: 'بِسْمِ اللَّهِ أَرْقِيكَ مِنْ كُلِّ شَيْءٍ يُؤْذِيكَ مِنْ شَرِّ كُلِّ نَفْسٍ أَوْ عَيْنِ حَاسِدٍ، اللَّهُ يَشْفِيكَ بِسْمِ اللَّهِ أَرْقِيكَ',
            phonetic: 'Bismi-llâhi arqîka min koulli shay\'in you\'dhîk, min sharri koulli nafsin aw \'ayni hâsid, Allâhou yashfîk, bismi-llâhi arqîk',
            french: 'Au nom d\'Allah (عز وجل), je te fais la Rouqiya contre toute chose qui te nuit, contre le mal de toute âme ou d\'un œil envieux. Qu\'Allah (عز وجل) te guérisse. Au nom d\'Allah (عز وجل), je te fais la Rouqiya.',
            target: 3,
            source: 'Mouslim',
          },
        ],
      },
      {
        id: 'peur',
        title: 'En cas de peur',
        icon: '😨',
        items: [
          {
            title: 'Doua de la peur',
            arabic: 'لاَ إِلَهَ إِلاَّ اللَّهُ',
            phonetic: 'Lâ ilâha illa-llâh',
            french: 'Il n\'y a de divinité qu\'Allah (عز وجل).',
            target: 3,
            source: 'Al-Boukhârî et Mouslim',
          },
          {
            title: 'Refuge contre le mal',
            arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
            phonetic: 'A\'oûdhou bi-kalimâti-llâhi-ttâmmâti min sharri mâ khalaq',
            french: 'Je cherche refuge auprès des paroles parfaites d\'Allah (عز وجل) contre le mal de ce qu\'Il a créé.',
            target: 3,
            source: 'Mouslim',
          },
          {
            title: 'Doua contre l\'angoisse nocturne',
            arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ غَضَبِهِ وَعِقَابِهِ وَمِنْ شَرِّ عِبَادِهِ وَمِنْ هَمَزَاتِ الشَّيَاطِينِ وَأَنْ يَحْضُرُونِ',
            phonetic: 'A\'oûdhou bi-kalimâti-llâhi-ttâmmati min ghadabihi wa \'iqâbihi wa min sharri \'ibâdihi wa min hamazâti-shshayâtîn wa an yahduroûn',
            french: 'Je cherche refuge auprès des paroles parfaites d\'Allah (عز وجل) contre Sa colère et Son châtiment, contre le mal de Ses serviteurs et les insufflations des démons, et contre leur présence.',
            target: 3,
            source: 'Abou Dâwoud',
          },
        ],
      },
      {
        id: 'difficulte',
        title: 'Face à une difficulté',
        icon: '🤲',
        items: [
          {
            title: 'Doua de la difficulté',
            arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
            phonetic: 'Hasbounâ-llâhou wa ni\'ma-l-wakîl',
            french: 'Allah (عز وجل) nous suffit et Il est Le Meilleur Garant.',
            target: 7,
            source: 'Al-Boukhârî — Parole d\'Ibrâhîm (عليه السلام)',
          },
          {
            title: 'Invocation de la détresse',
            arabic: 'اللَّهُمَّ رَحْمَتَكَ أَرْجُو فَلاَ تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ وَأَصْلِحْ لِي شَأْنِي كُلَّهُ لاَ إِلَهَ إِلاَّ أَنْتَ',
            phonetic: 'Allâhoumma rahmataka arjou falâ takilnî ilâ nafsî tarfata \'ayn, wa aslih lî sha\'nî koullah, lâ ilâha illâ ant',
            french: 'Ô Allah (عز وجل), c\'est Ta miséricorde que j\'espère, ne me laisse pas à moi-même un clin d\'œil, et arrange pour moi toute mon affaire. Il n\'y a de divinité que Toi.',
            target: 3,
            source: 'Abou Dâwoud',
          },
          {
            title: 'Doua de Moûsâ (عليه السلام)',
            arabic: 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي يَفْقَهُوا قَوْلِي',
            phonetic: 'Rabbi-shrah lî sadrî, wa yassir lî amrî, wa-hloul \'ouqdatan min lisânî yafqahoû qawlî',
            french: 'Seigneur, ouvre-moi ma poitrine, facilite-moi ma mission et dénoue un nœud en ma langue afin qu\'ils comprennent mes paroles. Invocation de Moûsâ (عليه السلام).',
            target: 3,
            source: 'Sourate Tâ-Hâ, 25-28',
          },
        ],
      },
      {
        id: 'istikhara',
        title: 'Prière de consultation (Istikhrâ)',
        icon: '🌟',
        items: [
          {
            title: 'Doua de l\'Istikhâra',
            arabic: 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ فَإِنَّكَ تَقْدِرُ وَلاَ أَقْدِرُ وَتَعْلَمُ وَلاَ أَعْلَمُ وَأَنْتَ عَلاَّمُ الْغُيُوبِ',
            phonetic: 'Allâhoumma innî astakhîrouka bi-\'ilmik, wa astaqdirouka bi-qoudratik, wa as\'alouka min fadlika-l-\'adhîm, fa-innaka taqdiru wa lâ aqdir, wa ta\'lamou wa lâ a\'lam, wa anta \'allâmou-l-ghouyoûb',
            french: 'Ô Allah (عز وجل), je Te consulte par Ta science, je Te demande la capacité par Ton pouvoir et je Te demande de Ta grâce immense, car Tu es capable et je ne le suis pas, Tu sais et je ne sais pas, et Tu es Le Connaisseur des choses cachées.',
            target: 1,
            source: 'Al-Boukhârî',
          },
          {
            title: 'Suite de la doua de l\'Istikhâra',
            arabic: 'اللَّهُمَّ إِنْ كُنْتَ تَعْلَمُ أَنَّ هَذَا الأَمْرَ خَيْرٌ لِي فِي دِينِي وَمَعَاشِي وَعَاقِبَةِ أَمْرِي فَاقْدُرْهُ لِي وَيَسِّرْهُ لِي ثُمَّ بَارِكْ لِي فِيهِ',
            phonetic: 'Allâhoumma in kounta ta\'lamou anna hâdha-l-amra khayrun lî fî dînî wa ma\'âshî wa \'âqibati amrî, faqdurhou lî wa yassirhou lî thoumma bârik lî fîh',
            french: 'Ô Allah (عز وجل), si Tu sais que cette affaire est un bien pour moi dans ma religion, ma vie ici-bas et mon devenir, alors décrète-la pour moi, facilite-la moi puis bénis-la moi.',
            target: 1,
            source: 'Al-Boukhârî',
          },
        ],
      },
    ],
  },
];
