import { DhikrItem } from '@/components/dhikr/DhikrCounter';

export const QURAN_INVOCATIONS: DhikrItem[] = [
  {
    title: 'Al-Fâtiha',
    arabic: 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ ﴿١﴾ ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ ﴿٢﴾ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ ﴿٣﴾ مَٰلِكِ يَوْمِ ٱلدِّينِ ﴿٤﴾ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ﴿٥﴾ ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ ﴿٦﴾ صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ ﴿٧﴾',
    phonetic: 'Bismillâhi r-Rahmâni r-Rahîm. Al-hamdu lillâhi Rabbi l-\'âlamîn. Ar-Rahmâni r-Rahîm. Mâliki yawmi d-dîn. Iyyâka na\'budu wa iyyâka nasta\'în. Ihdinâ s-sirâta l-mustaqîm. Sirâta lladhîna an\'amta \'alayhim, ghayri l-maghdûbi \'alayhim wa la d-dâllîn.',
    french: 'Au nom d\'Allah (عز وجل), le Tout Miséricordieux, le Très Miséricordieux. Louange à Allah (عز وجل), Seigneur des mondes. Le Tout Miséricordieux, le Très Miséricordieux. Maître du Jour de la rétribution. C\'est Toi [Seul] que nous adorons, et c\'est Toi [Seul] dont nous implorons secours. Guide-nous dans le droit chemin. Le chemin de ceux que Tu as comblés de faveurs, non pas de ceux qui ont encouru Ta colère, ni des égarés.',
    target: 1,
    source: 'Coran 1:1-7',
  },
  {
    title: 'Âyat al-Kursî',
    arabic: 'ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۚ لَا تَأْخُذُهُۥ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۗ مَن ذَا ٱلَّذِى يَشْفَعُ عِندَهُۥٓ إِلَّا بِإِذْنِهِۦ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَىْءٍ مِّنْ عِلْمِهِۦٓ إِلَّا بِمَا شَآءَ ۚ وَسِعَ كُرْسِيُّهُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ ۖ وَلَا يَـُٔودُهُۥ حِفْظُهُمَا ۚ وَهُوَ ٱلْعَلِىُّ ٱلْعَظِيمُ',
    phonetic: 'Allâhu lâ ilâha illâ Huwa, al-Hayyu l-Qayyûm. Lâ ta\'khudhuhu sinatun wa lâ nawm...',
    french: 'Allah (عز وجل) ! Point de divinité à part Lui, le Vivant, Celui qui subsiste par Lui-même. Ni somnolence ni sommeil ne Le saisissent. À Lui appartient tout ce qui est dans les cieux et sur la terre...',
    target: 1,
    source: 'Coran 2:255 — Al-Bukhârî n°5010',
  },
  {
    title: 'Fin de sourate Al-Baqara (v.285)',
    arabic: 'ءَامَنَ ٱلرَّسُولُ بِمَآ أُنزِلَ إِلَيْهِ مِن رَّبِّهِۦ وَٱلْمُؤْمِنُونَ ۚ كُلٌّ ءَامَنَ بِٱللَّهِ وَمَلَٰٓئِكَتِهِۦ وَكُتُبِهِۦ وَرُسُلِهِۦ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّن رُّسُلِهِۦ ۚ وَقَالُواْ سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ ٱلْمَصِيرُ',
    phonetic: 'Âmana r-rasûlu bimâ unzila ilayhi min Rabbihi wa l-mu\'minûn...',
    french: 'Le Messager (ﷺ) a cru en ce qui a été descendu vers lui venant de son Seigneur, et les croyants aussi. Tous ont cru en Allah (عز وجل), en Ses anges, en Ses livres et en Ses messagers (عليهم السلام).',
    target: 1,
    source: 'Coran 2:285 — Muslim n°807',
  },
  {
    title: 'Fin de sourate Al-Baqara (v.286)',
    arabic: 'لَا يُكَلِّفُ ٱللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا ٱكْتَسَبَتْ ۗ رَبَّنَا لَا تُؤَاخِذْنَآ إِن نَّسِينَآ أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَآ إِصْرًا كَمَا حَمَلْتَهُۥ عَلَى ٱلَّذِينَ مِن قَبْلِنَا ۚ رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِۦ ۖ وَٱعْفُ عَنَّا وَٱغْفِرْ لَنَا وَٱرْحَمْنَآ ۚ أَنتَ مَوْلَىٰنَا فَٱنصُرْنَا عَلَى ٱلْقَوْمِ ٱلْكَٰفِرِينَ',
    phonetic: 'Lâ yukallifu llâhu nafsan illâ wus\'ahâ... Rabbanâ lâ tu\'âkhidhnâ in nasînâ aw akhta\'nâ...',
    french: 'Allah (عز وجل) n\'impose à aucune âme une charge supérieure à sa capacité. Seigneur, ne nous tiens pas rigueur si nous oublions ou commettons une erreur. Seigneur, pardonne-nous et fais-nous miséricorde. Tu es notre Maître.',
    target: 1,
    source: 'Coran 2:286 — Muslim n°126',
  },
  {
    title: 'Invocation d\'Ibrâhîm (عليه السلام)',
    arabic: 'رَبِّ ٱجْعَلْنِى مُقِيمَ ٱلصَّلَوٰةِ وَمِن ذُرِّيَّتِى ۚ رَبَّنَا وَتَقَبَّلْ دُعَآءِ ﴿٤٠﴾ رَبَّنَا ٱغْفِرْ لِى وَلِوَٰلِدَىَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ ٱلْحِسَابُ ﴿٤١﴾',
    phonetic: 'Rabbi j\'alnî muqîma s-salâti wa min dhurriyyatî, Rabbanâ wa taqabbal du\'â\'î. Rabbanâ ghfir lî wa liwâlidayya wa lil-mu\'minîna yawma yaqûmu l-hisâb.',
    french: 'Ô mon Seigneur ! Fais que j\'accomplisse assidûment la prière, ainsi qu\'une partie de ma descendance. Ô notre Seigneur, accepte mon invocation. Ô notre Seigneur, pardonne-moi, ainsi qu\'à mes parents et aux croyants le Jour du Compte.',
    target: 1,
    source: 'Coran 14:40-41 — Invocation du Prophète Ibrâhîm (عليه السلام)',
  },
  {
    title: 'Invocation de Mûsâ (عليه السلام)',
    arabic: 'رَبِّ ٱشْرَحْ لِى صَدْرِى ﴿٢٥﴾ وَيَسِّرْ لِىٓ أَمْرِى ﴿٢٦﴾ وَٱحْلُلْ عُقْدَةً مِّن لِّسَانِى ﴿٢٧﴾ يَفْقَهُواْ قَوْلِى ﴿٢٨﴾',
    phonetic: 'Rabbi shrah lî sadrî, wa yassir lî amrî, wa hlul \'uqdatan min lisânî, yafqahû qawlî.',
    french: 'Ô mon Seigneur, ouvre-moi ma poitrine, et facilite ma mission, et dénoue un nœud en ma langue, afin qu\'ils comprennent mes paroles.',
    target: 1,
    source: 'Coran 20:25-28 — Invocation du Prophète Mûsâ (عليه السلام)',
  },
  {
    title: 'Invocation de Yûnus (عليه السلام)',
    arabic: 'لَّآ إِلَٰهَ إِلَّآ أَنتَ سُبْحَٰنَكَ إِنِّى كُنتُ مِنَ ٱلظَّٰلِمِينَ',
    phonetic: 'Lâ ilâha illâ Anta, subhânaka, innî kuntu mina zh-zhâlimîn.',
    french: 'Pas de divinité à part Toi ! Pureté à Toi ! J\'ai été certes du nombre des injustes.',
    target: 3,
    source: 'Coran 21:87 — Invocation du Prophète Yûnus (عليه السلام) — At-Tirmidhî n°3505',
  },
  {
    title: 'Sourate Al-Hashr (v.22-24)',
    arabic: 'هُوَ ٱللَّهُ ٱلَّذِى لَآ إِلَٰهَ إِلَّا هُوَ ۖ عَٰلِمُ ٱلْغَيْبِ وَٱلشَّهَٰدَةِ ۖ هُوَ ٱلرَّحْمَٰنُ ٱلرَّحِيمُ ﴿٢٢﴾ هُوَ ٱللَّهُ ٱلَّذِى لَآ إِلَٰهَ إِلَّا هُوَ ٱلْمَلِكُ ٱلْقُدُّوسُ ٱلسَّلَٰمُ ٱلْمُؤْمِنُ ٱلْمُهَيْمِنُ ٱلْعَزِيزُ ٱلْجَبَّارُ ٱلْمُتَكَبِّرُ ۚ سُبْحَٰنَ ٱللَّهِ عَمَّا يُشْرِكُونَ ﴿٢٣﴾',
    phonetic: 'Huwa llâhu lladhî lâ ilâha illâ Huwa, \'Âlimu l-ghaybi wa sh-shahâda, Huwa r-Rahmânu r-Rahîm...',
    french: 'C\'est Lui, Allah (عز وجل). Nulle divinité autre que Lui, le Connaisseur de l\'Invisible et du Visible. C\'est Lui, le Tout Miséricordieux, le Très Miséricordieux. Le Souverain, le Pur, l\'Apaisant, le Rassurant, le Prédominant, le Tout-Puissant, le Contraignant, l\'Orgueilleux. Gloire à Allah (عز وجل) !',
    target: 1,
    source: 'Coran 59:22-24 — At-Tirmidhî n°3474',
  },
  {
    title: 'Demande de pardon',
    arabic: 'رَبَّنَا ظَلَمْنَآ أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ ٱلْخَٰسِرِينَ',
    phonetic: 'Rabbanâ zhalamnâ anfusanâ wa in lam taghfir lanâ wa tarhamnâ lanakûnanna mina l-khâsirîn.',
    french: 'Ô notre Seigneur, nous nous sommes fait du tort à nous-mêmes. Et si Tu ne nous pardonnes pas et ne nous fais pas miséricorde, nous serons certes parmi les perdants.',
    target: 3,
    source: 'Coran 7:23 — Invocation d\'Âdam (عليه السلام) et Hawwâ\'',
  },
  {
    title: 'Demande de guidance',
    arabic: 'رَبَّنَآ ءَاتِنَا فِى ٱلدُّنْيَا حَسَنَةً وَفِى ٱلْءَاخِرَةِ حَسَنَةً وَقِنَا عَذَابَ ٱلنَّارِ',
    phonetic: 'Rabbanâ âtinâ fi d-dunyâ hasanatan wa fi l-âkhirati hasanatan wa qinâ \'adhâba n-nâr.',
    french: 'Ô notre Seigneur ! Accorde-nous belle part en ce monde, et belle part aussi dans l\'au-delà ; et protège-nous du châtiment du Feu !',
    target: 3,
    source: 'Coran 2:201 — Muslim n°2690',
  },
  {
    title: 'Confiance en Allah (عز وجل)',
    arabic: 'حَسْبُنَا ٱللَّهُ وَنِعْمَ ٱلْوَكِيلُ',
    phonetic: 'Hasbunâ llâhu wa ni\'ma l-wakîl.',
    french: 'Allah (عز وجل) nous suffit, Il est notre meilleur Garant.',
    target: 7,
    source: 'Coran 3:173 — Al-Bukhârî n°4563',
  },
  {
    title: 'Invocation de Zakariyyâ (عليه السلام)',
    arabic: 'رَبِّ لَا تَذَرْنِى فَرْدًا وَأَنتَ خَيْرُ ٱلْوَٰرِثِينَ',
    phonetic: 'Rabbi lâ tadharnî fardan wa Anta khayru l-wârithîn.',
    french: 'Ô mon Seigneur, ne me laisse pas seul, et Tu es le meilleur des héritiers.',
    target: 3,
    source: 'Coran 21:89 — Invocation du Prophète Zakariyyâ (عليه السلام)',
  },
];

export const SUNNA_INVOCATIONS: DhikrItem[] = [
  {
    title: 'Istikhâra — La consultation',
    arabic: 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ، وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ، وَأَسْأَلُكَ مِنْ فَضْلِكَ العَظِيمِ، فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ، وَتَعْلَمُ وَلَا أَعْلَمُ، وَأَنْتَ عَلَّامُ الغُيُوبِ',
    phonetic: 'Allâhumma innî astakhîruka bi\'ilmika, wa astaqdiruka biqudratika, wa as\'aluka min fadlika l-\'azhîm...',
    french: 'Ô Allah (عز وجل), je Te consulte par Ta science, et je Te demande de me donner le pouvoir par Ta puissance, et je Te demande de Ton immense faveur. Car Tu es Capable et je suis incapable, Tu sais et je ne sais pas, et Tu connais les choses invisibles.',
    target: 1,
    source: 'Al-Bukhârî n°1162 — Enseignée par le Prophète Mouhamed (ﷺ)',
  },
  {
    title: 'Maître du pardon (Sayyid al-Istighfâr)',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي، فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    phonetic: 'Allâhumma Anta Rabbî, lâ ilâha illâ Ant. Khalaqtanî wa anâ \'abduka, wa anâ \'alâ \'ahdika wa wa\'dika mâ stata\'t...',
    french: 'Ô Allah (عز وجل), Tu es mon Seigneur, il n\'y a de divinité que Toi. Tu m\'as créé et je suis Ton serviteur. Je suis fidèle à Ton pacte et à Ta promesse autant que je le puis. Je me réfugie auprès de Toi contre le mal de ce que j\'ai commis. Pardonne-moi, car nul ne pardonne les péchés si ce n\'est Toi.',
    target: 1,
    source: 'Al-Bukhârî n°6306 — Parole du Prophète Mouhamed (ﷺ)',
  },
  {
    title: 'Avant le repas',
    arabic: 'بِسْمِ اللَّهِ',
    phonetic: 'Bismillâh.',
    french: 'Au nom d\'Allah (عز وجل).',
    target: 1,
    source: 'Muslim n°2017 — Enseignement du Prophète Mouhamed (ﷺ)',
  },
  {
    title: 'Après le repas',
    arabic: 'الحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
    phonetic: 'Al-hamdu lillâhi lladhî at\'amanî hâdhâ wa razaqanîhi min ghayri hawlin minnî wa lâ quwwa.',
    french: 'Louange à Allah (عز وجل) qui m\'a nourri de cela et me l\'a attribué sans force ni puissance de ma part.',
    target: 1,
    source: 'Abû Dâwûd n°4023, At-Tirmidhî n°3458 — Parole du Prophète Mouhamed (ﷺ)',
  },
  {
    title: 'Entrée de la mosquée',
    arabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    phonetic: 'Allâhumma ftah lî abwâba rahmatik.',
    french: 'Ô Allah (عز وجل), ouvre-moi les portes de Ta miséricorde.',
    target: 1,
    source: 'Muslim n°713 — Parole du Prophète Mouhamed (ﷺ)',
  },
  {
    title: 'Sortie de la mosquée',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
    phonetic: 'Allâhumma innî as\'aluka min fadlik.',
    french: 'Ô Allah (عز وجل), je Te demande de Ta grâce.',
    target: 1,
    source: 'Muslim n°713 — Parole du Prophète Mouhamed (ﷺ)',
  },
  {
    title: 'Invocation du voyage',
    arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
    phonetic: 'Subhâna lladhî sakhkhara lanâ hâdhâ wa mâ kunnâ lahu muqrinîn, wa innâ ilâ Rabbinâ lamunqalibûn.',
    french: 'Gloire à Celui qui nous a soumis cela, alors que nous n\'étions pas capables de le dompter. Et c\'est vers notre Seigneur que nous retournerons.',
    target: 1,
    source: 'Coran 43:13-14, Muslim n°1342 — Sunna du Prophète Mouhamed (ﷺ)',
  },
  {
    title: 'Contre l\'angoisse',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالحَزَنِ، وَالعَجْزِ وَالكَسَلِ، وَالبُخْلِ وَالجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ',
    phonetic: 'Allâhumma innî a\'ûdhu bika mina l-hammi wa l-hazan, wa l-\'ajzi wa l-kasal, wa l-bukhli wa l-jubn, wa dala\'i d-dayni wa ghalabati r-rijâl.',
    french: 'Ô Allah (عز وجل), je cherche refuge auprès de Toi contre les soucis et la tristesse, contre l\'incapacité et la paresse, contre l\'avarice et la lâcheté, contre le fardeau des dettes et la domination des hommes.',
    target: 3,
    source: 'Al-Bukhârî n°6369 — Invocation régulière du Prophète Mouhamed (ﷺ)',
  },
  {
    title: 'Au réveil',
    arabic: 'الحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَمَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    phonetic: 'Al-hamdu lillâhi lladhî ahyânâ ba\'da mâ amâtanâ wa ilayhi n-nushûr.',
    french: 'Louange à Allah (عز وجل) qui nous a rendu la vie après nous avoir fait mourir, et c\'est vers Lui la résurrection.',
    target: 1,
    source: 'Al-Bukhârî n°6312 — Parole du Prophète Mouhamed (ﷺ)',
  },
  {
    title: 'Avant de dormir',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    phonetic: 'Bismika llâhumma amûtu wa ahyâ.',
    french: 'En Ton nom, ô Allah (عز وجل), je meurs et je vis.',
    target: 1,
    source: 'Al-Bukhârî n°6314 — Parole du Prophète Mouhamed (ﷺ)',
  },
  {
    title: 'Invocation pour les parents',
    arabic: 'رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    phonetic: 'Rabbi rhamhumâ kamâ rabbayânî saghîrâ.',
    french: 'Ô Seigneur, fais-leur miséricorde comme ils m\'ont élevé tout petit.',
    target: 3,
    source: 'Coran 17:24',
  },
  {
    title: 'Protection contre le mal',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    phonetic: 'A\'ûdhu bikalimâti llâhi t-tâmmâti min sharri mâ khalaq.',
    french: 'Je cherche refuge dans les paroles parfaites d\'Allah (عز وجل) contre le mal de ce qu\'Il a créé.',
    target: 3,
    source: 'Muslim n°2708 — Parole du Prophète Mouhamed (ﷺ)',
  },
];

export const SALAWAT: DhikrItem[] = [
  {
    title: 'Salât Ibrâhîmiyya',
    arabic: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ. اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ',
    phonetic: 'Allâhumma salli \'alâ Muhammadin wa \'alâ âli Muhammad, kamâ sallayta \'alâ Ibrâhîma wa \'alâ âli Ibrâhîm, innaka Hamîdun Majîd. Allâhumma bârik \'alâ Muhammadin wa \'alâ âli Muhammad, kamâ bârakta \'alâ Ibrâhîma wa \'alâ âli Ibrâhîm, innaka Hamîdun Majîd.',
    french: 'Ô Allah (عز وجل), prie sur Mouhamed (ﷺ) et sur la famille de Mouhamed (ﷺ), comme Tu as prié sur Ibrâhîm (عليه السلام) et la famille d\'Ibrâhîm (عليه السلام). Tu es certes Digne de louange et de gloire.',
    target: 10,
    source: 'Al-Bukhârî n°3370, Muslim n°406',
  },
  {
    title: 'Salât simple',
    arabic: 'اللَّهُمَّ صَلِّ وَسَلِّمْ عَلَى نَبِيِّنَا مُحَمَّدٍ',
    phonetic: 'Allâhumma salli wa sallim \'alâ nabiyyinâ Muhammad.',
    french: 'Ô Allah (عز وجل), prie et accorde le salut à notre Prophète Mouhamed (ﷺ).',
    target: 33,
    source: 'At-Tirmidhî n°484 — Le Prophète (ﷺ) a dit : « Quiconque prie sur moi une fois, Allah (عز وجل) prie sur lui dix fois. »',
  },
  {
    title: 'Salât avec Salâm',
    arabic: 'صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ',
    phonetic: 'Salla llâhu \'alayhi wa sallam.',
    french: 'Qu\'Allah (عز وجل) prie sur lui (ﷺ) et lui accorde le salut.',
    target: 100,
    source: 'Muslim n°408 — Le Prophète (ﷺ) a dit : « Le plus proche de moi le Jour du Jugement sera celui qui aura le plus prié sur moi. »',
  },
  {
    title: 'Salât du vendredi',
    arabic: 'اللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى سَيِّدِنَا مُحَمَّدٍ وَعَلَى آلِهِ وَصَحْبِهِ أَجْمَعِينَ',
    phonetic: 'Allâhumma salli wa sallim wa bârik \'alâ sayyidinâ Muhammadin wa \'alâ âlihi wa sahbihi ajma\'în.',
    french: 'Ô Allah (عز وجل), prie, accorde le salut et bénis notre maître Mouhamed (ﷺ), sa famille et tous ses compagnons.',
    target: 10,
    source: 'Abû Dâwûd n°1047 — Le Prophète (ﷺ) a dit : « Multipliez la prière sur moi le vendredi. »',
  },
  {
    title: 'Salât Tunjîna',
    arabic: 'اللَّهُمَّ صَلِّ عَلَى سَيِّدِنَا مُحَمَّدٍ صَلَاةً تُنْجِينَا بِهَا مِنْ جَمِيعِ الأَهْوَالِ وَالآفَاتِ، وَتَقْضِي لَنَا بِهَا جَمِيعَ الحَاجَاتِ، وَتُطَهِّرُنَا بِهَا مِنْ جَمِيعِ السَّيِّئَاتِ، وَتَرْفَعُنَا بِهَا أَعْلَى الدَّرَجَاتِ، وَتُبَلِّغُنَا بِهَا أَقْصَى الغَايَاتِ مِنْ جَمِيعِ الخَيْرَاتِ فِي الحَيَاةِ وَبَعْدَ الْمَمَاتِ',
    phonetic: 'Allâhumma salli \'alâ sayyidinâ Muhammadin salâtan tunjînâ bihâ min jamî\'i l-ahwâli wa l-âfât...',
    french: 'Ô Allah (عز وجل), prie sur notre maître Mouhamed (ﷺ) d\'une prière qui nous sauve de toutes les frayeurs et calamités, qui nous comble de tous les besoins, qui nous purifie de toutes les mauvaises actions, qui nous élève aux plus hauts degrés.',
    target: 10,
    source: 'Formule traditionnelle de salât sur le Prophète (ﷺ)',
  },
  {
    title: 'Salât courte — Série rapide',
    arabic: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ',
    phonetic: 'Allâhumma salli \'alâ Muhammad.',
    french: 'Ô Allah (عز وجل), prie sur Mouhamed (ﷺ).',
    target: 100,
    source: 'An-Nasâ\'î n°1297 — Format court pour les séries de salawât',
  },
  {
    title: 'Salât par la mention',
    arabic: 'صَلُّوا عَلَيْهِ وَسَلِّمُوا تَسْلِيمًا',
    phonetic: 'Sallû \'alayhi wa sallimû taslîmâ.',
    french: 'Priez sur lui (ﷺ) et saluez-le d\'un salut.',
    target: 10,
    source: 'Coran 33:56 — Ordre divin de prier sur le Prophète (ﷺ)',
  },
  {
    title: 'Salât complète avec intercession',
    arabic: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ وَأَعْطِهِ الوَسِيلَةَ وَالفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ',
    phonetic: 'Allâhumma salli \'alâ Muhammadin wa \'alâ âli Muhammad, wa a\'tihi l-wasîlata wa l-fadîla, wab\'athhu maqâman mahmûdan alladhî wa\'adtah.',
    french: 'Ô Allah (عز وجل), prie sur Mouhamed (ﷺ) et sur la famille de Mouhamed (ﷺ), accorde-lui le Wasîla et la grâce, et ressuscite-le au rang louable que Tu lui as promis.',
    target: 10,
    source: 'Al-Bukhârî n°614 — Invocation après l\'adhân',
  },
];
