// Liste des 114 sourates avec leur numéro de page de début
export const SURAHS = [
  { number: 1, name: "Al-Fatiha", nameFr: "L'Ouverture", startPage: 1 },
  { number: 2, name: "Al-Baqara", nameFr: "La Vache", startPage: 2 },
  { number: 3, name: "Al-Imran", nameFr: "La Famille d'Imran", startPage: 50 },
  { number: 4, name: "An-Nisa", nameFr: "Les Femmes", startPage: 77 },
  { number: 5, name: "Al-Ma'ida", nameFr: "La Table Servie", startPage: 106 },
  { number: 6, name: "Al-An'am", nameFr: "Les Bestiaux", startPage: 128 },
  { number: 7, name: "Al-A'raf", nameFr: "Les Murailles", startPage: 151 },
  { number: 8, name: "Al-Anfal", nameFr: "Le Butin", startPage: 177 },
  { number: 9, name: "At-Tawba", nameFr: "Le Repentir", startPage: 187 },
  { number: 10, name: "Yunus", nameFr: "Jonas", startPage: 208 },
  { number: 11, name: "Hud", nameFr: "Houd", startPage: 221 },
  { number: 12, name: "Yusuf", nameFr: "Joseph", startPage: 235 },
  { number: 13, name: "Ar-Ra'd", nameFr: "Le Tonnerre", startPage: 249 },
  { number: 14, name: "Ibrahim", nameFr: "Abraham", startPage: 255 },
  { number: 15, name: "Al-Hijr", nameFr: "Al-Hijr", startPage: 262 },
  { number: 16, name: "An-Nahl", nameFr: "Les Abeilles", startPage: 267 },
  { number: 17, name: "Al-Isra", nameFr: "Le Voyage Nocturne", startPage: 282 },
  { number: 18, name: "Al-Kahf", nameFr: "La Caverne", startPage: 293 },
  { number: 19, name: "Maryam", nameFr: "Marie", startPage: 305 },
  { number: 20, name: "Ta-Ha", nameFr: "Ta-Ha", startPage: 312 },
  { number: 21, name: "Al-Anbiya", nameFr: "Les Prophètes", startPage: 322 },
  { number: 22, name: "Al-Hajj", nameFr: "Le Pèlerinage", startPage: 332 },
  { number: 23, name: "Al-Mu'minun", nameFr: "Les Croyants", startPage: 342 },
  { number: 24, name: "An-Nur", nameFr: "La Lumière", startPage: 350 },
  { number: 25, name: "Al-Furqan", nameFr: "Le Discernement", startPage: 359 },
  { number: 26, name: "Ash-Shu'ara", nameFr: "Les Poètes", startPage: 367 },
  { number: 27, name: "An-Naml", nameFr: "Les Fourmis", startPage: 377 },
  { number: 28, name: "Al-Qasas", nameFr: "Le Récit", startPage: 385 },
  { number: 29, name: "Al-Ankabut", nameFr: "L'Araignée", startPage: 396 },
  { number: 30, name: "Ar-Rum", nameFr: "Les Romains", startPage: 404 },
  { number: 31, name: "Luqman", nameFr: "Luqman", startPage: 411 },
  { number: 32, name: "As-Sajda", nameFr: "La Prosternation", startPage: 415 },
  { number: 33, name: "Al-Ahzab", nameFr: "Les Coalisés", startPage: 418 },
  { number: 34, name: "Saba", nameFr: "Saba", startPage: 428 },
  { number: 35, name: "Fatir", nameFr: "Le Créateur", startPage: 434 },
  { number: 36, name: "Ya-Sin", nameFr: "Ya-Sin", startPage: 440 },
  { number: 37, name: "As-Saffat", nameFr: "Les Rangés", startPage: 446 },
  { number: 38, name: "Sad", nameFr: "Sad", startPage: 453 },
  { number: 39, name: "Az-Zumar", nameFr: "Les Groupes", startPage: 458 },
  { number: 40, name: "Ghafir", nameFr: "Le Pardonneur", startPage: 467 },
  { number: 41, name: "Fussilat", nameFr: "Les Versets Détaillés", startPage: 477 },
  { number: 42, name: "Ash-Shura", nameFr: "La Consultation", startPage: 483 },
  { number: 43, name: "Az-Zukhruf", nameFr: "L'Ornement", startPage: 489 },
  { number: 44, name: "Ad-Dukhan", nameFr: "La Fumée", startPage: 496 },
  { number: 45, name: "Al-Jathiya", nameFr: "L'Agenouillée", startPage: 499 },
  { number: 46, name: "Al-Ahqaf", nameFr: "Les Dunes", startPage: 502 },
  { number: 47, name: "Muhammad", nameFr: "Muhammad", startPage: 507 },
  { number: 48, name: "Al-Fath", nameFr: "La Victoire", startPage: 511 },
  { number: 49, name: "Al-Hujurat", nameFr: "Les Appartements", startPage: 515 },
  { number: 50, name: "Qaf", nameFr: "Qaf", startPage: 518 },
  { number: 51, name: "Adh-Dhariyat", nameFr: "Qui Éparpillent", startPage: 520 },
  { number: 52, name: "At-Tur", nameFr: "Le Mont", startPage: 523 },
  { number: 53, name: "An-Najm", nameFr: "L'Étoile", startPage: 526 },
  { number: 54, name: "Al-Qamar", nameFr: "La Lune", startPage: 528 },
  { number: 55, name: "Ar-Rahman", nameFr: "Le Tout Miséricordieux", startPage: 531 },
  { number: 56, name: "Al-Waqi'a", nameFr: "L'Événement", startPage: 534 },
  { number: 57, name: "Al-Hadid", nameFr: "Le Fer", startPage: 537 },
  { number: 58, name: "Al-Mujadila", nameFr: "La Discussion", startPage: 542 },
  { number: 59, name: "Al-Hashr", nameFr: "L'Exode", startPage: 545 },
  { number: 60, name: "Al-Mumtahina", nameFr: "L'Éprouvée", startPage: 549 },
  { number: 61, name: "As-Saff", nameFr: "Le Rang", startPage: 551 },
  { number: 62, name: "Al-Jumu'a", nameFr: "Le Vendredi", startPage: 553 },
  { number: 63, name: "Al-Munafiqun", nameFr: "Les Hypocrites", startPage: 554 },
  { number: 64, name: "At-Taghabun", nameFr: "La Grande Perte", startPage: 556 },
  { number: 65, name: "At-Talaq", nameFr: "Le Divorce", startPage: 558 },
  { number: 66, name: "At-Tahrim", nameFr: "L'Interdiction", startPage: 560 },
  { number: 67, name: "Al-Mulk", nameFr: "La Royauté", startPage: 562 },
  { number: 68, name: "Al-Qalam", nameFr: "La Plume", startPage: 564 },
  { number: 69, name: "Al-Haqqa", nameFr: "Celle qui Montre la Vérité", startPage: 566 },
  { number: 70, name: "Al-Ma'arij", nameFr: "Les Voies d'Ascension", startPage: 568 },
  { number: 71, name: "Nuh", nameFr: "Noé", startPage: 570 },
  { number: 72, name: "Al-Jinn", nameFr: "Les Djinns", startPage: 572 },
  { number: 73, name: "Al-Muzzammil", nameFr: "L'Enveloppé", startPage: 574 },
  { number: 74, name: "Al-Muddaththir", nameFr: "Le Revêtu d'un Manteau", startPage: 575 },
  { number: 75, name: "Al-Qiyama", nameFr: "La Résurrection", startPage: 577 },
  { number: 76, name: "Al-Insan", nameFr: "L'Homme", startPage: 578 },
  { number: 77, name: "Al-Mursalat", nameFr: "Les Envoyés", startPage: 580 },
  { number: 78, name: "An-Naba", nameFr: "La Nouvelle", startPage: 582 },
  { number: 79, name: "An-Nazi'at", nameFr: "Les Anges qui Arrachent", startPage: 583 },
  { number: 80, name: "Abasa", nameFr: "Il s'est Renfrogné", startPage: 585 },
  { number: 81, name: "At-Takwir", nameFr: "L'Obscurcissement", startPage: 586 },
  { number: 82, name: "Al-Infitar", nameFr: "La Rupture", startPage: 587 },
  { number: 83, name: "Al-Mutaffifin", nameFr: "Les Fraudeurs", startPage: 587 },
  { number: 84, name: "Al-Inshiqaq", nameFr: "La Déchirure", startPage: 589 },
  { number: 85, name: "Al-Buruj", nameFr: "Les Constellations", startPage: 590 },
  { number: 86, name: "At-Tariq", nameFr: "L'Astre Nocturne", startPage: 591 },
  { number: 87, name: "Al-A'la", nameFr: "Le Très-Haut", startPage: 591 },
  { number: 88, name: "Al-Ghashiya", nameFr: "L'Enveloppante", startPage: 592 },
  { number: 89, name: "Al-Fajr", nameFr: "L'Aube", startPage: 593 },
  { number: 90, name: "Al-Balad", nameFr: "La Cité", startPage: 594 },
  { number: 91, name: "Ash-Shams", nameFr: "Le Soleil", startPage: 595 },
  { number: 92, name: "Al-Layl", nameFr: "La Nuit", startPage: 595 },
  { number: 93, name: "Ad-Duha", nameFr: "Le Jour Montant", startPage: 596 },
  { number: 94, name: "Ash-Sharh", nameFr: "L'Ouverture de la Poitrine", startPage: 596 },
  { number: 95, name: "At-Tin", nameFr: "Le Figuier", startPage: 597 },
  { number: 96, name: "Al-Alaq", nameFr: "L'Adhérence", startPage: 597 },
  { number: 97, name: "Al-Qadr", nameFr: "La Destinée", startPage: 598 },
  { number: 98, name: "Al-Bayyina", nameFr: "La Preuve", startPage: 598 },
  { number: 99, name: "Az-Zalzala", nameFr: "La Secousse", startPage: 599 },
  { number: 100, name: "Al-Adiyat", nameFr: "Les Coursiers", startPage: 599 },
  { number: 101, name: "Al-Qari'a", nameFr: "Le Fracas", startPage: 600 },
  { number: 102, name: "At-Takathur", nameFr: "La Course aux Richesses", startPage: 600 },
  { number: 103, name: "Al-Asr", nameFr: "Le Temps", startPage: 601 },
  { number: 104, name: "Al-Humaza", nameFr: "Les Calomniateurs", startPage: 601 },
  { number: 105, name: "Al-Fil", nameFr: "L'Éléphant", startPage: 601 },
  { number: 106, name: "Quraysh", nameFr: "Quraysh", startPage: 602 },
  { number: 107, name: "Al-Ma'un", nameFr: "L'Ustensile", startPage: 602 },
  { number: 108, name: "Al-Kawthar", nameFr: "L'Abondance", startPage: 602 },
  { number: 109, name: "Al-Kafirun", nameFr: "Les Mécréants", startPage: 603 },
  { number: 110, name: "An-Nasr", nameFr: "Le Secours", startPage: 603 },
  { number: 111, name: "Al-Masad", nameFr: "Les Fibres", startPage: 603 },
  { number: 112, name: "Al-Ikhlas", nameFr: "Le Monothéisme Pur", startPage: 604 },
  { number: 113, name: "Al-Falaq", nameFr: "L'Aube Naissante", startPage: 604 },
  { number: 114, name: "An-Nas", nameFr: "Les Hommes", startPage: 604 },
];

// Fonction pour trouver la sourate actuelle basée sur le numéro de page
export function getSurahByPage(pageNumber: number): { name: string; nameFr: string; number: number } | null {
  if (pageNumber < 1 || pageNumber > 604) return null;
  
  // Find the surah that contains this page (the last surah whose startPage <= pageNumber)
  for (let i = SURAHS.length - 1; i >= 0; i--) {
    if (SURAHS[i].startPage <= pageNumber) {
      return { name: SURAHS[i].name, nameFr: SURAHS[i].nameFr, number: SURAHS[i].number };
    }
  }
  return { name: SURAHS[0].name, nameFr: SURAHS[0].nameFr, number: SURAHS[0].number };
}
