/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare let self: ServiceWorkerGlobalScope;

// Take control immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// Cache Google Fonts
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'gstatic-fonts-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// ===== PUSH NOTIFICATION HANDLERS =====

self.addEventListener('push', (event) => {
  let data = {
    title: '🌙 Rappel Makhatma',
    body: "Assalamou aleykoum ! C'est le moment de ta lecture pour rester régulier(e) avec le Livre d'Allah (عز وجل). Prêt(e) pour tes pages du jour ?",
    icon: '/favicon.png',
    url: '/accueil',
  };

  try {
    if (event.data) {
      const text = event.data.text();
      if (text && text.length > 0) {
        const parsed = JSON.parse(text);
        data = { ...data, ...parsed };
      }
    }
  } catch (_e) {
    // No payload or parse error — use default message
  }

  const options: Record<string, unknown> = {
    body: data.body,
    icon: data.icon || '/favicon.png',
    badge: '/pwa-192x192.png',
    tag: 'makhatma-reminder',
    renotify: true,
    vibrate: [200, 100, 200],
    data: { url: data.url || '/accueil' },
    actions: [
      { action: 'open', title: '📖 Ouvrir Ma Khatma' },
      { action: 'dismiss', title: 'Plus tard' },
    ],
  };

  event.waitUntil(
    // @ts-ignore - showNotification accepts extended options
    self.registration.showNotification(data.title, options)
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const url = event.notification.data?.url || '/accueil';

  if (event.action === 'dismiss') return;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          (client as WindowClient).navigate(url);
          return (client as WindowClient).focus();
        }
      }
      return self.clients.openWindow(url);
    })
  );
});
